Repository vertexproject/synapse, pull requests merged in 2018-05, with the labels that each got.

#744 010 material model
  synapse/lib/modules.py
  synapse/lib/xact.py
  synapse/models/material.py
  synapse/tests/test_model_material.py
Labels: enhancement

#745 Feature authdeny mesg
  synapse/cores/common.py
  synapse/lib/auth.py
  synapse/lib/storm.py
Labels: documentation, enhancement

#746 mac: Do not rebuild python for each synapse version change
  .circleci/config.yml
Labels: enhancement

#743 Ports inet:cidr, inet:ipv6, inet:url to 010
  synapse/models/inet.py
  synapse/models/inet.py.old
  synapse/tests/test_model_inet.py
Labels: enhancement

#748 Remove migrations and migration tests
  synapse/models/crypto.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/models/syn.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_person.py
  synapse/tests/test_model_syn.py
Labels: enhancement

#749 Clean up synapse/__init__.py, require python 3.6
  .circleci/config.yml
  setup.py
  synapse/__init__.py
Labels: enhancement

#753 010 setup
  setup.py
Labels: enhancement

#754 Fix tests for circleci
  synapse/tests/files/dmonboot/dmon.yaml
  synapse/tests/files/dmoncore/dmon.yaml
  synapse/tests/files/dmontest/dmon.yaml
Labels: bug

#751 implement Hex base type. Use it to implement the crypto module.
  synapse/datamodel.py
  synapse/lib/chop.py
  synapse/lib/modules.py
  synapse/lib/types.py
  synapse/models/crypto.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_chop.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_crypto.py
Labels: enhancement

#757 Restore simple inet:dns:a forms
  synapse/lib/modules.py
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: enhancement

#761 010 telco
  synapse/lib/modules.py
  synapse/models/telco.py
  synapse/tests/test_model_telco.py
Labels: enhancement

#756 010 gov model
  synapse/lib/modules.py
  synapse/models/gov/cn.py
  synapse/models/gov/intl.py
  synapse/models/gov/us.py
  synapse/tests/test_model_gov_cn.py
  synapse/tests/test_model_gov_intl.py
  synapse/tests/test_model_gov_us.py
Labels: enhancement

#760 Tighten up Hex type
  synapse/lib/types.py
  synapse/tests/test_lib_types.py
Labels: enhancement

#755 Ports most of geospace module to 010
  synapse/lib/modules.py
  synapse/lib/types.py
  synapse/models/geospace.py
  synapse/models/inet.py
  synapse/tests/test_model_geospace.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#764 lift operation optimization
  synapse/datamodel.py
  synapse/lib/layer.py
  synapse/lib/node.py
  synapse/lib/types.py
  synapse/lib/xact.py
  synapse/models/inet.py
  synapse/models/telco.py
  synapse/tests/test_cortex.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_geopol.py
  synapse/tests/test_model_gov_us.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_language.py
Labels: enhancement

#750 Porting more 010 inet forms/types
  synapse/lib/node.py
  synapse/models/geospace.py
  synapse/models/inet.py
  synapse/models/inet.py.old
  synapse/tests/test_model_inet.py
Labels: enhancement

#767 Port inet:wifi:* and inet:urlredir to 010
  synapse/models/inet.py
  synapse/models/inet.py.old
  synapse/tests/test_model_inet.py
Labels: enhancement

#769 Add a time.sleep in the _runPollLoop
  synapse/lib/net.py
Labels: bug

#768 Port inet:net4, inet:asnet4. Add Range base type, add support for negative integers
  .gitignore
  synapse/datamodel.py
  synapse/exc.py
  synapse/lib/types.py
  synapse/models/inet.py
  synapse/models/inet.py.old
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#772 010 person
  synapse/lib/modules.py
  synapse/lib/types.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_chop.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_person.py
Labels: enhancement

#776 splices, snap() conversion, and tags
  synapse/cortex.py
  synapse/datamodel.py
  synapse/eventbus.py
  synapse/exc.py
  synapse/lib/cache.py
  synapse/lib/chop.py
  synapse/lib/layer.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/types.py
  synapse/models/crypto.py
  synapse/models/dns.py
  synapse/models/files.py
  synapse/models/inet.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cache.py
  synapse/tests/test_lib_chop.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_base.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_dns.py
  synapse/tests/test_model_files.py
  synapse/tests/test_model_geopol.py
  synapse/tests/test_model_gov_cn.py
  synapse/tests/test_model_gov_intl.py
  synapse/tests/test_model_gov_us.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_language.py
  synapse/tests/test_model_material.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_person.py
  synapse/tests/test_model_syn.py
  synapse/tests/test_model_telco.py
  synapse/tests/utils.py
Labels: enhancement

#779 storm runtime and auth plumbing for remote cortex
  synapse/cmds/cortex.py
  synapse/common.py
  synapse/cortex.py
  synapse/daemon.py
  synapse/datamodel.py
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/cell.py
  synapse/lib/chop.py
  synapse/lib/cli.py
  synapse/lib/cmdr.py
  synapse/lib/layer.py
  synapse/lib/node.py
  synapse/lib/plex.py
  synapse/lib/snap.py
  synapse/lib/syntax.py
  synapse/lib/threads.py
  synapse/lib/types.py
  synapse/models/files.py
  synapse/models/geospace.py
  synapse/models/inet.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cli.py
  synapse/tests/test_lib_queue.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_syn.py
  synapse/tools/cmdr.py
Labels: enhancement

#781 010 ports
  synapse/models/inet.py
  synapse/models/inet.py.old
  synapse/tests/test_model_inet.py
  synapse/tests/utils.py
Labels: enhancement

#780 010 authdeny messages
  synapse/lib/cell.py
  synapse/lib/node.py
  synapse/lib/snap.py
Labels: enhancement

#784 Ports all remaining inet model elements
  synapse/lib/types.py
  synapse/models/inet.py
  synapse/models/inet.py.old
  synapse/tests/test_model_inet.py
  synapse/tests/utils.py
Labels: enhancement

#786 Last bits of the inet model port
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#788 010 bug cryo
  synapse/cryotank.py
Labels: bug

#789 Adds str norm to nodeprop, cleans up synapse/lib/types tests
  synapse/lib/types.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: enhancement

#790 WIP: 010 model sweep
  synapse/lib/modules.py
  synapse/models/files.py
  synapse/models/language.py
  synapse/models/material.py
  synapse/models/media.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/models/temporal.py
  synapse/tests/test_model_material.py
  synapse/tests/test_model_media.py
  synapse/tests/test_model_temporal.py
Labels: enhancement

#794 Add enums option to Str type.
  synapse/lib/types.py
  synapse/tests/test_lib_types.py
Labels: enhancement

#792 010 model fixes
  synapse/models/gov/cn.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/tests/test_model_gov_cn.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_person.py
  synapse/tests/test_model_telco.py
Labels: enhancement

#795 cortex feeds and sync
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/types.py
  synapse/models/inet.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_model_orgs.py
  synapse/tests/utils.py
  synapse/tools/cryo/cat.py
Labels: enhancement

#797 absolute property filter syntax for storm
  synapse/lib/ast.py
  synapse/lib/syntax.py
  synapse/tests/test_cortex.py
Labels: enhancement

#800 added new pivot/join in/out syntax to storm
  synapse/cmds/cortex.py
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/lmdb.py
  synapse/lib/snap.py
  synapse/lib/syntax.py
  synapse/models/base.py
  synapse/models/dns.py
  synapse/models/inet.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_lmdb.py
  synapse/tests/test_model_dns.py
  synapse/tests/utils.py
Labels: enhancement

#801 010 getcoremods
  synapse/cortex.py
  synapse/daemon.py
  synapse/lib/module.py
  synapse/tests/files/dmoncoreauth/cells/core/boot.yaml
  synapse/tests/files/dmoncoreauth/cells/core/cell.yaml
  synapse/tests/files/dmoncoreauth/cells/core/mods/testmodule/conf.yaml
  synapse/tests/files/dmoncoreauth/dmon.yaml
  synapse/tests/test_cortex.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: enhancement

#802 Include our test code and test files in the synapse package.
  MANIFEST.in
  setup.py
  synapse/lib/cmpr.py
Labels: enhancement

#804 010 dns redux
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: enhancement

#799 Rejigger Genr/Share to cleanup on network disconnect.
  synapse/daemon.py
  synapse/lib/coro.py
  synapse/lib/layer.py
  synapse/lib/link.py
  synapse/lib/plex.py
  synapse/telepath.py
  synapse/tests/common.py
  synapse/tests/test_lib_coro.py
Labels: bug

#806 Add inet:addr types to it:exec:url and it:exec:bind.
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#805 Fix bug where telepath server drop hangs the client.
  synapse/telepath.py
Labels: bug

#807 010 setup.py
  .bumpversion.cfg
  setup.py
  synapse/lib/version.py
Labels: enhancement

#808 Make the feed size configurable for cryotank consumption.
  synapse/cortex.py
Labels: enhancement

#810 Add time/callAt/callLater functions to the plex.
  synapse/lib/plex.py
  synapse/tests/test_lib_plex.py
Labels: enhancement

#813 Removes synapse/lib/webapp.py
  synapse/lib/webapp.py
  synapse/tests/test_lib_webapp.py
Labels: enhancement

#816 dynamic snap writelocking, node deletion plumbing, storm priv elevation, and *type= lift cmpr
  synapse/cmds/cortex.py
  synapse/cortex.py
  synapse/datamodel.py
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/cache.py
  synapse/lib/layer.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/syntax.py
  synapse/models/files.py
  synapse/models/infotech.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_coro.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_base.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_dns.py
  synapse/tests/test_model_files.py
  synapse/tests/test_model_geopol.py
  synapse/tests/test_model_gov_cn.py
  synapse/tests/test_model_gov_intl.py
  synapse/tests/test_model_gov_us.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_language.py
  synapse/tests/test_model_material.py
  synapse/tests/test_model_media.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_person.py
  synapse/tests/test_model_syn.py
  synapse/tests/test_model_telco.py
  synapse/tests/utils.py
Labels: enhancement

#817 Make Cell.deploy() a classmethod so it has access to cls.confdefs
  synapse/cells.py
  synapse/lib/cell.py
  synapse/tests/test_cells.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: enhancement
