Repository vertexproject/synapse, pull requests merged in 2018-11, with the labels that each got.

#984 WIP - 010 model files pe
  synapse/models/files.py
Labels: bug

#988 010 task logging
  synapse/lib/cell.py
  synapse/tests/test_cmds_cortex.py
Labels: enhancement

#991 In Cortex coroloops which are sending or consuming data, catch OSErro…
  synapse/cortex.py
Labels: enhancement

#992 010 - Include Edge nodes in Paths when traversing them via noderefs --traverse-edge
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#990 Add a generic cluster node and unit test.
  synapse/models/base.py
  synapse/tests/test_model_base.py
Labels: enhancement

#997 010 nodeget bug
  synapse/lib/node.py
  synapse/tests/test_lib_node.py
Labels: bug

#999 catch a proppivotout issue.
  synapse/lib/ast.py
  synapse/tests/test_model_base.py
Labels: bug

#1005 ensure delnode yields periodically.
  synapse/lib/storm.py
Labels: bug

#1011 010 - edge repr support
  synapse/lib/chop.py
  synapse/lib/types.py
  synapse/tests/test_lib_chop.py
  synapse/tests/test_model_base.py
Labels: enhancement

#1012 Fix storm parsing where command is at end of subquery
  synapse/lib/syntax.py
  synapse/tests/test_cmds_trigger.py
  synapse/tests/test_lib_syntax.py
Labels: bug

#1007 Remote layer
  synapse/axon.py
  synapse/cells.py
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/layer.py
  synapse/lib/lmdblayer.py
  synapse/lib/remotelayer.py
  synapse/lib/snap.py
  synapse/tests/files/dmonlayer/cells/layer1/boot.yaml
  synapse/tests/files/dmonlayer/dmon.yaml
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_remotelayer.py
  synapse/tests/test_lib_snap.py
  synapse/tests/utils.py
Labels: enhancement

#1013 010 - inet:dns:name custom type
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: enhancement

#1016 010 testdir docs
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: documentation
