Repository vertexproject/synapse, pull requests merged in 2018-07, with the labels that each got.

#848 010 bug indx
  synapse/lib/types.py
  synapse/models/files.py
  synapse/models/inet.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_files.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_telco.py
Labels: bug

#851 Ensure that all uses of s_exc.BadTypeValu are consistent w/r/t mesg and valu
  synapse/lib/types.py
  synapse/lib/version.py
  synapse/models/files.py
  synapse/models/geospace.py
  synapse/models/inet.py
Labels: bug

#853 010 - Ensure name is present on badtypevalu exceptions
  synapse/lib/chop.py
  synapse/lib/types.py
  synapse/lib/version.py
  synapse/models/geospace.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/telco.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_base.py
  synapse/tests/test_model_geospace.py
Labels: enhancement

#846 010 docs
  docs/conf.py
  docs/synapse/userguide_section0.rst
  docs/synapse/userguides/ug001_synapse.rst
  docs/synapse/userguides/ug001_why_synapse.rst
  docs/synapse/userguides/ug002_bkd_graphs_hypergraphs.rst
  docs/synapse/userguides/ug002_graphintro.rst
  docs/synapse/userguides/ug003_bkd_dm_basics.rst
  docs/synapse/userguides/ug003_dm_basics.rst
  docs/synapse/userguides/ug004_bkd_model_introspect.rst
  docs/synapse/userguides/ug004_dm_concepts.rst
  docs/synapse/userguides/ug005_dm_form_cats.rst
  docs/synapse/userguides/ug005_dm_nodesconcepts.rst
  docs/synapse/userguides/ug006_dm_form_types.rst
  docs/synapse/userguides/ug006_dm_nodeprops.rst
  docs/synapse/userguides/ug007_am_tags_nodes.rst
  docs/synapse/userguides/ug007_dm_nodetypes.rst
  docs/synapse/userguides/ug008_am_tags_analysis.rst
  docs/synapse/userguides/ug008_dm_tagconcepts.rst
  docs/synapse/userguides/ug009_am_tags_other.rst
  docs/synapse/userguides/ug009_dm_tagmodel.rst
  docs/synapse/userguides/ug010_cmdr_cortex.rst
  docs/synapse/userguides/ug010_dc_data_model.rst
  docs/synapse/userguides/ug011_dc_analytical_model.rst
  docs/synapse/userguides/ug011_storm_basics.rst
  docs/synapse/userguides/ug012_dc_nodes_vs_tags.rst
  docs/synapse/userguides/ug012_storm_ref_datamod.rst
  docs/synapse/userguides/ug013_dc_node_deconfliction.rst
  docs/synapse/userguides/ug013_storm_ref_lift.rst
  docs/synapse/userguides/ug014_dc_layers.rst
  docs/synapse/userguides/ug014_storm_ref_filter.rst
  docs/synapse/userguides/ug015_storm_ref_pivot.rst
  docs/synapse/userguides/ug015_syn_commands.rst
  docs/synapse/userguides/ug016_storm_ref_byhandlers.rst
  docs/synapse/userguides/ug016_syn_storm.rst
  docs/synapse/userguides/ug017_storm_ref_stats.rst
  docs/synapse/userguides/ug017_syn_storm_reference.rst
  docs/synapse/userguides/ug018_storm_ref_misc.rst
  readthedocs.yml
  setup.py
  synapse/__init__.py
Labels: documentation

#850 010 37
  .circleci/config.yml
  setup.py
Labels: enhancement

#854 010 pivot safety
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/types.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: bug

#852 010 auth tweak
  synapse/cortex.py
  synapse/lib/auth.py
  synapse/lib/cell.py
  synapse/tests/files/dmoncoreauth/cells/core/cell.yaml
  synapse/tests/test_cortex.py
Labels: enhancement

#855 Proppivot feedback
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: enhancement

#856 010 - Change two log statements from warnings to errors.
  synapse/daemon.py
  synapse/lib/snap.py
Labels: enhancement

#859 Remove superhash tool
  synapse/tests/test_tools_superhash.py
  synapse/tools/superhash.py
Labels: enhancement

#860 010 fini police
  synapse/__init__.py
  synapse/cortex.py
  synapse/cryotank.py
  synapse/eventbus.py
  synapse/lib/auth.py
  synapse/lib/cell.py
  synapse/lib/layer.py
  synapse/lib/snap.py
  synapse/tests/test_utils.py
Labels: bug

#861 010 bug query
  synapse/lib/syntax.py
  synapse/tests/test_cortex.py
Labels: bug

#857 010 file:path fail on bare relative paths
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: bug

#863 Plumb a storm option to suppress unregistered messages being printed.
  synapse/cmds/cortex.py
  synapse/tests/test_cmds_cortex.py
Labels: enhancement

#865 allow feed functions to yield Node() objects at the Snap() API level.
  synapse/lib/snap.py
  synapse/tests/test_lib_snap.py
Labels: enhancement

#864 Plumb the layer:lmdb:mapsize option in the Cortex config into the default layer config.
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/tests/files/dmoncore/cells/core/cell.yaml
  synapse/tests/files/dmoncoreauth/cells/core/cell.yaml
  synapse/tests/files/testcore/cell.yaml
Labels: bug

#866 quick fix for negative constants
  synapse/lib/syntax.py
  synapse/tests/test_model_geospace.py
Labels: bug

#868 Add a debug message during cell config loading.
  synapse/lib/cell.py
Labels: enhancement

#862 010 ingest redux
  docs/synapse/examples/ingest_embed1.json
  docs/synapse/examples/ingest_embed2.json
  docs/synapse/examples/ingest_embed3.json
  docs/synapse/examples/ingest_embed4.json
  docs/synapse/examples/ingest_structured_dnsa1.csv
  docs/synapse/examples/ingest_structured_dnsa1.json
  docs/synapse/examples/ingest_structured_dnsa2.json
  docs/synapse/examples/ingest_structured_dnsa2.jsonl
  docs/synapse/examples/ingest_structured_nested_data.json
  docs/synapse/examples/ingest_structured_nested_def.json
  docs/synapse/examples/ingest_structured_nested_def2.json
  docs/synapse/examples/ingest_structured_nested_def3.json
  docs/synapse/examples/ingest_structured_tlds.txt
  docs/synapse/examples/ingest_structured_tlds1.json
  docs/synapse/userguide_section0.rst
  docs/synapse/userguides/ug050_ing_intro.rst
  docs/synapse/userguides/ug051_ing_tool.rst
  docs/synapse/userguides/ug052_ing_embed.rst
  docs/synapse/userguides/ug053_ing_lines.rst
  docs/synapse/userguides/ug054_ing_csv.rst
  docs/synapse/userguides/ug055_ing_json.rst
  docs/synapse/userguides/ug056_ing_jsonl.rst
  docs/synapse/userguides/ug057_ing_xml.rst
  docs/synapse/userguides/ug058_ing_filebytes.rst
  docs/synapse/userguides/ug059_ing_sync.rst
  docs/synapse/userguides/ug060_ing_format.rst
  docs/synapse/userguides/ug061_ing_conditional.rst
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/encoding.py
  synapse/lib/ingest.py
  synapse/lib/node.py
  synapse/lib/time.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_encoding.py
  synapse/tests/test_lib_ingest.py
  synapse/tests/test_tools_feed.py
  synapse/tests/test_tools_ingest.py
  synapse/tests/utils.py
  synapse/tools/backup.py
  synapse/tools/deploy.py
  synapse/tools/feed.py
  synapse/tools/ingest.py
Labels: enhancement

#869 Remove neuron files.
  synapse/neuron.py
  synapse/tests/test_axon.py
  synapse/tests/test_neuron.py
  synapse/tests/utils.py
  synapse/tools/neuron.py
Labels: enhancement

#870 Tweak testrunner
  scripts/testrunner.sh
Labels: enhancement

#872 Add a uniq command to storm.
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#873 010 - Change the way nodes are printed to be more copy-paste friendly
  synapse/cmds/cortex.py
  synapse/tests/test_tools_feed.py
Labels: bug

#874 010 bug comp repr
  synapse/lib/types.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: bug

#875 010 - Make PropPivot resilient to BadLiftValu
  synapse/lib/ast.py
  synapse/models/inet.py
  synapse/tests/test_model_dns.py
Labels: bug

#877 010 docker tweak
  Dockerfile
  synapse/cortex.py
Labels: enhancement

#879 010 guidstar
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: enhancement

#880 Remove sphinx pinning since 1.7.6 has been released.
  setup.py
Labels: bug

#878 010 storm iden
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#881 010 - Allow seeding storm queries with idens.
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: enhancement
