Repository vertexproject/synapse, pull requests merged in 2018-09, with the labels that each got.

#931 Add lmdb:readahead layer support
  .circleci/config.yml
  synapse/lib/lmdblayer.py
Labels: enhancement

#928 010 migration bugfixes and improvements
  synapse/tests/test_tools_migrate_010.py
  synapse/tools/migrate_010.py
Labels: enhancement

#930 010 - Loc filtering
  synapse/datamodel.py
  synapse/lib/types.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: enhancement

#932 010 ctx stats
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/lmdb.py
  synapse/lib/lmdblayer.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_lmdb.py
Labels: enhancement

#933 010 - Add a ou:name node test and promote ou:name to a form
  synapse/models/orgs.py
  synapse/tests/test_model_orgs.py
Labels: enhancement

#937 010 - Add unit tests showing and/or operator use in storm
  synapse/tests/test_cortex.py
Labels: enhancement

#926 WIP Model changes for ps:persona, ps:person, ou:org, ps:name
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_person.py
Labels: enhancement

#941 010 - better telepath aliases.yaml support
  synapse/telepath.py
  synapse/tests/test_telepath.py
  synapse/tests/utils.py
Labels: bug, enhancement

#940 010 - remove edit mode syntax for deleting nodes
  synapse/lib/syntax.py
  synapse/tests/test_cortex.py
Labels: bug

#939 Migrate ps:personx:has and ou:org:has to generic 'has' nodes
  synapse/tests/test_tools_migrate_010.py
  synapse/tools/migrate_010.py
Labels: enhancement

#943 010 - Add an optional client-side storm/splice log.
  synapse/cmds/cortex.py
  synapse/cortex.py
  synapse/lib/cmdr.py
  synapse/lib/encoding.py
  synapse/tests/test_cmds_cortex.py
  synapse/tests/test_lib_encoding.py
Labels: enhancement

#936 WIP / Discussion - 010 Plex fini
  synapse/axon.py
  synapse/daemon.py
  synapse/lib/plex.py
  synapse/tests/test_lib_plex.py
  synapse/tests/test_telepath.py
Labels: bug

#944 010 Additional plex fini cleanup
  synapse/tests/test_telepath.py
  synapse/tools/cmdr.py
Labels: bug

#947 Make scope.leave() to return the scope frame.
  synapse/lib/scope.py
  synapse/tests/test_lib_scope.py
Labels: enhancement

#948 010 logging
  synapse/cortex.py
Labels: enhancement

#950 010 dns model tweaks
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: bug, enhancement

#952 010 - Make movetags move tags on syn:tag nodes.
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#954 00x migration fixes for inet:dns:soa and it:dev:regval
  synapse/tests/test_tools_migrate_010.py
  synapse/tools/migrate_010.py
Labels: bug

#956 010 -Add a 3.7 dockerfile for 3.7 testing
  synapse/docker/Dockerfile-37
Labels: enhancement

#960 010 bug movetag
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug
