Repository vertexproject/synapse, pull requests merged in 2018-03, with the labels that each got.

#682 Celluser ebus
  synapse/cryotank.py
  synapse/neuron.py
  synapse/tests/test_cryotank.py
  synapse/tests/test_tools_cryo_cat.py
  synapse/tools/cryo/cat.py
Labels: enhancement

#686 Autodoc configable
  docs/Makefile
  docs/contributing.rst
  docs/synapse/devopsguides/cortex_storage_details.rst
  docs/synapse/devopsguides/cortex_storage_types.rst
  docs/synapse/devopsguides/deployment.rst
  docs/synapse/userguides/ug012_storm_ref_datamod.rst
  docs/synapse/userguides/ug013_storm_ref_lift.rst
  docs/synapse/userguides/ug014_storm_ref_filter.rst
  docs/synapse/userguides/ug015_storm_ref_pivot.rst
  docs/synapse/userguides/ug017_storm_ref_stats.rst
  docs/synapse/userguides/ug018_storm_ref_misc.rst
  synapse/models/biology.py
  synapse/models/chemistry.py
  synapse/models/crypto.py
  synapse/models/dns.py
  synapse/models/files.py
  synapse/models/finance.py
  synapse/models/geopol.py
  synapse/models/geospace.py
  synapse/models/gov/cn.py
  synapse/models/gov/intl.py
  synapse/models/gov/us.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/language.py
  synapse/models/material.py
  synapse/models/media.py
  synapse/models/mime.py
  synapse/models/money.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/models/science.py
  synapse/models/syn.py
  synapse/models/telco.py
  synapse/models/temporal.py
  synapse/neuron.py
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: enhancement

#689 quick update for crypto sequences to use itertools.count() for perf
  synapse/neuron.py
  synapse/tests/test_neuron.py
Labels: enhancement

#690 Defvals will now smash over the same configuration options whenever a…
  synapse/lib/config.py
Labels: bug

#683 Implement Generic `ps:person:has` and `ps:persona:has`
  synapse/lib/storm.py
  synapse/lib/types.py
  synapse/models/person.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_model_person.py
Labels: enhancement

#685 Implement Generic `ou:org:has`
  synapse/lib/iq.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_model_orgs.py
Labels: enhancement

#667 storm support for sub-query based filtration
  synapse/lib/storm.py
  synapse/lib/syntax.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_syntax.py
Labels: enhancement

#694 Update cryouser to be cryoclient.
  synapse/cryotank.py
  synapse/tests/test_cryotank.py
  synapse/tests/test_tools_cryo_cat.py
  synapse/tools/cryo/cat.py
Labels: enhancement

#693 Move CryptSeq from neuron.py to tinfoil.py
  synapse/lib/crypto/tinfoil.py
  synapse/neuron.py
  synapse/tests/test_lib_crypto_tinfoil.py
Labels: enhancement

#692 neuron cli tool for provisioning cells
  synapse/neuron.py
  synapse/tests/test_neuron.py
  synapse/tools/neuron.py
Labels: enhancement

#696 added possible fix for blob metrics race
  synapse/axon.py
Labels: bug

#681 Plumb CellPool into Cortex
  synapse/axon.py
  synapse/cores/common.py
  synapse/lib/cell.py
  synapse/lib/iq.py
  synapse/tests/test_cortex.py
Labels: enhancement

#691 initial HTTP model elements
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#701 Axon double save
  CHANGELOG.md
  synapse/tests/test_axon.py
Labels: documentation

#703 Axon tests
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: bug

#704 Plumb cell:conf auth as a base64 encoded msgpacked blob.
  synapse/cores/common.py
  synapse/lib/iq.py
  synapse/tests/test_cortex.py
Labels: bug

#698 source/seen nodes and ou:meet/ou:conference nodes
  synapse/__init__.py
  synapse/lib/types.py
  synapse/models/base.py
  synapse/models/orgs.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_base.py
  synapse/tests/test_model_orgs.py
Labels: enhancement

#705 Fixes bug in Configable ctor
  synapse/lib/config.py
  synapse/tests/test_lib_config.py
Labels: bug

#708 Add cryocell docs to autodoc
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: documentation

#707 Remove xxsocks, use == -1 for fileno checking
  synapse/lib/socket.py
Labels: bug

#710 neuron/cell leaks
  synapse/tests/test_neuron.py
Labels: bug
