Repository vertexproject/synapse, pull requests merged in 2019-10, with the labels that each got.

#1389 Make the Telepath proxy poolsize configurable
  synapse/telepath.py
  synapse/tests/test_telepath.py
Labels: enhancement

#1361 indexed multi-value properties
  synapse/datamodel.py
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/lmdblayer.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/lib/types.py
  synapse/models/geospace.py
  synapse/tests/test_cortex.py
  synapse/tests/test_datamodel.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_snap.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_syn.py
  synapse/tests/utils.py
Labels: enhancement

#1394 Feature setpasswd
  .circleci/config.yml
  docs/synapse/httpapi.ipynb
  synapse/lib/cell.py
  synapse/lib/hive.py
  synapse/lib/httpapi.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_hive.py
  synapse/tests/test_lib_httpapi.py
Labels: bug, documentation, enhancement

#1390 Add optional role rules to cellauth list display
  synapse/tests/test_tools_cellauth.py
  synapse/tools/cellauth.py
Labels: enhancement

#1395 Bug model dnsname norm
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: bug

#1393 initial skeleton model for crypto currency
  synapse/models/crypto.py
  synapse/models/economic.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_economic.py
Labels: enhancement

#1399 added parent to geo:place
  synapse/models/geospace.py
  synapse/tests/test_model_geospace.py
Labels: enhancement

#1391 Feature tornado update
  requirements.txt
  setup.py
Labels: enhancement

#1396 add lib.vars to storm
  synapse/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1404 Bug daemon coro
  synapse/daemon.py
  synapse/tests/test_telepath.py
Labels: bug

#1405 Allow variables in deref
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
Labels: enhancement

#1406 BUG: fix for trig doc persisting and new name field
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/trigger.py
  synapse/models/syn.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_trigger.py
Labels: enhancement

#1408 Add lib.feed stormtype for assisting with data ingest.
  synapse/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1402 Make cortex, view, and layer idens to be unique
  synapse/cortex.py
  synapse/cryotank.py
  synapse/exc.py
  synapse/lib/cell.py
  synapse/lib/hive.py
  synapse/lib/layer.py
  synapse/lib/lmdblayer.py
  synapse/lib/lmdbslab.py
  synapse/lib/remotelayer.py
  synapse/lib/slaboffs.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_hive.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_remotelayer.py
  synapse/tests/test_lib_slaboffs.py
  synapse/tests/test_tools_backup.py
Labels: enhancement

#1409 yield nodes from values into the pipeline
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/tests/test_lib_storm.py
Labels: enhancement

#1411 lib.feed stormtype updates
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1413 Allow empty values which are not set on a node through lib.csv.emit()
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_tools_csvtool.py
Labels: bug

#1410 Allow cellauth to behave properly with pre-authgate cells.
  synapse/tools/cellauth.py
Labels: bug

#1414 fix for view iden migration bug
  synapse/cortex.py
  synapse/lib/storm.lark
  synapse/tests/test_cortex.py
Labels: bug
