Repository vertexproject/synapse, pull requests merged in 2019-07, with the labels that each got.

#1295 Feature - cron information in tasks
  synapse/lib/agenda.py
  synapse/tests/test_lib_agenda.py
Labels: enhancement

#1306 Fix csvtool help export description
  synapse/tools/csvtool.py
Labels: bug

#1304 Fix several uses of s_common.genfile
  CHANGELOG.rst
  synapse/cmds/cortex.py
  synapse/common.py
  synapse/lib/certdir.py
  synapse/models/infotech.py
  synapse/tools/csvtool.py
Labels: bug

#1308 Docs hive api
  synapse/lib/hive.py
  synapse/tests/test_model_person.py
Labels: documentation

#1292 Allow inet:fqdn filtering to start with a * wildcard.
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#1302 Thesilence docs
  docs/synapse/userguide.rst
  docs/synapse/userguides/storm_adv_libraries.ipynb
  docs/synapse/userguides/storm_adv_methods.ipynb
  docs/synapse/userguides/storm_adv_vars.ipynb
  docs/synapse/userguides/storm_ref_intro.ipynb
  docs/synapse/userguides/storm_ref_type_specific.ipynb
  docs/synapse/userguides/syn_tools_cmdr.ipynb
Labels: documentation

#1309 Add a default share name for the axon.
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: bug

#1311 Fix tool name references
  synapse/tools/feed.py
  synapse/tools/pullfile.py
Labels: bug, documentation

#1291 initial gzip/bzip/json support for Bytes primitive in storm
  synapse/lib/stormhttp.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormhttp.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1307 Implement yield keyword, make loop yielding consistent
  CHANGELOG.rst
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
Labels: enhancement

#1303 Implement editparens
  CHANGELOG.rst
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/tests/test_lib_ast.py
Labels: enhancement

#1313 Push univ=1 value onto form specific universal properties
  synapse/models/syn.py
  synapse/tests/test_model_syn.py
Labels: bug

#1310 In cmdr, emit the time the query execution started on the server
  synapse/cmds/cortex.py
Labels: enhancement

#1305 Allow relative and universal properties to be specified from a variable
  CHANGELOG.rst
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
Labels: enhancement

#1314 Fix test for $gzip()
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#1316 Thesilence moardocs
  CHANGELOG.rst
  docs/synapse/userguides/storm_ref_data_mod.ipynb
  docs/synapse/userguides/storm_ref_type_specific.ipynb
  docs/synapse/userguides/syn_tools_csvtool.ipynb
Labels: documentation

#1319 Bug cellauth delrule
  CHANGELOG.rst
  synapse/lib/cell.py
  synapse/lib/hive.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_tools_cellauth.py
  synapse/tools/cellauth.py
Labels: bug

#1321 circleci codecov update
  .circleci/config.yml
Labels: enhancement

#1320 Allow underscores in org:alias values.
  synapse/models/orgs.py
  synapse/tests/test_model_orgs.py
Labels: enhancement

#1322 Allow variables in tag segments after the first
  CHANGELOG.rst
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/lib/types.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
Labels: enhancement

#1324 Bug httpapi sess
  synapse/lib/httpapi.py
  synapse/tests/test_lib_httpapi.py
Labels: bug

#1325 circelci seatbelts
  .circleci/config.yml
Labels: bug

#1323 Storm Tee command
  CHANGELOG.rst
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#1326 Fixes quickstart documentation error
  docs/synapse/quickstart.rst
Labels: bug, documentation
