Repository vertexproject/synapse, pull requests merged in 2019-09, with the labels that each got.

#1357 circleci config update
  .circleci/config.yml
Labels: enhancement

#1360 added inet:url:mirror form
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#1359 Bug storm max ival
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#1350 runtime model extensions, prop lift via var deref, tag-properties, oh my
  synapse/cortex.py
  synapse/datamodel.py
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/hive.py
  synapse/lib/layer.py
  synapse/lib/lmdblayer.py
  synapse/lib/node.py
  synapse/lib/remotelayer.py
  synapse/lib/snap.py
  synapse/lib/storm.lark
  synapse/lib/storm.py
  synapse/lib/storm_format.py
  synapse/tests/test_cortex.py
  synapse/tests/test_datamodel.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_hive.py
  synapse/tests/test_lib_lmdblayer.py
  synapse/tests/test_lib_node.py
Labels: enhancement

#1358 Storm HTTP Post and Base64 lib
  synapse/cortex.py
  synapse/lib/stormhttp.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormhttp.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1362 Make geo:dist inherit IntBase type
  synapse/models/geospace.py
  synapse/tests/test_model_geospace.py
Labels: bug

#1344 Feature healthcheck
  synapse/axon.py
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/health.py
  synapse/lib/httpapi.py
  synapse/tests/docker-compose.yml
  synapse/tests/test_axon.py
  synapse/tests/test_lib_health.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_tools_healthcheck.py
  synapse/tests/utils.py
  synapse/tools/healthcheck.py
Labels: enhancement

#1363 Bug daemon share
  synapse/daemon.py
  synapse/tests/test_telepath.py
Labels: bug

#1367 Move agenda.start() call AFTER coremodules have finished loading
  synapse/cortex.py
Labels: bug

#1366 Restore quoted string parsing in storm
  synapse/lib/grammar.py
  synapse/tests/test_lib_grammar.py
Labels: bug

#1365 Feature link coverage
  synapse/tests/test_lib_link.py
Labels: enhancement

#1372 Add extramodel props and tagprop awareness to runt nodes
  synapse/cortex.py
  synapse/models/syn.py
  synapse/tests/test_model_syn.py
Labels: enhancement

#1373 Feature tagprop reprs
  synapse/cmds/cortex.py
  synapse/datamodel.py
  synapse/lib/node.py
  synapse/tests/test_cmds_cortex.py
  synapse/tests/test_lib_node.py
Labels: enhancement

#1368 Scrape cmd
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#1371 Add explicit permissions for manipulating triggers and cron
  synapse/cmds/boss.py
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/tests/test_cmds_boss.py
  synapse/tests/test_cmds_cron.py
  synapse/tests/test_cmds_trigger.py
Labels: enhancement

#1352 storm service architecture
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/coro.py
  synapse/lib/grammar.py
  synapse/lib/link.py
  synapse/lib/lmdbslab.py
  synapse/lib/msgpack.py
  synapse/lib/storm.lark
  synapse/lib/storm.py
  synapse/lib/stormsvc.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/models/syn.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_link.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_msgpack.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_telepath.py
Labels: enhancement

#1378 Add .time.format() to allow formatting a Synapse timestamp into a string
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1348 Plumb view argument through cortex API
  synapse/cortex.py
  synapse/datamodel.py
  synapse/exc.py
  synapse/lib/coro.py
  synapse/lib/editatom.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/trigger.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_remotelayer.py
  synapse/tests/test_lib_trigger.py
  synapse/tests/test_lib_view.py
  synapse/tests/test_model_syn.py
Labels: enhancement

#1382 Refactor/move/add arch doc
  docs/synapse/devguide.rst
  docs/synapse/devguides/architecture.rst
  docs/synapse/devguides/cortex_quickstart.ipynb
Labels: documentation

#1364 Feature current telepath users
  synapse/daemon.py
  synapse/lib/cell.py
  synapse/lib/link.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_telepath.py
Labels: enhancement

#1385 Bug perms
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/tests/test_cmds_boss.py
  synapse/tests/test_cmds_cron.py
  synapse/tests/test_cmds_trigger.py
Labels: bug

#1386 Doc arch tweaks
  docs/synapse/devguides/architecture.rst
Labels: documentation

#1388 Bug test assets
  synapse/tests/files/cellauth/cells/echo00/boot.yaml
  synapse/tests/files/cellauth/dmon.yaml
  synapse/tests/files/test.dat
  synapse/tests/nest1.tar
  synapse/tests/nest2.tar
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_datfile.py
Labels: bug
