Repository vertexproject/synapse, pull requests merged in 2019-02, with the labels that each got.

#1076 010-bug-univdel
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: bug

#1078 Cull dead syntax.py code so we have less syntax.py code to maintain.
  synapse/lib/jupyter.py
  synapse/lib/syntax.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/tests/test_lib_syntax.py
Labels: enhancement

#1077 010 reindex fire
  synapse/lib/editatom.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: bug, enhancement

#1089 Remove last 00x model
  synapse/models/telco.py
Labels: enhancement

#1088 Requirements.txt updates, msgpack 0.6.1 bump
  requirements.txt
  requirements_dev.txt
  requirements_doc.txt
  setup.py
  synapse/lib/msgpack.py
  synapse/tests/test_lib_msgpack.py
Labels: enhancement

#1093 fix for index truncation bug
  synapse/datamodel.py
  synapse/lib/lmdblayer.py
  synapse/lib/types.py
  synapse/models/files.py
  synapse/models/inet.py
  synapse/tests/test_datamodel.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: bug

#1106 Catch and log 'path too long' errors when starting a unix socket server that is too long.
  synapse/daemon.py
  synapse/tests/test_daemon.py
Labels: enhancement

#1107 Allow synapse to travel at 88mph
  synapse/common.py
Labels: enhancement
