Repository vertexproject/synapse, pull requests merged in 2019-12, with the labels that each got.

#1444 Add multi-value ou:org:names prop to ou:org
  synapse/models/orgs.py
  synapse/tests/test_model_orgs.py
Labels: enhancement

#1443 Bug cryotank delete
  synapse/cryotank.py
  synapse/tests/test_cryotank.py
  synapse/tests/utils.py
Labels: bug

#1445 Make StormType nosuchname errors more friendly.
  synapse/lib/stormtypes.py
Labels: bug

#1442 Bug storm ingest safety
  synapse/cryotank.py
  synapse/lib/snap.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#1449 small wordsmithing
  docs/synapse/intro.rst
Labels: documentation

#1451 Feature synnodes stability
  synapse/lib/snap.py
  synapse/tests/test_cortex.py
Labels: enhancement

#1447 Better error message for geo:dist parse errors
  synapse/models/geospace.py
  synapse/tests/test_model_geospace.py
Labels: enhancement

#1452 Fix: Users using another user's queue
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#1453 Allow refs=True in graph rules to facilitate "refs out" behavior
  synapse/lib/ast.py
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
Labels: bug

#1454 Fix bug where removal of tag prop wouldn't update Node
  synapse/lib/node.py
  synapse/tests/test_cortex.py
Labels: bug

#1462 Bump circleci cache for linux ci builds
  .circleci/config.yml
Labels: bug

#1463 Fix broken doc link
  docs/synapse/devguides/cortex_quickstart.ipynb
Labels: bug, documentation

#1459 Allow expressions to deal with None values
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
Labels: enhancement

#1458 Prevent downgrading to before layer reidening
  CHANGELOG.rst
  synapse/cortex.py
  synapse/lib/modelrev.py
Labels: bug

#1468 Eager CI upgrades.
  .circleci/config.yml
Labels: enhancement

#1456 Exec storm from storm
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1470 Bug runt synformpivot
  synapse/lib/ast.py
  synapse/tests/test_model_syn.py
Labels: bug

#1466 Make tee runtsafe
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#1446 Add storm service command runt nodes
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/models/syn.py
  synapse/tests/test_model_syn.py
Labels: enhancement

#1471 Bug: PropPivotOut array support
  synapse/lib/ast.py
  synapse/tests/test_model_syn.py
Labels: bug

#1472 Add some asyncio.sleep calls into the AST
  synapse/lib/ast.py
Labels: bug

#1464 Feature user list
  synapse/lib/cell.py
  synapse/lib/hive.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#1469 Feature stormtypes strbytes
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement
