Repository vertexproject/synapse, pull requests merged in 2019-11, with the labels that each got.

#1418 add storm stats lib with tally and storm init/fini blocks
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1421 Protect addFeedNodes from a ctor which doesn't make an async generator.
  synapse/lib/snap.py
  synapse/tests/test_lib_snap.py
Labels: bug

#1422 Fix an ambiguity in the switchcase grammar
  synapse/lib/storm.lark
  synapse/tests/test_lib_grammar.py
Labels: bug

#1423 Migrate stored trigger view to new scheme
  synapse/cortex.py
  synapse/lib/trigger.py
  synapse/tests/test_lib_trigger.py
Labels: bug

#1417 Add service.add and service.del hooks to storm service
  synapse/cortex.py
  synapse/lib/stormsvc.py
  synapse/tests/test_lib_stormsvc.py
Labels: enhancement

#1426 Bug cryotank anit
  synapse/cryotank.py
Labels: bug

#1427 Feature cryocell flexibility
  synapse/cryotank.py
  synapse/tests/test_cryotank.py
  synapse/tests/utils.py
Labels: enhancement

#1420 clean up old stormsvc commands
  synapse/cortex.py
  synapse/lib/stormsvc.py
  synapse/tests/test_lib_stormsvc.py
Labels: bug

#1419 Storm updates for functions and packages and some utilities
  synapse/common.py
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/grammar.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.lark
  synapse/lib/storm.py
  synapse/lib/storm_format.py
  synapse/lib/stormsvc.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormhttp.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1430 Dressing for visi-storm-funcs
  synapse/cortex.py
  synapse/lib/node.py
  synapse/lib/stormsvc.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_node.py
  synapse/tests/test_lib_stormsvc.py
Labels: bug, enhancement

#1432 Feature error logging
  synapse/lib/provenance.py
  synapse/lib/view.py
  synapse/tests/test_lib_provenance.py
Labels: enhancement

#1434 Feature stormtypes updates
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1435 StormDmon promotion bug
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
Labels: bug

#1431 Allow storm functions to call each other.
  synapse/lib/ast.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_ast.py
Labels: bug

#1437 add loc property to mat:item, it:host, and geo:nloc
  synapse/models/geospace.py
  synapse/models/infotech.py
  synapse/models/material.py
  synapse/tests/test_model_geospace.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_material.py
Labels: enhancement

#1438 Fix case ambiguity
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
Labels: bug

#1436 Initial task pair splitting for dmon restartability
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
Labels: enhancement
