Repository vertexproject/synapse, pull requests merged in 2020-11, with the labels that each got.

#1938 Feature ipv4 cmpr
  synapse/lib/types.py
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#1939 Correct telepath client object behavior
  synapse/telepath.py
  synapse/tests/test_telepath.py
Labels: bug

#1941 Fix reset test.
  synapse/telepath.py
  synapse/tests/test_telepath.py
Labels: bug

#1956 Support fallback python 37 images
  .circleci/config.yml
  docker-compose.yml
  docker/images/synapse/Dockerfile
  docker/images/synapse/Dockerfile-py37
Labels: enhancement

#1957 Bug background capture
  synapse/lib/storm.py
Labels: bug

#1950 implement env var based node and file limits on cortex and axon
  synapse/axon.py
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/cell.py
  synapse/lib/config.py
  synapse/lib/layer.py
  synapse/lib/snap.py
  synapse/tests/test_axon.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_config.py
  synapse/tests/utils.py
Labels: enhancement

#1960 Refactor pypi release procss to avoid doing the prep twice
  .circleci/config.yml
Labels: bug

#1961 Populate oldv for nodedata set edits
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
Labels: bug

#1963 Add --now option to cron.at
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, enhancement

#1955 Added :client:host / :server:host to inet:http:request and :host / :acct to inet:search:query
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#1974 onload storm commands should be executed in their own schedcoro
  synapse/cortex.py
  synapse/tests/test_lib_storm.py
Labels: bug
