Repository vertexproject/synapse, pull requests merged in 2020-07, with the labels that each got.

#1786 Fix help error for macro.del
  synapse/lib/stormlib/macro.py
Labels: bug

#1787 Fix rule indexing for print and delete
  synapse/tests/test_tools_cellauth.py
  synapse/tools/cellauth.py
Labels: bug

#1789 Bug model edge language
  synapse/lib/storm.py
  synapse/lib/stormlib/model.py
  synapse/tests/test_lib_stormlib_model.py
Labels: bug

#1784 Thesilence docs
  CHANGELOG.rst
  docs/synapse/glossary.rst
  docs/synapse/userguides/bkd_graphs_hypergraphs.ipynb
  docs/synapse/userguides/bkd_why_synapse.ipynb
  docs/synapse/userguides/data_model_form_categories.ipynb
  docs/synapse/userguides/storm_adv_vars.ipynb
  docs/synapse/userguides/storm_ref_automation.ipynb
  docs/synapse/userguides/storm_ref_cmd.ipynb
  docs/synapse/userguides/storm_ref_data_mod.ipynb
  docs/synapse/userguides/storm_ref_pivot.ipynb
Labels: documentation

#1782 Add ps and kill to storm
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/task.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1794 fix for prop pivot out with array source
  synapse/lib/ast.py
  synapse/lib/types.py
  synapse/tests/test_lib_ast.py
Labels: bug

#1795 storm autoadd mode
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/tests/test_lib_ast.py
Labels: enhancement

#1798 better validation of auth api inputs
  synapse/lib/hiveauth.py
  synapse/tests/test_lib_hiveauth.py
Labels: bug

#1800 headers array fields for email message and http requests
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#1802 Infotech reveng model additions
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#1803 Update scrape docs for --refs
  docs/synapse/userguides/storm_ref_cmd.ipynb
Labels: documentation

#1785 refactor nexus to remove leadership
  synapse/cortex.py
  synapse/daemon.py
  synapse/exc.py
  synapse/lib/agenda.py
  synapse/lib/cell.py
  synapse/lib/certdir.py
  synapse/lib/config.py
  synapse/lib/hive.py
  synapse/lib/hiveauth.py
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/lib/nexus.py
  synapse/lib/slabseqn.py
  synapse/lib/spawn.py
  synapse/lib/storm.py
  synapse/lib/stormsvc.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_certdir.py
  synapse/tests/test_lib_hiveauth.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_nexus.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_view.py
  synapse/tests/test_servers_cortex.py
  synapse/tests/test_telepath.py
  synapse/tests/test_tools_migrate200.py
  synapse/tests/utils.py
  synapse/tools/migrate_200.py
Labels: enhancement

#1805 added --no-edges to graph command and :doc:url to syn:tag
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/storm.py
  synapse/models/syn.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_model_syn.py
Labels: enhancement

#1811 docs for docker deployments and mirrors
  docs/synapse/devguides/devops_cortex.rst
Labels: documentation

#1806 Feature reqvalidstorm
  synapse/cortex.py
  synapse/lib/httpapi.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement

#1804 Feature autodoc stormtypes
  docs/conf.py
  docs/index.rst
  docs/synapse/stormtypes.rst
  synapse/cortex.py
  synapse/lib/stormhttp.py
  synapse/lib/stormlib/macro.py
  synapse/lib/stormlib/model.py
  synapse/lib/stormtypes.py
  synapse/lib/stormwhois.py
  synapse/telepath.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: documentation

#1815 Fix docker build, add smoketests
  .circleci/config.yml
  docker/bootstrap.sh
  docker/images/axon/Dockerfile
  docker/images/cortex/Dockerfile
  docker/images/cryotank/Dockerfile
Labels: bug, enhancement

#1818 Fix autodoc form examples
  synapse/models/crypto.py
  synapse/models/dns.py
  synapse/models/economic.py
  synapse/models/files.py
  synapse/models/geopol.py
  synapse/models/geospace.py
  synapse/models/gov/cn.py
  synapse/models/gov/intl.py
  synapse/models/gov/us.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/material.py
  synapse/models/media.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/models/risk.py
  synapse/models/syn.py
  synapse/models/telco.py
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: bug, documentation

#1797 Thesilence docs
  docs/synapse/glossary.rst
  docs/synapse/userguides/bkd_why_synapse.ipynb
  docs/synapse/userguides/data_model_form_categories.ipynb
  docs/synapse/userguides/index_storm_adv.rst
  docs/synapse/userguides/index_storm_ref.rst
  docs/synapse/userguides/storm_adv_subquery.ipynb
  docs/synapse/userguides/storm_ref_automation.ipynb
  docs/synapse/userguides/storm_ref_cmd.ipynb
  docs/synapse/userguides/storm_ref_data_mod.ipynb
  docs/synapse/userguides/storm_ref_filter.ipynb
  docs/synapse/userguides/storm_ref_intro.ipynb
  docs/synapse/userguides/storm_ref_pivot.ipynb
  docs/synapse/userguides/storm_ref_subquery.ipynb
  docs/synapse/userguides/storm_ref_type_specific.ipynb
  docs/synapse/userguides/syn_ref_cmdr.ipynb
  docs/synapse/userguides/syn_tools_csvtool.ipynb
Labels: documentation

#1822 Axon HTTPAPI tweaks
  docs/synapse/devguides/devops_axon.rst
  docs/synapse/devguides/devops_cortex.rst
  docs/synapse/httpapi.ipynb
  synapse/axon.py
  synapse/lib/stormtypes.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_stormtypes.py
Labels: documentation, enhancement

#1824 Fix issue with dyncalls against remote axons
  synapse/cortex.py
  synapse/tests/test_cortex.py
Labels: bug

#1823 Document list of permissions
  docs/synapse/devguides/cell_permissions.rst
  docs/synapse/devguides/devops_cell.rst
  docs/synapse/devops.rst
  synapse/lib/cell.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_ast.py
Labels: documentation

#1821 added author field to yara rules
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#1826 added option to map nexslog async
  synapse/lib/cell.py
  synapse/lib/nexus.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#1827 added deref to list based on numeric index
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1828 added .inet.http.request() for generic http requests
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#1813 added prop/tag count APIs to the layers in stormtypes
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement
