Repository vertexproject/synapse, pull requests merged in 2020-08, with the labels that each got.

#1831 Fix doc string typos
  synapse/models/dns.py
  synapse/models/infotech.py
  synapse/models/orgs.py
Labels: bug, documentation

#1834 Fix inet:ipv4range doc typo
  synapse/models/inet.py
Labels: documentation

#1845 gracefully yield on implicit filter within pivots
  synapse/lib/ast.py
  synapse/tests/test_lib_ast.py
Labels: bug

#1851 Runt pivotout support and docstrings
  synapse/lib/ast.py
  synapse/lib/hiveauth.py
  synapse/lib/stormlib/backup.py
  synapse/tests/test_model_syn.py
Labels: bug, documentation

#1852 Add :nicks and :names to ps:person and ps:persona
  synapse/models/person.py
  synapse/tests/test_model_person.py
Labels: documentation

#1853 Add a step to smoke test the sdist and wheel packages
  .circleci/config.yml
Labels: enhancement

#1850 Add nodedata prop to syn:cmd
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/models/syn.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_model_syn.py
  synapse/tests/test_tools_autodoc.py
  synapse/tests/utils.py
  synapse/tools/autodoc.py
Labels: enhancement

#1855 Add module conf data to storm service definitions
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormsvc.py
Labels: enhancement

#1862 Correct Axon documentation
  docs/synapse/devguides/devops_cortex.rst
Labels: bug, documentation

#1865 Refactor test_axon.py
  synapse/tests/test_axon.py
Labels: enhancement
