Repository vertexproject/synapse, pull requests merged in 2020-10, with the labels that each got.

#1892 initial display hinting for props
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/language.py
  synapse/models/media.py
  synapse/models/orgs.py
  synapse/models/risk.py
  synapse/models/syn.py
  synapse/models/telco.py
Labels: enhancement

#1903 Add getFormCounts() apis to the view and layer objects in storm.
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1905 If any of the destination forms are not actually forms, then go raise…
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: bug

#1910 Allow layers to report their total size on disk
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1906 Feature storm if regex
  synapse/lib/ast.py
  synapse/lib/storm.lark
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1904 Reigndocs
  docs/synapse/userguides/storm_ref_lift.ipynb
  synapse/lib/jupyter.py
  synapse/tests/test_lib_jupyter.py
Labels: documentation

#1915 Fix bug in spawncore with stormservices
  synapse/lib/spawn.py
  synapse/tests/test_lib_spawn.py
Labels: bug

#1914 Resolve issue where a spawn process' slab fails
  synapse/lib/lmdbslab.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_spawn.py
Labels: bug

#1916 Proper runtsafe scope for commands and detect undeclared vars
  synapse/lib/ast.py
  synapse/lib/node.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_jupyter.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_orgs.py
Labels: bug

#1918 Promote addFeedData calls to Syntasks
  synapse/cortex.py
  synapse/lib/snap.py
Labels: enhancement

#1913 290 prep
  CHANGELOG.rst
  docs/synapse/devguides/devops_cortex.rst
Labels: documentation

#1924 Fix telepath onlink exceptions bug
  synapse/telepath.py
  synapse/tests/test_telepath.py
Labels: bug

#1919 time repr - Reuse epoch object instead if making a new object.
  synapse/lib/time.py
Labels: enhancement

#1920 Update circleci config and remove loop arguments
  .circleci/config.yml
  synapse/lib/base.py
  synapse/lib/view.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_layer.py
  synapse/tests/utils.py
Labels: enhancement

#1926 Include node iden in Node.delete() errors
  synapse/lib/node.py
Labels: enhancement

#1912 Take advantage of LMDB append optimization
  synapse/lib/lmdbslab.py
  synapse/lib/slabseqn.py
  synapse/tests/test_lib_lmdbslab.py
Labels: enhancement

#1923 Update storm cmdargs 'type' value to allow any model type name
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1921 Py38 feature prep
  .circleci/config.yml
  Dockerfile
  docker-compose.yml
  docker/images/axon/Dockerfile
  docker/images/cortex/Dockerfile
  docker/images/cryotank/Dockerfile
  requirements.txt
  requirements_dev.txt
  setup.py
Labels: enhancement

#1909 tools for locking / checking deprecated model elements
  synapse/cortex.py
  synapse/datamodel.py
  synapse/exc.py
  synapse/lib/hive.py
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/lib/snap.py
  synapse/lib/stormlib/model.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/tests/test_datamodel.py
  synapse/tests/test_lib_stormlib_model.py
Labels: enhancement
