Repository vertexproject/synapse, pull requests merged in 2020-06, with the labels that each got.

#1748 Migrate view owner to creator
  synapse/tests/test_tools_migrate020.py
  synapse/tools/migrate_020.py
Labels: bug

#1751 Tweak circle config for 2.x.x release line
  .circleci/config.yml
Labels: enhancement

#1752 Fix a bunch of documentation related items referring to 020
  CHANGELOG.rst
  docs/synapse/devops.rst
  docs/synapse/intro.rst
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_tools_migrate200.py
  synapse/tests/test_tools_sync200.py
  synapse/tools/migrate_200.py
  synapse/tools/sync_200.py
Labels: documentation

#1716 implement macros
  CHANGELOG.rst
  docs/synapse/userguides/storm_adv_methods.ipynb
  docs/synapse/userguides/storm_ref_filter.ipynb
  docs/synapse/userguides/storm_ref_lift.ipynb
  docs/synapse/userguides/storm_ref_type_specific.ipynb
  synapse/common.py
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/cell.py
  synapse/lib/layer.py
  synapse/lib/parser.py
  synapse/lib/spawn.py
  synapse/lib/storm.lark
  synapse/lib/storm.py
  synapse/lib/storm_format.py
  synapse/lib/stormlib/macro.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_spawn.py
  synapse/tests/test_lib_stormlib_macro.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_geospace.py
  synapse/tests/utils.py
Labels: enhancement

#1761 Fix macro.set example error.
  synapse/lib/stormlib/macro.py
Labels: bug

#1763 Docs update
  CHANGELOG.rst
  docs/index.rst
  docs/synapse/200_changes.rst
  docs/synapse/devops.rst
  docs/synapse/intro.rst
  synapse/cortex.py
  synapse/daemon.py
  synapse/lib/ast.py
  synapse/lib/coro.py
  synapse/lib/hiveauth.py
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/telepath.py
  synapse/tools/migrate_200.py
Labels: documentation

#1767 Documentation updates
  .circleci/config.yml
  CHANGELOG.rst
  docs/_static/css/theme_overrides.css
  docs/_static/favicon.svg
  docs/_static/logo.svg
  docs/_static/theme_overrides.css
  docs/_templates/breadcrumbs.html
  docs/conf.py
  docs/index.rst
Labels: documentation

#1771 Update storm service docs
  docs/conf.py
  docs/synapse/devguides/devops_cell.rst
  docs/synapse/devguides/stormservices.rst
  docs/synapse/devops.rst
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: documentation

#1773 Docs stormsvc cmds
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: documentation

#1772 Autodoc confdefs
  docs/conf.py
  docs/synapse/devguides/backups.rst
  docs/synapse/devguides/devops_axon.rst
  docs/synapse/devguides/devops_cell.rst
  docs/synapse/devguides/devops_cortex.rst
  docs/synapse/devguides/devops_cryotank.rst
  docs/synapse/devguides/devops_general.rst
  docs/synapse/devguides/stormservices.rst
  docs/synapse/devops.rst
  synapse/cortex.py
  synapse/lib/config.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: documentation

#1774 Docs updated quickstart
  CHANGELOG.rst
  README.rst
  docs/synapse/devguides/devops_general.rst
  docs/synapse/quickstart.rst
Labels: documentation

#1769 Disallow command parameters and bare string constants from starting with //
  synapse/lib/storm.lark
  synapse/tests/test_lib_grammar.py
Labels: bug

#1776 Add template to Storm service docs
  docs/synapse/devguides/stormservices.ipynb
  docs/synapse/devguides/stormservices.rst
  synapse/lib/jupyter.py
  synapse/tests/test_lib_jupyter.py
Labels: documentation

#1777 Reorganize the userguide toctree
  docs/synapse/devguides/backups.rst
  docs/synapse/userguide.rst
  docs/synapse/userguides/index_analytical.rst
  docs/synapse/userguides/index_bkd.rst
  docs/synapse/userguides/index_datamodel.rst
  docs/synapse/userguides/index_design.rst
  docs/synapse/userguides/index_storm_adv.rst
  docs/synapse/userguides/index_storm_ref.rst
  docs/synapse/userguides/index_tools.rst
Labels: documentation

#1779 Update user setup doc permission names
  docs/synapse/quickstart.rst
Labels: bug, documentation

#1768 Fix sequencing bug between leadership setting and service initialization
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/base.py
  synapse/lib/cell.py
  synapse/lib/hiveauth.py
  synapse/lib/layer.py
  synapse/lib/msgpack.py
  synapse/lib/nexus.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_base.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_msgpack.py
  synapse/tests/test_lib_nexus.py
  synapse/tests/test_lib_slabseqn.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_tools_migrate200.py
  synapse/tools/migrate_200.py
Labels: bug

#1780 Docs glossary
  docs/synapse/glossary.rst
Labels: documentation

#1781 Devops guide documentation updates
  Dockerfile
  docs/synapse/devguides/devops_axon.rst
  docs/synapse/devguides/devops_cell.rst
  docs/synapse/devguides/devops_cortex.rst
  docs/synapse/devguides/devops_cryotank.rst
  docs/synapse/devguides/index_autoconf.rst
  docs/synapse/devguides/index_cells.rst
  docs/synapse/devops.rst
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: documentation

#1783 Add nonexistent file to axon.get test
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: bug
