Repository vertexproject/synapse, pull requests merged in 2020-05, with the labels that each got.

#1708 Use the registered cellapi as opposed to hardcoding CoreApi
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_layer.py
Labels: bug

#1710 Fix var leakage in chained services
  synapse/lib/node.py
  synapse/lib/storm.py
  synapse/tests/test_lib_node.py
  synapse/tests/test_lib_stormsvc.py
Labels: bug

#1713 Additional async methods on the Layer class
  synapse/lib/layer.py
  synapse/lib/view.py
Labels: enhancement

#1715 lift by from+tag, validate the form is a valid form.
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: bug

#1717 Fix test class name.
  synapse/tests/test_model_risk.py
Labels: bug

#1719 Fix a test teardown race condition
  synapse/lib/nexus.py
  synapse/tests/test_servers_cortex.py
Labels: bug

#1714 Test for and fix nested log actions
  synapse/cortex.py
  synapse/lib/hiveauth.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
  synapse/tools/migrate_020.py
Labels: bug

#1718 View.pack() include triggers and plumbed to storm town
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#1720 Feature spawncore conf
  synapse/cortex.py
  synapse/lib/spawn.py
Labels: enhancement

#1721 async layer lift apis so regex can yield
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
Labels: bug

#1723 Fix pycodestyle ambiguity
  synapse/cortex.py
  synapse/lib/modelrev.py
  synapse/lib/view.py
  synapse/tests/test_telepath.py
  synapse/tools/cryo/cat.py
Labels: bug, enhancement

#1722 Allow spawn to work with cortexes that have services
  synapse/cortex.py
  synapse/lib/spawn.py
  synapse/lib/storm.py
  synapse/tests/test_lib_spawn.py
Labels: bug

#1727 Fix a bug where forked views were unable to be loaded by the spawncore
  synapse/lib/spawn.py
  synapse/tests/test_lib_spawn.py
Labels: bug

#1712 Support generating nodeedits when form is not present
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_view.py
  synapse/tests/test_tools_migrate020.py
  synapse/tools/migrate_020.py
Labels: bug

#1732 Return actual trigger iden
  synapse/cmds/trigger.py
  synapse/tests/test_cmds_trigger.py
Labels: bug

#1730 Cell leadership awareness
  .circleci/config.yml
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/base.py
  synapse/lib/cell.py
  synapse/lib/layer.py
  synapse/lib/nexus.py
  synapse/lib/spawn.py
  synapse/lib/storm.py
  synapse/lib/stormsvc.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cmds_cortex.py
  synapse/tests/test_cmds_cron.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_msgpack.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_tools_migrate020.py
  synapse/tests/test_tools_pullfile.py
  synapse/tools/pullfile.py
Labels: enhancement

#1741 Fix prompt toolkit
  setup.py
Labels: bug

#1739 Bump lmdb minver and a few other packages.
  requirements.txt
  setup.py
Labels: enhancement

#1747 Version bump
  setup.py
  synapse/cmds/cortex.py
  synapse/common.py
  synapse/cortex.py
  synapse/lib/version.py
  synapse/tests/test_lib_version.py
  synapse/tests/test_tools_migrate020.py
  synapse/tools/cellauth.py
  synapse/tools/cmdr.py
  synapse/tools/csvtool.py
  synapse/tools/feed.py
  synapse/tools/hive/load.py
  synapse/tools/hive/save.py
  synapse/tools/migrate_020.py
Labels: enhancement
