Repository vertexproject/synapse, pull requests merged in 2020-12, with the labels that each got.

#1976 properly plumb getPathObjs
  synapse/lib/jsonstor.py
  synapse/tests/test_lib_jsonstor.py
Labels: bug

#1972 Fix HasRelPropCond for pivprops
  synapse/lib/ast.py
  synapse/lib/storm.lark
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
Labels: bug

#1975 fix support for array of aha servers in cell config
  synapse/lib/cell.py
  synapse/tests/test_lib_aha.py
Labels: bug

#1977 stop forking a crazy number of kid layers that blows up cluster tests with max file descriptors
  synapse/tests/test_cortex.py
Labels: bug

#1978 split addform nexus
  synapse/cortex.py
Labels: bug

#1981 fix view.add/fork perms and read telepath.yaml in cellauth
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_tools_cellauth.py
  synapse/tools/cellauth.py
Labels: bug

#1984 aha:admin accounts must be unlocked upon startup if they are locked. …
  synapse/lib/cell.py
  synapse/tests/test_lib_aha.py
Labels: bug

#1985 pop path from aha svcurl to honor local path
  synapse/telepath.py
  synapse/tests/test_lib_aha.py
Labels: bug

#1991 Adds efficient view/layer push/pull configurations.
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/hiveauth.py
  synapse/lib/jsonstor.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_jsonstor.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#1982 Add HTTP API for an admin to mint a one-time passwd for a user
  synapse/lib/cell.py
  synapse/lib/hive.py
  synapse/lib/hiveauth.py
  synapse/lib/httpapi.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#1992 Bugfix: replay push/pull add messages
  synapse/cortex.py
Labels: bug

#1995 BUGFIX: Ensure parent FQDN exists even in out-of-order node edit playback
  synapse/models/inet.py
Labels: bug

#2005 Rename lib.regx to lib.regex.
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1998 added lib.dmon.get / lib.dmon.bump and refactored dmon loop
  synapse/cortex.py
  synapse/lib/spawn.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_spawn.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2006 fix for AHA support in pullfile / pushfile
  synapse/telepath.py
  synapse/tests/test_tools_pullfile.py
  synapse/tests/test_tools_pushfile.py
  synapse/tools/pullfile.py
  synapse/tools/pushfile.py
Labels: enhancement

#2007 Thesilence docs
  docs/synapse/userguides/analytical_model_tags.ipynb
  docs/synapse/userguides/analytical_model_tags_analysis.ipynb
  docs/synapse/userguides/bkd_graphs_hypergraphs.ipynb
  docs/synapse/userguides/bkd_why_synapse.ipynb
  docs/synapse/userguides/data_model_form_categories.ipynb
  docs/synapse/userguides/data_model_object_categories.ipynb
  docs/synapse/userguides/data_model_terms.ipynb
  docs/synapse/userguides/design_analytical_model.ipynb
  docs/synapse/userguides/design_data_model.ipynb
  docs/synapse/userguides/design_forms_vs_tags.ipynb
  docs/synapse/userguides/index_analytical.rst
  docs/synapse/userguides/index_datamodel.rst
  docs/synapse/userguides/storm_adv_libs.ipynb
  docs/synapse/userguides/storm_adv_methods.ipynb
  docs/synapse/userguides/storm_adv_vars.ipynb
  docs/synapse/userguides/storm_ref_automation.ipynb
  docs/synapse/userguides/storm_ref_cmd.ipynb
  docs/synapse/userguides/storm_ref_model_introspect.ipynb
  docs/synapse/userguides/storm_ref_pivot.ipynb
  docs/synapse/userguides/storm_ref_type_specific.ipynb
Labels: documentation

#2012 Refactor push/pull test to not reach through the layer API boundary
  synapse/lib/layer.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2013 Feature StormVarListError messages
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: enhancement

#2014 Make Coretex.getFormCount() return a primitive object
  synapse/cortex.py
Labels: bug

#2011 Add node.set() in Stormtypes
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#1615 IT LIVES!: Telepath getPipeline() method for pipelining telepath calls
  synapse/daemon.py
  synapse/telepath.py
  synapse/tests/test_telepath.py
Labels: enhancement

#2032 implement pop() and cull() on multiqueue/slabseqn
  synapse/cortex.py
  synapse/lib/lmdbslab.py
  synapse/lib/slabseqn.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_slabseqn.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, enhancement
