Repository vertexproject/synapse, pull requests merged in 2021-04, with the labels that each got.

#2096 Project model, it:account (et al), duration base type, guid lift by prefix, model tweaks, and storm runtime fixes
  synapse/cortex.py
  synapse/datamodel.py
  synapse/lib/ast.py
  synapse/lib/layer.py
  synapse/lib/modules.py
  synapse/lib/node.py
  synapse/lib/storm.py
  synapse/lib/stormlib/project.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/models/auth.py
  synapse/models/crypto.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/proj.py
  synapse/models/syn.py
  synapse/models/telco.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_proj.py
Labels: bug, enhancement

#2146 Update lark dependency
  requirements.txt
  setup.py
  synapse/lib/parser.py
  synapse/tests/test_lib_grammar.py
Labels: enhancement

#2149 Feature stormsvc version
  synapse/lib/stormsvc.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2153 pin jupyter-client
  requirements_doc.txt
Labels: bug

#2154 Unpack items used in varlistsetoper
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: bug

#2158 Update circle config to use build contexts
  .circleci/config.yml
Labels: enhancement

#2161 Avoid calling applyNodeEdit with no edits for tags
  synapse/lib/node.py
Labels: bug

#2169 Update min lmdb version
  requirements.txt
  setup.py
Labels: enhancement

#2170 allow refang in lookup/autoadd mode
  synapse/lib/ast.py
  synapse/lib/scrape.py
  synapse/tests/test_lib_ast.py
Labels: enhancement
