Repository vertexproject/synapse, pull requests merged in 2021-12, with the labels that each got.

#2459 Fix for SYN-2869 re path scoped vars
  synapse/lib/agenda.py
  synapse/lib/node.py
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2485 Feat genpkg readonly (SYN-2959)
  synapse/common.py
  synapse/lib/cell.py
  synapse/lib/certdir.py
  synapse/lib/platforms/linux.py
  synapse/servers/stemcell.py
  synapse/tests/test_tools_genpkg.py
  synapse/tools/genpkg.py
Labels: enhancement

#2484 Changelog 20211201
  CHANGELOG.rst
  docs/synapse/httpapi.ipynb
  docs/synapse/userguides/syn_tools_feed.rst
  synapse/lib/stormlib/project.py
Labels: enhancement

#2463 Writeback mirroring for layers
  docs/synapse/devguides/devops_cortex.rst
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/layer.py
  synapse/lib/nexus.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_layer.py
Labels: enhancement

#2486 Add $lib.scrape() (SYN-2806)
  synapse/lib/scrape.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2489 BUGFIX upstream sync fired when not configured
  synapse/lib/layer.py
Labels: bug

#2491 Add --raw arg to pkg.load (SYN-2880)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2492 Restore path behavior (SYN-2962)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2494 Update description of scrape command
  docs/synapse/userguides/storm_ref_cmd.rstorm
Labels: documentation

#2495 Update aiohttp min version (SYN-2963)
  requirements.txt
  setup.py
Labels: enhancement

#2488 Adds layer index verification routines and Storm API plumbing
  setup.cfg
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_layer.py
Labels: enhancement

#2469 uniq arrays model mop up (SYN-1393, SYN-2251)
  synapse/lib/modelrev.py
  synapse/models/biz.py
  synapse/models/crypto.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/risk.py
  synapse/models/syn.py
  synapse/models/telco.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_lib_nexus.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_telco.py
Labels: enhancement

#2438 Add hasPathObj() copyPathObj() and copyPathObjs() APIs to jsonstor
  synapse/lib/jsonstor.py
  synapse/tests/test_lib_jsonstor.py
Labels: enhancement

#2499 Fix doc formatting issue
  synapse/lib/stormtypes.py
Labels: documentation

#2498 Start adding commercial docs to mainline (SYN-2954)
  docs/index.rst
  docs/synapse/devguides/cortex.hcl
  docs/synapse/devguides/demo-aha-onepod.yaml
  docs/synapse/devguides/demo-aha-pods.yaml
  docs/synapse/devguides/index_orchestration.rst
  docs/synapse/devguides/orch_hashistack.rst
  docs/synapse/devguides/orch_kubernetes.rst
  docs/synapse/devguides/shodan.hcl
  docs/synapse/devops.rst
  docs/synapse/power_ups.rst
  docs/synapse/power_ups/advanced_power_ups.rst
  docs/synapse/power_ups/rapid_power_ups.rst
  docs/synapse/support.rst
  docs/synapse/user_interface.rst
Labels: documentation

#2501 Update links (SYN-2954)
  README.rst
  docs/synapse/devguide.rst
  docs/synapse/devguides/cortex_quickstart.ipynb
  docs/synapse/intro.rst
  docs/synapse/power_ups.rst
  docs/synapse/power_ups/advanced_power_ups.rst
  docs/synapse/power_ups/rapid_power_ups.rst
  docs/synapse/support.rst
Labels: documentation

#2500 Add try/except around httpresp.json method (SYN-3007)
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#2502 Add $lib.inet.ipv6.expand (SYN-3010)
  synapse/cortex.py
  synapse/lib/stormlib/ipv6.py
  synapse/tests/test_lib_stormlib_ipv6.py
Labels: enhancement

#2504 Allow setting a custom title when generating documentation for confdefs (SYN-2954)
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: enhancement

#2505 Add stream:jsonlines to httpapi docs (SYN-2985)
  docs/synapse/httpapi.ipynb
Labels: documentation

#2506 Changelog 20211216
  CHANGELOG.rst
  docs/synapse/power_ups/advanced_power_ups.rst
  docs/synapse/power_ups/rapid_power_ups.rst
Labels: documentation

#2507 Catch indexerror during layer verify routines (VS-193)
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
Labels: bug
