Repository vertexproject/synapse, pull requests merged in 2021-05, with the labels that each got.

#2173 Have layer reported size be actual disk usage
  synapse/lib/layer.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2172 Add Storm Package autodocs and update rstorm
  synapse/lib/rstorm.py
  synapse/tests/files/rstorm/httpresp1.json
  synapse/tests/files/rstorm/httpresp2.json
  synapse/tests/files/rstorm/testsvc.py
  synapse/tests/files/stormpkg/testpkg.yaml
  synapse/tests/test_lib_rstorm.py
  synapse/tests/test_tools_autodoc.py
  synapse/tests/test_tools_rstorm.py
  synapse/tools/autodoc.py
  synapse/tools/rstorm.py
Labels: enhancement

#2174 stix 2.1 validation, stix 2.1 vuln support
  requirements.txt
  setup.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormtypes.py
  synapse/tests/files/stix_export/basic.json
  synapse/tests/files/stix_export/custom0.json
  synapse/tests/files/stix_export/risk0.json
  synapse/tests/test_lib_stormlib_stix.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2177 Autobump a user's dmons when the user is locked/unlocked
  synapse/cortex.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2181 Allow none as input to setPasswd to clear passwords.
  synapse/lib/hiveauth.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_hiveauth.py
Labels: enhancement

#2182 Clean up package deletion, $lib.pkg updates
  synapse/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_storm.py
Labels: bug, enhancement

#2184 Grab push/pull offset data when storm Layer.pack is called
  synapse/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2188 Fix mirror dmon del bug SYN-1547
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
Labels: bug

#2191 make file hashes rw and implement basic pre-set hook
  synapse/cortex.py
  synapse/lib/node.py
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: enhancement

#2194 SYN-1623: Allow view/layer admin to set user rules/admin on that object
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2195 simple it:log:event model addition
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#2183 Explicitly close generators where the remote side closed early
  synapse/daemon.py
  synapse/tests/test_daemon.py
Labels: bug

#2186 Import nodes command
  synapse/lib/storm.py
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2179 Feat struct log
  .circleci/config.yml
  synapse/common.py
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/stormlib/stix.py
  synapse/lib/structlog.py
  synapse/tests/test_common.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_structlog.py
  synapse/tests/test_servers_axon.py
  synapse/tests/test_servers_cortex.py
  synapse/tests/test_servers_cryotank.py
  synapse/tests/test_servers_univ.py
  synapse/tests/utils.py
Labels: enhancement

#2189 Remove trigger inheritance SYN-2003
  synapse/lib/trigger.py
  synapse/lib/view.py
  synapse/tests/test_lib_trigger.py
  synapse/tests/test_lib_view.py
Labels: enhancement

#2185 More useful output when using $lib.print on StormTypes
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2199 Do not document hideconf options via autodoc.
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: bug

#2198 Feat stormcmd default print
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2192 added syn:tag:part type and syn:tag norm handler for list/tuple
  synapse/datamodel.py
  synapse/lib/types.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_types.py
Labels: enhancement

#2205 lib.inet.http updates SYN-2035 SYN-2065
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
  synapse/tests/utils.py
Labels: enhancement

#2207 Bug session deref
  synapse/lib/cell.py
Labels: bug

#2210 Fix aha logger name.
  synapse/lib/aha.py
Labels: bug

#2209 Feat tee parallel
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
  synapse/tools/aha/__init__.py
Labels: enhancement

#2203 Convert storm runtime to base to allow fini and implement storm websocket that requires cleanup
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/stormhttp.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_node.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#2211 Log the ImportError exception in getDynMod SYN-1928
  synapse/lib/dyndeps.py
  synapse/tests/test_lib_dyndeps.py
Labels: bug

#2212 Bug cmdroper setargv
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
  synapse/tests/files/stormpkg/storm/commands/testpkgcmd
  synapse/tests/files/stormpkg/testpkg.yaml
  synapse/tests/test_lib_rstorm.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_tools_autodoc.py
  synapse/tests/test_tools_genpkg.py
Labels: bug, enhancement

#2214 Added storm API for to update a user name
  synapse/lib/cell.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2217 Fix rstorm http mock: body is bytes
  synapse/lib/rstorm.py
  synapse/tests/files/rstorm/httpresp3.json
  synapse/tests/test_lib_rstorm.py
Labels: bug

#2218 Prevent duplicate execution of tee queries
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2216 Incref base objects when passed to a sub-runtime
  synapse/lib/ast.py
  synapse/lib/storm.py
  synapse/tests/test_lib_stormsvc.py
Labels: bug
