Repository vertexproject/synapse, pull requests merged in 2021-02, with the labels that each got.

#2040 Added model interfaces and msoffice mime forms
  synapse/datamodel.py
  synapse/models/files.py
  synapse/tests/test_datamodel.py
  synapse/tests/test_model_files.py
Labels: enhancement

#2074 Add missing sleep in addNodes
  synapse/lib/snap.py
Labels: bug

#2075 Constrain lmdb for the time being.
  CHANGELOG.rst
  requirements.txt
  setup.py
Labels: bug

#2077 Add an optional iden argument to addUser() apis.
  synapse/lib/cell.py
  synapse/lib/hiveauth.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2081 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#2082 modularize storm HTTP handlers
  synapse/axon.py
  synapse/lib/httpapi.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement

#2089 Feature aha docs
  .circleci/config.yml
  docker/images/aha/entrypoint.sh
  docs/conf.py
  docs/synapse/devguides/cell_permissions.rst
  docs/synapse/devguides/devops_aha.rst
  docs/synapse/devguides/index_autoconf.rst
  docs/synapse/devguides/index_cells.rst
  synapse/lib/aha.py
  synapse/lib/cell.py
  synapse/lib/certdir.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_tools_aha.py
  synapse/tests/test_tools_autodoc.py
  synapse/tests/utils.py
  synapse/tools/aha/easycert.py
  synapse/tools/aha/list.py
  synapse/tools/autodoc.py
  synapse/tools/cmdr.py
Labels: bug, documentation, enhancement

#2095 Cast synapse_minversion to tuple to avoid JSON breaking storm packages
  synapse/cortex.py
  synapse/tests/test_lib_ast.py
Labels: bug

#2092 Add interfaces to output of model.getModelDefs and getModelDict
  synapse/datamodel.py
  synapse/tests/test_cortex.py
  synapse/tests/test_datamodel.py
Labels: enhancement

#2097 Add docs for assigning properties via subquery
  docs/synapse/userguides/storm_ref_data_mod.ipynb
  docs/synapse/userguides/storm_ref_subquery.ipynb
Labels: documentation
