Repository vertexproject/synapse, pull requests merged in 2021-01, with the labels that each got.

#2046 Add missing toprim/tostr calls for whois guid generation.
  synapse/lib/stormwhois.py
  synapse/tests/test_lib_stormwhois.py
Labels: bug

#2045 Plumbing simplified import/export mechanism and path metadata API in storm
  CHANGELOG.rst
  synapse/axon.py
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/httpapi.py
  synapse/lib/lmdbslab.py
  synapse/lib/snap.py
  synapse/lib/spooled.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_axon.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_spawn.py
  synapse/tests/test_lib_spooled.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2053 Add try/except around the n2 node creation
  synapse/lib/snap.py
  synapse/tests/test_cortex.py
Labels: enhancement

#2055 Allow ISIC code prefixes
  synapse/models/orgs.py
  synapse/tests/test_model_orgs.py
Labels: enhancement

#2056 Support model metadata for tags and enforce tag trees using regular expressions
  synapse/cortex.py
  synapse/lib/node.py
  synapse/lib/stormlib/model.py
  synapse/tests/test_cortex.py
Labels: enhancement

#2060 Add logs to cell backup routines.
  synapse/lib/cell.py
Labels: enhancement

#2034 Feature stormprims docs
  CHANGELOG.rst
  docs/synapse/httpapi.ipynb
  docs/synapse/userguides/storm_adv_methods.ipynb
  docs/synapse/userguides/storm_adv_vars.ipynb
  docs/synapse/userguides/storm_ref_automation.ipynb
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/autodoc.py
  synapse/lib/hiveauth.py
  synapse/lib/httpapi.py
  synapse/lib/layer.py
  synapse/lib/stormhttp.py
  synapse/lib/stormlib/backup.py
  synapse/lib/stormlib/json.py
  synapse/lib/stormlib/macro.py
  synapse/lib/stormlib/model.py
  synapse/lib/stormlib/modelext.py
  synapse/lib/stormlib/version.py
  synapse/lib/stormtypes.py
  synapse/lib/stormwhois.py
  synapse/lib/urlhelp.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_autodoc.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_stormhttp.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_tools_autodoc.py
  synapse/tests/utils.py
  synapse/tools/autodoc.py
  synapse/tools/csvtool.py
Labels: documentation, enhancement
