Repository vertexproject/synapse, pull requests merged in 2021-10, with the labels that each got.

#2390 Feat vendor libraries (SYN-2656)
  .circleci/config.yml
  MANIFEST.in
  docs/conf.py
  docs/synapse/devguides/architecture.rst
  requirements.txt
  setup.py
  synapse/lib/crypto/coin.py
  synapse/vendor/__init__.py
  synapse/vendor/cashaddress/LICENSE
  synapse/vendor/cashaddress/__init__.py
  synapse/vendor/cashaddress/base58.py
  synapse/vendor/cashaddress/convert.py
  synapse/vendor/cashaddress/crypto.py
  synapse/vendor/cashaddress/tests/__init__.py
  synapse/vendor/cashaddress/tests/test_cashaddress.py
  synapse/vendor/substrateinterface/LICENSE
  synapse/vendor/substrateinterface/__init__.py
  synapse/vendor/substrateinterface/tests/__init__.py
  synapse/vendor/substrateinterface/tests/test_ss58.py
  synapse/vendor/substrateinterface/utils/__init__.py
  synapse/vendor/substrateinterface/utils/ss58.py
  synapse/vendor/utils.py
  synapse/vendor/xrpl/LICENSE
  synapse/vendor/xrpl/__init__.py
  synapse/vendor/xrpl/constants.py
  synapse/vendor/xrpl/core/__init__.py
  synapse/vendor/xrpl/core/addresscodec/__init__.py
  synapse/vendor/xrpl/core/addresscodec/codec.py
  synapse/vendor/xrpl/core/addresscodec/exceptions.py
  synapse/vendor/xrpl/core/addresscodec/main.py
  synapse/vendor/xrpl/core/addresscodec/utils.py
  synapse/vendor/xrpl/tests/__init__.py
  synapse/vendor/xrpl/tests/test_codec.py
  synapse/vendor/xrpl/tests/test_main.py
  synapse/vendor/xrpl/tests/test_main_test_cases.py
Labels: enhancement

#2396 Fix SYN-2675 non-populated tagprops dict in node
  synapse/lib/node.py
Labels: bug

#2387 Feat crypto scrape (SYN-2598)
  .circleci/config.yml
  MANIFEST.in
  docs/conf.py
  docs/synapse/devguides/architecture.rst
  docs/synapse/httpapi.ipynb
  requirements.txt
  setup.py
  synapse/lib/crypto/coin.py
  synapse/lib/scrape.py
  synapse/tests/test_lib_crypto_coin.py
  synapse/tests/test_lib_scrape.py
  synapse/tests/test_lib_stormlib_stix.py
  synapse/vendor/__init__.py
  synapse/vendor/cashaddress/LICENSE
  synapse/vendor/cashaddress/__init__.py
  synapse/vendor/cashaddress/base58.py
  synapse/vendor/cashaddress/convert.py
  synapse/vendor/cashaddress/crypto.py
  synapse/vendor/cashaddress/tests/__init__.py
  synapse/vendor/cashaddress/tests/test_cashaddress.py
  synapse/vendor/substrateinterface/LICENSE
  synapse/vendor/substrateinterface/__init__.py
  synapse/vendor/substrateinterface/tests/__init__.py
  synapse/vendor/substrateinterface/tests/test_ss58.py
  synapse/vendor/substrateinterface/utils/__init__.py
  synapse/vendor/substrateinterface/utils/ss58.py
  synapse/vendor/utils.py
  synapse/vendor/xrpl/LICENSE
  synapse/vendor/xrpl/__init__.py
  synapse/vendor/xrpl/constants.py
  synapse/vendor/xrpl/core/__init__.py
  synapse/vendor/xrpl/core/addresscodec/__init__.py
  synapse/vendor/xrpl/core/addresscodec/codec.py
  synapse/vendor/xrpl/core/addresscodec/exceptions.py
  synapse/vendor/xrpl/core/addresscodec/main.py
  synapse/vendor/xrpl/core/addresscodec/utils.py
  synapse/vendor/xrpl/tests/__init__.py
  synapse/vendor/xrpl/tests/test_codec.py
  synapse/vendor/xrpl/tests/test_main.py
  synapse/vendor/xrpl/tests/test_main_test_cases.py
Labels: enhancement

#2398 Update regex minimum version to one that actually exposes the re API properly
  requirements.txt
  setup.py
Labels: enhancement

#2401 Bug crypto scrape
  synapse/lib/scrape.py
  synapse/tests/test_lib_scrape.py
Labels: bug

#2399 IMAP Storm library (SYN-2680)
  requirements.txt
  setup.py
  synapse/cortex.py
  synapse/lib/stormlib/imap.py
  synapse/tests/test_lib_stormlib_imap.py
Labels: enhancement

#2409 Fork doc update (SYN-2057)
  docs/synapse/glossary.rst
  synapse/lib/stormtypes.py
Labels: documentation

#2411 Add sleeps to potential hotloops in movetag (SYN-2642)
  synapse/lib/storm.py
Labels: bug

#2431 add a Storm version command (SYN-2662)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2423 crypto currency model additions
  synapse/cortex.py
  synapse/lib/stormlib/cell.py
  synapse/lib/stormtypes.py
  synapse/models/crypto.py
  synapse/models/economic.py
  synapse/tests/test_lib_stormlib_cell.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_economic.py
Labels: enhancement

#2434 Add lib.xml and lib.yaml to storm
  synapse/cortex.py
  synapse/lib/stormlib/xml.py
  synapse/lib/stormlib/yaml.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormlib_xml.py
  synapse/tests/test_lib_stormlib_yaml.py
Labels: enhancement

#2441 Adds hex string utils and bytes unpacking
  synapse/cortex.py
  synapse/lib/stormlib/hex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2442 Fix for overzealous if condition caching in storm
  synapse/lib/ast.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2439 Add try/catch blocks to storm and $lib.raise()
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
Labels: enhancement
