Repository vertexproject/synapse, pull requests merged in 2021-07, with the labels that each got.

#2268 HEAD Support for lib.inet.http.head (SYN-2275)
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
  synapse/tests/utils.py
Labels: enhancement

#2270 Fix cron test (SYN-2270)
  synapse/tests/test_cmds_cron.py
Labels: enhancement

#2271 Update the aha teardown log messages.
  synapse/lib/aha.py
Labels: enhancement

#2266 Export layer lmdb replay log size, et al
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tools/backup.py
Labels: enhancement

#2274 Adds lib.regex.replace
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2276 Add univs to dict returned by getModelDict
  synapse/datamodel.py
  synapse/tests/test_cortex.py
Labels: enhancement

#2280 Resolve some grammar ambiguities
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm_format.py
Labels: bug

#2273 Bug missing autoadd (SYN-2114)
  synapse/lib/snap.py
  synapse/tests/test_lib_stormlib_stix.py
  synapse/tests/test_model_dns.py
  synapse/tests/test_model_economic.py
  synapse/tests/test_model_files.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_telco.py
  synapse/tests/utils.py
Labels: bug

#2281 Changelog 20210713
  CHANGELOG.rst
Labels: documentation

#2285 Add lib.cell apis in stormtypes. (SYN-2302)
  synapse/cortex.py
  synapse/lib/stormlib/cell.py
  synapse/tests/test_lib_stormlib_cell.py
Labels: enhancement

#2283 Log teleLinkLoop exceptions as errors with exception information. (SYN-2336)
  synapse/telepath.py
Labels: enhancement

#2284 Fix Storm command execution with non-runtsafe opts
  synapse/lib/storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2286 Bug aha possible attributeerror (SYN-2337)
  synapse/telepath.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_telepath.py
Labels: bug

#2287 aha link teardown for distributed changes (SYN-2315)
  synapse/lib/aha.py
  synapse/lib/jsonstor.py
  synapse/tests/test_lib_aha.py
Labels: bug

#2289 More resilient tag part normalization and lib.tags.prefix() function
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_types.py
Labels: enhancement

#2225 Make stormtypes unique properly inside a Set stormtype (SYN-342)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2301 Add new spec for specifying command input forms
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2306 Feat stormtype updates
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2293 Support Telepath Shares in Storm
  synapse/lib/stormsvc.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormsvc.py
Labels: enhancement

#2292 Specify/Move View for Cron (SYN-2037)
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_agenda.py
Labels: enhancement

#2304 Model updates from 20210728
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/risk.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#2307 Add deps/requires/conflicts logic for storm-packages
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/storm.py
  synapse/lib/version.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2308 Changelog 20210729
  CHANGELOG.rst
  synapse/models/risk.py
Labels: documentation

#2309 BUG: fix cron.list display output with old cron jobs that dont have a view
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_storm.py
Labels: bug
