Repository vertexproject/synapse, pull requests merged in 2021-11, with the labels that each got.

#2447 StormTypesRegistry - directly track the known / unknown type values when they are registered or removed. SYN-2736
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2449 Make storm tool print props in precedence order.
  synapse/tests/test_tools_storm.py
  synapse/tools/storm.py
Labels: enhancement

#2448 Feat Add jsonschema validation to Storm (SYN-2690)
  synapse/lib/stormlib/json.py
  synapse/tests/test_lib_config.py
  synapse/tests/test_lib_stormlib_json.py
  synapse/tests/utils.py
Labels: enhancement

#2450 Add str.find() list.slice() and list.extend()
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2446 Add implicit wild/range time syntax to storm lift/filt AND time chop functions for storm
  requirements.txt
  setup.py
  synapse/lib/stormtypes.py
  synapse/lib/time.py
  synapse/lib/types.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_types.py
Labels: enhancement

#2451 Add inet:flow:<src|dst>:handshake and proj:attachment and Str.size()
  synapse/lib/stormtypes.py
  synapse/models/inet.py
  synapse/models/proj.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_proj.py
Labels: enhancement

#2452 Changelog for v2.70.0
  CHANGELOG.rst
  synapse/lib/stormlib/json.py
Labels: documentation

#2443 Update control flow docs
  docs/synapse/userguides/storm_adv_control.rstorm
  docs/synapse/userguides/storm_ref_intro.rst
  docs/synapse/userguides/storm_ref_subquery.rstorm
Labels: documentation

#2456 Fix issue with msgpack-ing certain path meta objects (SYN-2772)
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2457 stormtypes - when encoding a str or decoding a byts, use surrogatepass errors handler (SYN-2869)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2454 Deprecate path trace (SYN-2771)
  synapse/common.py
  synapse/lib/node.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2461 Add a 404 handler page. (SYN-2846)
  docs/conf.py
  docs/synapse/404.rst
Labels: documentation

#2464 Adds support for async triggers
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/lmdbslab.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/trigger.py
  synapse/lib/view.py
  synapse/tests/test_lib_trigger.py
Labels: enhancement

#2468 Adds $lib.axon.readlines() and $lib.axon.jsonlines() to Storm
  synapse/axon.py
  synapse/lib/stormtypes.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2460 Remove "Libraries" stub page from Storm User Guide & update links
  docs/index.rst
  docs/synapse/200_changes.rst
  docs/synapse/glossary.rst
  docs/synapse/intro.rst
  docs/synapse/userguides/bkd_why_synapse.rst
  docs/synapse/userguides/index_storm_adv.rst
  docs/synapse/userguides/storm_adv_control.rstorm
  docs/synapse/userguides/storm_adv_libs.rst
  docs/synapse/userguides/storm_adv_methods.rstorm
  docs/synapse/userguides/storm_adv_vars.rstorm
  docs/synapse/userguides/storm_ref_intro.rst
  docs/synapse/userguides/storm_ref_type_specific.rstorm
  docs/synapse/userguides/syn_tools_csvtool.rst
Labels: documentation

#2470 404 redux (SYN-2846)
  .readthedocs.yaml
  docs/conf.py
  readthedocs.yml
  requirements_doc.txt
  setup.py
  synapse/lib/stormtypes.py
Labels: documentation

#2466 Log storm query mode in structlog for storm queries (SYN-2907)
  synapse/cortex.py
  synapse/lib/snap.py
  synapse/lib/view.py
Labels: enhancement

#2471 Add a missing value to terminalEnglishMap (SYN-2907)
  synapse/lib/parser.py
Labels: bug

#2467 Docs update: type-specific behaviors
  docs/synapse/userguides/storm_adv_methods.rstorm
  docs/synapse/userguides/storm_adv_vars.rstorm
  docs/synapse/userguides/storm_ref_cmd.rstorm
  docs/synapse/userguides/storm_ref_filter.rstorm
  docs/synapse/userguides/storm_ref_lift.rstorm
  docs/synapse/userguides/storm_ref_type_specific.rstorm
Labels: documentation

#2476 Update pyopenssl / cryptography packages (SYN-2932)
  requirements.txt
  setup.py
  synapse/lib/certdir.py
Labels: enhancement

#2477 Add names to cron logging events; add structured logging to cron output (SYN-2936)
  synapse/lib/agenda.py
Labels: enhancement

#2478 Lock aiothttp-socks into a version range that has a pinned version range for python-socks (SYN-2938)
  requirements.txt
  setup.py
  synapse/tests/test_axon.py
Labels: bug

#2455 Update dmon logging to log additional state changes. SYN-2866
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
Labels: enhancement

#2480 Add Storm intersect command to allow intersecting pivot results
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2472 Catch brokenprocesspool errors - SYN-2900
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/coro.py
  synapse/lib/stormlib/stix.py
  synapse/lib/task.py
  synapse/lib/view.py
Labels: bug
