Repository vertexproject/synapse, pull requests merged in 2021-06, with the labels that each got.

#2208 wget UA
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2221 Redo tagprop keying
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_node.py
  synapse/tests/test_lib_snap.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2227 Protect a few possible places from a dictionary RuntimeError
  synapse/cortex.py
  synapse/daemon.py
Labels: bug

#2234 Fill in deprecated docs SYN-1651 SYN-1759
  docs/synapse/datamodel_deprecation.rst
  synapse/models/orgs.py
Labels: documentation

#2229 Have movetag check for cycles (SYN-1833)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2235 added toprim calls for HTTP connect args
  synapse/lib/stormhttp.py
Labels: bug

#2239 Add description field to ou:industry (SYN-2085)
  synapse/models/orgs.py
  synapse/tests/test_model_orgs.py
Labels: enhancement

#2237 Add name param to trigger add commands (SYN-2045)
  synapse/lib/storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2241 Update help command output (SYN-2062)
  docs/synapse/userguides/storm_ref_cmd.ipynb
  synapse/lib/storm.py
Labels: documentation

#2242 Define cmdformhints in the stormpackage definition. (SYN-2223)
  synapse/lib/storm.py
Labels: bug

#2240 Add regx to BadTypeValu exception of str type when regex fails to match. (SYN-2151)
  synapse/lib/types.py
Labels: bug

#2246 Fix iterNewBackupArchive link error (SYN-2241)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: bug

#2232 Tweak to genpkg (SYN-2072)
  synapse/tests/test_tools_genpkg.py
  synapse/tools/genpkg.py
Labels: enhancement

#2243 Log exceptions in callstorm (SYN-2216)
  synapse/lib/view.py
  synapse/tests/test_cortex.py
Labels: enhancement

#2248 Added contract as to/from in payment and payment memo text
  synapse/models/economic.py
  synapse/tests/test_model_economic.py
Labels: enhancement

#2249 Update backup streaming APIs link cleanup
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#2255 Log why Aha services are being set down
  synapse/lib/aha.py
Labels: enhancement

#2258 Remove incorrect cmdopts use in cdefs
  synapse/lib/stormsvc.py
  synapse/tests/test_lib_stormsvc.py
Labels: bug

#2259 Bug setlogging mock
  synapse/tests/test_lib_cell.py
  synapse/tests/test_servers_axon.py
  synapse/tests/test_servers_cortex.py
  synapse/tests/test_servers_cryotank.py
  synapse/tests/test_servers_univ.py
  synapse/tests/utils.py
Labels: bug

#2262 Update logging configuration to universally accept ints / strs (SYN-2232) (SYN-2049)
  docs/synapse/devguides/devops_cell.rst
  docs/synapse/devguides/devops_cortex.rst
  synapse/common.py
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/const.py
  synapse/tests/test_common.py
  synapse/tests/utils.py
Labels: documentation, enhancement

#2260 Call _normStormPkg in all loadStormPkg paths
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/lib/stormsvc.py
Labels: enhancement

#2265 Adds findall() behavior to lib.regex
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2263 Fixes SYN-2250 trigger.pack() error on deleted user
  synapse/lib/trigger.py
Labels: bug

#2261 Stormtypes Doc update (SYN-2058)
  synapse/lib/rstorm.py
  synapse/lib/stormlib/project.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormtypes.py
  synapse/models/proj.py
  synapse/tests/test_model_proj.py
Labels: documentation, enhancement
