Repository vertexproject/synapse, pull requests merged in 2021-08, with the labels that each got.

#2313 Prevents renaming all role (SYN-2454)
  synapse/lib/hiveauth.py
  synapse/tests/test_lib_hiveauth.py
Labels: bug

#2311 Enforce node data perms at the layer and add auth.self.set perms checks
  docs/synapse/devguides/cell_permissions.rst
  synapse/lib/cell.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2318 Changelog 20210805
  CHANGELOG.rst
Labels: documentation

#2317 Multiple http requests in single command for storm docs (SYN-2435)
  requirements.txt
  setup.py
  synapse/lib/rstorm.py
  synapse/tests/files/rstorm/httprespmulti.yaml
  synapse/tests/test_lib_rstorm.py
Labels: enhancement

#2328 Added stemcell server
  .circleci/config.yml
  docker/images/stemcell/Dockerfile
  docker/images/stemcell/entrypoint.sh
  synapse/cells.py
  synapse/lib/cell.py
  synapse/servers/stemcell.py
  synapse/tests/test_servers_stemcell.py
Labels: enhancement

#2330 Refactor some axon code
  synapse/axon.py
  synapse/common.py
  synapse/lib/coro.py
  synapse/tests/test_axon.py
Labels: enhancement

#2331 Add rstorm support multi-line secondary properties for nodes (SYN-2531)
  synapse/cmds/cortex.py
  synapse/lib/rstorm.py
  synapse/tests/test_lib_rstorm.py
Labels: bug

#2333 Model updates 20210823
  synapse/models/inet.py
  synapse/models/orgs.py
  synapse/models/proj.py
  synapse/models/risk.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_proj.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#2325 update wget docs for --headers arg for clarity (SYN-2417)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: documentation

#2344 LibLift/Snap caching issue fix (SYN-2565)
  synapse/lib/snap.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug
