Repository vertexproject/synapse, pull requests merged in 2022-08, with the labels that each got.

#2784 Add svcadd waiters to getmirrors test (SYN-3923)
  synapse/tests/test_lib_stormlib_cell.py
Labels: bug

#2786 Add missing libstix docstring (SYN-3890)
  synapse/lib/stormlib/stix.py
Labels: bug, documentation

#2787 Spelling fixes in honor of neomorph
  synapse/models/crypto.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/transport.py
Labels: documentation

#2788 Add livebackup tool
  synapse/tests/test_tools_livebackup.py
  synapse/tools/livebackup.py
Labels: enhancement

#2785 Fix Aha waiters for replay and check mirror status (SYN-3923)
  synapse/lib/nexus.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormlib_cell.py
Labels: bug

#2791 Add aha:// support to csvtool, refactor tool (SYN-3949)
  synapse/tests/test_tools_csvtool.py
  synapse/tools/csvtool.py
Labels: bug

#2778 Model Updates 2022-07-28
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/risk.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#2792 Feat changelog 20220803
  CHANGELOG.rst
Labels: documentation

#2766 Fix very large and high precision hugenum index values
  synapse/common.py
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_model_crypto.py
Labels: enhancement

#2796 Thesilence newdocs
  docs/synapse/glossary.rst
  docs/synapse/userguides/analytical_model_tags.rstorm
  docs/synapse/userguides/data_model_form_categories.rst
  docs/synapse/userguides/data_model_object_categories.rstorm
  docs/synapse/userguides/data_model_terms.rstorm
  docs/synapse/userguides/storm_ref_data_mod.rstorm
  docs/synapse/userguides/storm_ref_intro.rst
  docs/synapse/userguides/storm_ref_pivot.rstorm
Labels: documentation

#2797 Inject the tag name into the BadTypeValu when norming a tag (SYN-3982, SYN-2923)
  synapse/exc.py
  synapse/lib/snap.py
  synapse/tests/test_cortex.py
  synapse/tests/test_exc.py
  synapse/tests/test_lib_node.py
Labels: bug

#2798 CircleCI - Fix incorrect image tag argument, add missing filters
  .circleci/config.yml
  CHANGELOG.rst
Labels: bug

#2799 Add ps:contact:title migration (SYN-3944)
  synapse/lib/modelrev.py
  synapse/models/person.py
  synapse/tests/test_lib_modelrev.py
Labels: enhancement

#2795 synapse.lib.coro.spawn logging update
  synapse/axon.py
  synapse/common.py
  synapse/lib/cell.py
  synapse/lib/coro.py
  synapse/lib/httpapi.py
  synapse/lib/storm.py
  synapse/lib/stormlib/json.py
  synapse/lib/stormlib/mime.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormlib/xml.py
Labels: enhancement

#2789 Migrate crypto:X509:cert:serial prop from str to hex (SYN-3837)
  synapse/lib/modelrev.py
  synapse/lib/stormlib/hex.py
  synapse/lib/stormtypes.py
  synapse/models/crypto.py
  synapse/models/person.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_lib_stormlib_hex.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_crypto.py
Labels: enhancement

#2800 Include node iden in model migration warnings
  synapse/lib/modelrev.py
Labels: enhancement

#2801 Doc changelog 20220809
  CHANGELOG.rst
Labels: documentation

#2806 Assorted bugfixes (SYN-3973, SYN-3987, SYN-4002)
  .circleci/config.yml
  synapse/lib/storm.py
  synapse/lib/stormlib/model.py
Labels: bug

#2762 Hugenum math in Storm (SYN-3350)
  synapse/common.py
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/stormlib/math.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: enhancement

#2813 Add axon2axon command
  synapse/tests/test_tools_axon2axon.py
  synapse/tools/axon2axon.py
Labels: enhancement

#2816 Feat axon2axon aha
  synapse/tests/test_tools_axon2axon.py
  synapse/tools/axon2axon.py
Labels: enhancement

#2815 Pass subquery filter vars back out (SYN-4031)
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: bug

#2817 Doc changelog 20220823
  CHANGELOG.rst
  docs/synapse/power_ups/rapid_power_ups.rst
Labels: documentation

#2818 Add Axon metrics Stormlib (SYN-3939)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2823 Add role.pack() and user.pack() methods in storm (SYN-4050)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2824 Add a note about backup storage use (SYN-3921)
  docs/synapse/devopsguide.rst
Labels: documentation
