Repository vertexproject/synapse, pull requests merged in 2022-07, with the labels that each got.

#2743 basic hash bytes from storm (VS-248)
  synapse/cortex.py
  synapse/lib/stormlib/hashes.py
  synapse/tests/test_lib_stormlib_hashes.py
Labels: enhancement

#2714 Add movesodes storm command (VS-220, SYN-3716)
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2733 Deal with an interesting error in test_storm_pushpull
  synapse/lib/cell.py
Labels: bug

#2749 Bug: Fix %z based lib.time.parse calls (SYN-3819)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2752 Update pycryptodome, pygments, and scalecodec max versions.
  requirements.txt
  setup.py
Labels: enhancement

#2719 Feat storm csv reader (SYN-3731, SYN-3783)
  synapse/axon.py
  synapse/exc.py
  synapse/lib/link.py
  synapse/lib/queue.py
  synapse/lib/stormtypes.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, enhancement

#2755 Axon coverage update
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: enhancement

#2756 Doc changelog 20220711
  CHANGELOG.rst
  docs/synapse/httpapi.ipynb
  synapse/models/transport.py
Labels: documentation

#2754 Storm library $lib.gen for generating nodes based on secondary property deconfliction
  synapse/cortex.py
  synapse/lib/stormlib/gen.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormlib_gen.py
Labels: enhancement

#2758 Add missing axon API get arguments, update changelog.
  CHANGELOG.rst
  synapse/axon.py
Labels: bug, documentation

#2761 Fix doc links
  docs/synapse/devopsguide.rst
Labels: bug, documentation

#2767 Docs update
  docs/synapse/glossary.rst
  docs/synapse/userguides/storm_ref_filter.rstorm
Labels: documentation

#2760 APIs and Storm libs for enumerating mirrors via AHA (SYN-3513)
  synapse/lib/aha.py
  synapse/lib/cell.py
  synapse/lib/stormlib/cell.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormlib_cell.py
Labels: enhancement

#2770 Create subs when merging part of a view using merge --apply (SYN-3827)
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2769 Make Storm command arg parse error an exception (SYN-3753)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_tools_genpkg.py
Labels: enhancement

#2768 Add storm opt to specify task iden
  synapse/cortex.py
  synapse/lib/boss.py
  synapse/lib/task.py
  synapse/lib/view.py
  synapse/tests/test_lib_boss.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2774 Add type checking to externally specified task iden
  synapse/lib/task.py
  synapse/tests/test_lib_boss.py
  synapse/tests/test_lib_task.py
Labels: enhancement

#2772 Add support for handling timezones without colon seperators (SYN-2841)
  synapse/lib/time.py
  synapse/tests/test_lib_time.py
Labels: bug

#2773 Add support for exporting custom STIX objects
  synapse/lib/stormlib/stix.py
  synapse/tests/test_lib_stormlib_stix.py
Labels: enhancement

#2775 Clarify AHA URLs with ...
  docs/synapse/deploymentguide.rst
Labels: documentation

#2776 BUGFIX: Allow cron listing when user has been deleted
  synapse/cortex.py
  synapse/tests/test_cortex.py
Labels: bug

#2777 Changelog for v2.102.0
  CHANGELOG.rst
  docs/synapse/userguides/storm_ref_filter.rstorm
  synapse/models/base.py
Labels: documentation

#2716 support publishing images to alternative registry (SYN-3618)
  .circleci/config.yml
  docker/README.rst
  docker/bootstrap.sh
  docker/build_all.sh
  docker/build_image.sh
  docker/images/synapse/Dockerfile
  docker/images/synapse/Dockerfile-py37
  docker/scripts/push_all.sh
  docker/scripts/retag_all.sh
  docker/scripts/save_all.sh
  docker/scripts/test_all.sh
  docs/synapse/devguide.rst
  docs/synapse/devguides/docker.rst
  synapse/docker/start-cron.sh
  synapse/servers/stemcell.py
Labels: enhancement

#2780 Axon HTTP 404 handler for by/sha256 path (SYN-3878)
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: enhancement

#2781 Ensure errors are logged prior to backup teardown (SYN-3922)
  synapse/lib/cell.py
Labels: enhancement

#2779 Change count behavior with --yield (SYN-3846)
  docs/synapse/power_ups/rapid_power_ups.rst
  docs/synapse/userguides/storm_ref_cmd.rstorm
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement, documentation

#2783 Adds $lib.random.int() to storm
  synapse/cortex.py
  synapse/lib/stormlib/random.py
  synapse/tests/test_lib_stormlib_random.py
Labels: enhancement
