Repository vertexproject/synapse, pull requests merged in 2022-05, with the labels that each got.

#2664 Add params option to inet.http.connect (SYN-3464)
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#2660 Ensure that the Cli histfile is readable / writeable during startup (SYN-3471)
  synapse/lib/cli.py
Labels: bug

#2649 Storm LALR(1) conversion (SYN-2359, SYN-3081, SYN-3419)
  requirements.txt
  setup.py
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_cmds_cortex.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_tools_storm.py
  synapse/tests/test_utils.py
Labels: enhancement

#2667 Update powerups related documenation
  docs/synapse/power_ups/advanced_power_ups.rst
  docs/synapse/power_ups/rapid_power_ups.rst
Labels: documentation

#2654 Fix node:del not running when adding nodeedits directly to view/snap (SYN-3462, SYN-3522)
  synapse/cortex.py
  synapse/lib/snap.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_view.py
Labels: bug

#2674 Remove limit prints (SYN-3511)
  synapse/lib/ast.py
  synapse/lib/storm.py
Labels: enhancement

#2675 Bug: when tls user certs are provided, require their user to be present (SYN-3535)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: bug

#2677 Restore autodoc config escaping (SYN-3579)
  synapse/tests/test_tools_autodoc.py
  synapse/tools/autodoc.py
Labels: bug

#2679 Add mirror option to aha:// URLs, randomize telepath client connect order, handle lists in openurl
  synapse/exc.py
  synapse/lib/aha.py
  synapse/lib/link.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_telepath.py
Labels: enhancement

#2680 Skip telepath test if default port is bound (SYN-3605)
  synapse/tests/test_telepath.py
Labels: enhancement

#2678 Adds lib.copy() to storm (SYN-3593)
  synapse/lib/msgpack.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2683 Stormtypes doc fix
  docs/synapse/stormtypes.rst
Labels: documentation

#2685 Process Storm function kwargs before converting
  synapse/lib/parser.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2687 Validate config values when set (SYN-3613)
  synapse/common.py
  synapse/lib/cell.py
  synapse/lib/config.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/trigger.py
  synapse/lib/view.py
  synapse/tests/test_common.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_config.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_trigger.py
  synapse/tests/test_servers_cortex.py
Labels: enhancement

#2681 Add nexus ready status to aha mirrors filter
  synapse/lib/agenda.py
  synapse/lib/aha.py
  synapse/lib/cell.py
  synapse/lib/nexus.py
  synapse/lib/version.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_hiveauth.py
  synapse/tests/test_lib_nexus.py
  synapse/tests/utils.py
Labels: enhancement

#2690 Rename EQUAL terminal to EQSPACE (SYN-3642)
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2689 Add "search" mode to storm
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
Labels: enhancement

#2691 Relax trigger schema validation (SYN-3613)
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/trigger.py
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_trigger.py
Labels: enhancement

#2693 Remove a unused argument in getAhaProxy
  CHANGELOG.rst
  synapse/telepath.py
Labels: bug

#2701 Call nexsroot.recover() during cell startup (SYN-3219)
  synapse/lib/cell.py
  synapse/lib/view.py
Labels: enhancement

#2703 Add listening ports to provisioning cli
  docs/synapse/devopsguide.rst
  synapse/lib/aha.py
  synapse/tests/test_lib_aha.py
  synapse/tools/aha/provision/service.py
Labels: enhancement

#2704 Feat changelog 20220531
  CHANGELOG.rst
Labels: documentation
