Repository vertexproject/synapse, pull requests merged in 2022-09, with the labels that each got.

#2822 Prevent "None" tags being created from null variables (SYN-4004)
  synapse/lib/ast.py
  synapse/tests/test_lib_ast.py
Labels: bug

#2819 Test API additions for better package test conventions
  CHANGELOG.rst
  docs/conf.py
  synapse/lib/base.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_tools_genpkg.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: enhancement

#2820 No longer fail for unmet stormpkg reqs and add verification API (SYN-4034)
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2827 Add ** power operator to Storm (SYN-3870)
  synapse/common.py
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2828 Model updates 2022-09-01
  synapse/lib/modelrev.py
  synapse/models/geopol.py
  synapse/models/geospace.py
  synapse/models/inet.py
  synapse/models/media.py
  synapse/models/risk.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_model_geopol.py
  synapse/tests/test_model_geospace.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#2825 Avoid converting Storm Numbers to floats for storage ops (SYN-4039)
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2826 Update min and max Storm command help (SYN-4063)
  synapse/lib/storm.py
Labels: enhancement

#2830 Changelog for v2.107.0
  CHANGELOG.rst
  docs/synapse/devguides/power-ups.rst
Labels: documentation

#2831 Fix incorrect genpkg arg in docs
  docs/synapse/devguides/power-ups.rst
Labels: bug, documentation

#2832 Update aiosmtplib
  requirements.txt
  setup.py
Labels: enhancement

#2833 Enforce Telepath ssl:// minimum version to TLS 1.2 (SYN-4053)
  synapse/lib/certdir.py
  synapse/tests/test_lib_link.py
  synapse/tests/test_telepath.py
Labels: bug

#2836 Catch FileNotFoundError in healthcheck (SYN-4119)
  synapse/tests/test_tools_healthcheck.py
  synapse/tools/healthcheck.py
Labels: bug

#2837 Update axon to override initService methods rather than anit (SYN-4111)
  synapse/axon.py
Labels: enhancement

#2838 Replace livenessProbe with readinessProbe (SYN-3125, SYN-4084)
  docs/synapse/devguides/demo-aha-pods.yaml
  docs/synapse/devopsguide.rst
Labels: documentation

#2835 Ignore encoding errors in csvrows (SYN-4049)
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: bug

#2839 Correct syn:splice:splice type to be `data` not `str`. resolves SYN-4126
  synapse/models/syn.py
Labels: bug

#2840 Catch transformer errors in other query modes (SYN-4133)
  synapse/lib/parser.py
  synapse/tests/test_lib_grammar.py
Labels: bug

#2834 Add storm and update http api docs (SYN-4030, SYN-4041, SYN-4044)
  CHANGELOG.rst
  docs/synapse/devguide.rst
  docs/synapse/devguides/storm_api.rst
  docs/synapse/devopsguide.rst
  docs/synapse/httpapi.ipynb
  docs/synapse/httpapi.rst
  examples/httpapi/aiohttp_storm_example.py
  examples/httpapi/requests_storm_example.py
  synapse/lib/ast.py
  synapse/lib/task.py
Labels: documentation

#2844 Use withTeleEnv in all tools (SYN-4046)
  synapse/tests/test_tools_autodoc.py
  synapse/tests/test_tools_feed.py
  synapse/tests/test_tools_pullfile.py
  synapse/tests/test_tools_storm.py
  synapse/tools/aha/easycert.py
  synapse/tools/aha/list.py
  synapse/tools/autodoc.py
  synapse/tools/cellauth.py
  synapse/tools/cmdr.py
  synapse/tools/cryo/cat.py
  synapse/tools/cryo/list.py
  synapse/tools/csvtool.py
  synapse/tools/feed.py
  synapse/tools/genpkg.py
  synapse/tools/healthcheck.py
  synapse/tools/hive/load.py
  synapse/tools/hive/save.py
  synapse/tools/pullfile.py
  synapse/tools/pushfile.py
  synapse/tools/storm.py
Labels: enhancement

#2847 Update aioimap requirement (SYN-4120)
  requirements.txt
  setup.py
Labels: enhancement

#2849 Str.format() (SYN-4134)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2848 Thesilence docs
  docs/synapse/userguides/analytical_model_tags.rstorm
  docs/synapse/userguides/analytical_model_tags_analysis.rst
  docs/synapse/userguides/data_model_terms.rstorm
  docs/synapse/userguides/design_analytical_model.rst
  docs/synapse/userguides/design_data_model.rst
  docs/synapse/userguides/design_forms_vs_tags.rst
Labels: documentation

#2853 Fix tools with incorrect default telepath URLs
  synapse/tools/aha/provision/service.py
  synapse/tools/aha/provision/user.py
  synapse/tools/livebackup.py
  synapse/tools/modrole.py
  synapse/tools/moduser.py
  synapse/tools/promote.py
Labels: bug

#2852 More spelling/doc fixes. Fixes: SYN-4150, SYN-4142, SYN-4102, SYN-4101,
  synapse/lib/storm.py
  synapse/models/base.py
  synapse/models/crypto.py
  synapse/models/files.py
  synapse/models/geopol.py
  synapse/models/geospace.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/person.py
Labels: documentation

#2845 Drop RSA based TLS ciphers and disable client renegotiation (SYN-4119)
  synapse/lib/cell.py
  synapse/lib/certdir.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_telepath.py
Labels: enhancement

#2854 Update the minimum version of oauthlib (SYN-4163)
  requirements.txt
  setup.py
Labels: enhancement

#2850 Aha root user (SYN-4054, SYN-3953)
  synapse/lib/aha.py
  synapse/lib/base.py
  synapse/lib/cell.py
  synapse/tests/test_lib_aha.py
  synapse/tests/utils.py
  synapse/tools/aha/enroll.py
Labels: enhancement

#2855 Doc changelog 20220926
  CHANGELOG.rst
Labels: documentation

#2846 Split off expression rules in Storm grammar, adjust EDGEN2INIT regex (SYN-4141)
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_lib_grammar.py
Labels: bug

#2857 Bug - Cortex with embedded Axon parent relationship not set (SYN-4171)
  synapse/cortex.py
  synapse/tests/test_cortex.py
Labels: bug

#2856 Docs rtd conf (SYN-4180)
  .readthedocs.yaml
Labels: documentation

#2858 Fix cron.move help
  synapse/lib/storm.py
Labels: bug, documentation

#2861 Add deprecation warnings to splice.undo and splice.list (SYN-4127)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2863 Update synapse-rss related documentation.
  docs/synapse/power_ups/advanced_power_ups.rst
  docs/synapse/power_ups/rapid_power_ups.rst
Labels: documentation

#2862 Mark the /storm/nodes API deprecated for parity with eval apis (SYN-4095)
  docs/synapse/httpapi.rst
  synapse/common.py
  synapse/lib/httpapi.py
Labels: enhancement
