Repository vertexproject/synapse, pull requests merged in 2022-01, with the labels that each got.

#2510 String-ify lib.inet.http headers and param values (SYN-3053)
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#2512 Add host property to risk:hasvuln (SYN-3044)
  synapse/models/risk.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#2511 v2.76.0 changelog
  CHANGELOG.rst
Labels: documentation

#2503 Macho model and defines (SYN-2768)
  synapse/lookup/macho.py
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: enhancement

#2518 Add yu to tld list (SYN-3066)
  synapse/data/iana.tlds.mpk
Labels: enhancement

#2519 Add mesg arguments to all nosuchprop exceptions (SYN-3067)
  synapse/datamodel.py
  synapse/lib/ast.py
  synapse/lib/node.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/tests/test_cortex.py
  synapse/tests/test_tools_storm.py
Labels: enhancement

#2514 Adds risk:mitigation it:prod:hardware it:prod:component it:screenshot it:exec:url DOM capture props
  synapse/lib/types.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/risk.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#2516 Allow Axon to POST multipart form-data with files (SYN-3065)
  synapse/axon.py
  synapse/lib/stormhttp.py
  synapse/lib/stormtypes.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#2520 Expand some requirements version ranges (SYN-3070)
  requirements.txt
  setup.py
Labels: enhancement

#2517 Update linux.getTotalMemory to respect cgroupv2 and fallback to /proc/meminfo (SYN-3063)
  synapse/lib/platforms/linux.py
Labels: bug

#2522 fix for tagprop migration with missing indexes
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
Labels: bug

#2523 Bug layr7 regression
  CHANGELOG.rst
  docs/synapse/devguides/devops_general.rst
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
Labels: bug

#2525 Expand the version range of typing-extensions that we allow (SYN-3058)
  requirements.txt
  setup.py
Labels: enhancement

#2515 Set a view's parent from storm
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_view.py
Labels: enhancement

#2508 scrape with context (SYN-3030)
  synapse/cortex.py
  synapse/lib/crypto/coin.py
  synapse/lib/scrape.py
  synapse/lib/stormlib/scrape.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_scrape.py
  synapse/tests/test_lib_stormlib_scrape.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2526 Add new scrape fangs (SYN-3097)
  synapse/lib/scrape.py
  synapse/tests/test_lib_scrape.py
Labels: enhancement

#2524 next round of layer verify improvements, split getStorNode()/genStorNode() logic, expose getStorNode() via storm
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2527 Fix missing keyword argument in AxonApi.wput method SYN-3107
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: bug

#2528 Add name and desc props to it:prod:softver
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#2529 changelog for v2.79.0
  CHANGELOG.rst
Labels: documentation

#2531 Auto-generate workflows in genpkg from dir (SYN-3106)
  synapse/tests/files/stormpkg/testpkg.yaml
  synapse/tests/files/stormpkg/workflows/testpkg-bam.newp
  synapse/tests/files/stormpkg/workflows/testpkg-baz.yaml
  synapse/tests/files/stormpkg/workflows/testpkg-foo.yaml
  synapse/tests/test_tools_genpkg.py
  synapse/tools/genpkg.py
Labels: enhancement

#2513 Durable user notifications and begin Cell embedding formalism
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/jsonstor.py
  synapse/lib/slabseqn.py
  synapse/lib/stormlib/notifications.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_nexus.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/utils.py
Labels: bug, enhancement

#2534 Update packaging, pycryptome, scalecodec packages
  .circleci/config.yml
  requirements.txt
  requirements_dev.txt
  setup.py
Labels: enhancement

#2535 Add node.tags leaf argument in storm (SYN-3136)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2536 BUGFIX: embedded jsonstor needs stable iden
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/hiveauth.py
  synapse/tests/test_cortex.py
Labels: bug

#2538 Add _ as a valid prop/form/type name char
  synapse/lib/grammar.py
  synapse/lib/storm.lark
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormlib_modelext.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#2539 Add a CPE2.2 storm hotfix (VS-200)
  CHANGELOG.rst
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/stormlib/cell.py
  synapse/lib/types.py
  synapse/tests/test_lib_stormlib_cell.py
  synapse/tests/test_lib_stormlib_model.py
Labels: bug, enhancement
