Repository vertexproject/synapse, pull requests merged in 2022-06, with the labels that each got.

#2705 Misc cleanup
  synapse/cortex.py
  synapse/lib/aha.py
  synapse/lib/ast.py
  synapse/lib/cell.py
  synapse/lib/certdir.py
  synapse/lib/crypto/coin.py
  synapse/lib/interval.py
  synapse/lib/jupyter.py
  synapse/lib/scrape.py
  synapse/lib/snap.py
  synapse/lib/stormlib/ethereum.py
  synapse/lib/stormlib/log.py
  synapse/lib/stormlib/oauth.py
  synapse/lib/stormlib/scrape.py
  synapse/lib/stormlib/storm.py
  synapse/lib/stormlib/version.py
  synapse/lib/stormlib/xml.py
  synapse/lib/stormsvc.py
  synapse/lib/stormtypes.py
  synapse/lib/threads.py
  synapse/models/economic.py
  synapse/models/proj.py
  synapse/servers/cell.py
  synapse/tests/test_cmds_trigger.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_hiveauth.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_jsonstor.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_lib_stormlib_ethereum.py
  synapse/tests/test_lib_stormlib_oauth.py
  synapse/tests/test_lib_stormlib_scrape.py
  synapse/tests/test_lib_trigger.py
  synapse/tests/test_model_biz.py
  synapse/tests/test_model_files.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_telco.py
  synapse/tests/test_servers_cortex.py
  synapse/tests/test_tools_aha.py
  synapse/tests/test_tools_csvtool.py
  synapse/tests/test_tools_hivesave.py
  synapse/tests/test_tools_pullfile.py
  synapse/tests/test_tools_pushfile.py
  synapse/tools/aha/easycert.py
  synapse/tools/genpkg.py
  synapse/tools/modrole.py
  synapse/tools/moduser.py
  synapse/tools/promote.py
  synapse/tools/pushfile.py
  synapse/vendor/utils.py
Labels: enhancement

#2698 Adjust number terminal regex, add LISTTOKN (SYN-3655)
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2707 Add aha provisioning httpapi (SYN-3674)
  docs/synapse/httpapi.ipynb
  synapse/lib/aha.py
  synapse/tests/test_lib_aha.py
Labels: enhancement

#2710 Add --tag and --prop option to diff and update merge examples
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: documentation

#2711 Add the ability to set a non-forked views layers from storm via $view.set(layers, $idens)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#2712 Feat changelog 20220606
  CHANGELOG.rst
Labels: documentation

#2715 Allow 'func' as a named param name in storm function calls (SYN-3536)
  synapse/lib/ast.py
  synapse/tests/test_lib_ast.py
Labels: bug

#2713 Deal with flakey test_storm_pushpull (SYN-3646)
  synapse/lib/cell.py
Labels: bug

#2722 Add additional aha logging (SYN-3744)
  synapse/lib/aha.py
Labels: enhancement

#2723 Nexus - Only set ahaready when ahasvcname is set. (SYN-3743)
  synapse/lib/nexus.py
Labels: bug

#2724 v2.98.0 Changelog
  CHANGELOG.rst
Labels: documentation

#2726 csvtool - add view and optsfile arguments
  synapse/tests/test_tools_csvtool.py
  synapse/tools/csvtool.py
Labels: enhancement

#2727 Add an initial modular/extensible STIX import library
  synapse/lib/stormlib/stix.py
  synapse/models/infotech.py
  synapse/models/person.py
  synapse/tests/files/stix_import/apt1.json
  synapse/tests/files/stix_import/oasis-example-00.json
  synapse/tests/test_lib_stormlib_stix.py
Labels: enhancement

#2728 Add Storm uptime command and API (SYN-3658, SYN-3756)
  synapse/lib/platforms/linux.py
  synapse/lib/storm.py
  synapse/lib/stormlib/cell.py
  synapse/tests/test_lib_stormlib_cell.py
Labels: enhancement

#2729 Changelog 20220623
  CHANGELOG.rst
Labels: documentation

#2734 Bugfix: Normalize tag value lists to tuple in snap.addTag() to norm JSON inputs
  synapse/lib/snap.py
  synapse/tests/test_lib_httpapi.py
Labels: bug

#2732 Support parsing with CVSS version prefix (SYN-3071)
  synapse/lib/stormlib/infosec.py
  synapse/tests/test_lib_stormlib_infosec.py
Labels: enhancement

#2735 Update powerups list
  docs/synapse/power_ups/advanced_power_ups.rst
  docs/synapse/power_ups/rapid_power_ups.rst
Labels: documentation

#2736 Changelog for v2.100.0
  CHANGELOG.rst
Labels: documentation
