Repository vertexproject/synapse, pull requests merged in 2022-12, with the labels that each got.

#2935 Feat requirements update
  requirements.txt
  requirements_dev.txt
  setup.py
Labels: enhancement

#2936 Changelog for v2.115.0
  CHANGELOG.rst
Labels: documentation

#2938 Remove OBE insecure mode reference (SYN-4408)
  docs/synapse/devguides/certbot.sh
  docs/synapse/httpapi.rst
Labels: documentation

#2941 Genpkg / rapid powerup fixes (SYN-4492, SYN-4493)
  docs/synapse/devguides/power-ups.rst
  synapse/tests/test_tools_genpkg.py
  synapse/tools/genpkg.py
Labels: bug, documentation

#2939 Bug: Remove aha:provision from cell.yaml during provisioning (SYN-4476)
  synapse/lib/cell.py
  synapse/tests/test_lib_aha.py
Labels: bug

#2942 Check for array prop refs in node deletes (SYN-4434)
  synapse/cortex.py
  synapse/datamodel.py
  synapse/lib/ast.py
  synapse/lib/snap.py
  synapse/tests/test_cortex.py
Labels: bug

#2944 Docs changelog 20221213
  CHANGELOG.rst
Labels: documentation

#2948 Fix incorrect enroll command in deployment docs
  docs/synapse/devopsguide.rst
Labels: documentation

#2950 Make risk:tool:software:soft:names uniq (SYN-4480)
  synapse/lib/modelrev.py
  synapse/models/risk.py
  synapse/tests/test_lib_modelrev.py
Labels: enhancement

#2951 Fix snap.addnode warning messages.
  synapse/lib/snap.py
Labels: bug

#2949 Add nexsoffs to cellInfo() apis (SYN-4522)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#2945 Bytes.json() now raises synerr exceptions on error (SYN-4506)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2910 OAuth V2 manager (SYN-4177)
  synapse/cortex.py
  synapse/lib/oauth.py
  synapse/lib/stormlib/oauth.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormlib_oauth.py
Labels: enhancement

#2946 Mark provenance APIs for removal in v2.221.0 (SYN-4464)
  synapse/cortex.py
Labels: enhancement, documentation

#2955 Fix storm smtp html methods (SYN-4539)
  synapse/lib/stormlib/smtp.py
  synapse/tests/test_lib_stormlib_smtp.py
Labels: bug

#2940 rapid power-up code signing
  synapse/common.py
  synapse/cortex.py
  synapse/data/__init__.py
  synapse/data/certs/cas/The Vertex Project Intermediate CA 00.crt
  synapse/data/certs/cas/The Vertex Project ROOT CA.crt
  synapse/data/certs/crls/The Vertex Project Intermediate CA 00.crl
  synapse/data/certs/crls/The Vertex Project ROOT CA.crl
  synapse/exc.py
  synapse/lib/cell.py
  synapse/lib/certdir.py
  synapse/lib/crypto/rsa.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_common.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_certdir.py
  synapse/tests/test_tools_easycert.py
  synapse/tests/test_utils.py
  synapse/tools/easycert.py
  synapse/tools/genpkg.py
Labels: enhancement

#2957 Update manifest to add embedded CA certificates
  MANIFEST.in
Labels: bug, enhancement

#2958 Ensure packages produced by genpkg are always valid json to avoid python json.dumps type casting (SYN-4491)
  synapse/common.py
  synapse/tests/files/stormpkg/badjsonpkg.yaml
  synapse/tests/test_common.py
  synapse/tests/test_tools_genpkg.py
  synapse/tools/genpkg.py
Labels: enhancement
