Repository vertexproject/synapse, pull requests merged in 2022-04, with the labels that each got.

#2624 Add meta:rule and created/updated times to meta:ruleset / it:app:yara:rule
  synapse/models/base.py
  synapse/models/infotech.py
  synapse/tests/test_model_base.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#2619 Cell mirror option docs (SYN-3345)
  docs/synapse/devguides/devops_cell.rst
  synapse/axon.py
  synapse/common.py
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/aha.py
  synapse/lib/cell.py
  synapse/lib/httpapi.py
  synapse/lib/stormlib/imap.py
  synapse/models/infotech.py
  synapse/tests/test_tools_autodoc.py
  synapse/tests/test_utils.py
  synapse/tools/autodoc.py
Labels: documentation

#2625 Fix duplicated results on array regex lifts (SYN-3338)
  synapse/lib/layer.py
  synapse/tests/test_lib_types.py
Labels: enhancement

#2627 Add JsonStor container (SYN-3436)
  .circleci/config.yml
  docker/images/jsonstor/Dockerfile
  docker/images/jsonstor/entrypoint.sh
  docs/conf.py
  docs/synapse/devguides/devops_jsonstor.rst
  docs/synapse/devguides/index_autoconf.rst
  docs/synapse/devguides/index_cells.rst
Labels: enhancement

#2626 Allow specifying version in $lib.import
  synapse/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#2628 Changelog for v2.90.0
  CHANGELOG.rst
Labels: documentation

#2629 Update Cell backup logging (SYN-3443)
  synapse/lib/cell.py
Labels: enhancement

#2630 Change SYN_SLAB_COMMIT_WARN from 5.0 to 1.0 (SYN-3426)
  synapse/lib/lmdbslab.py
Labels: enhancement

#2633 Update Storm command reference
  docs/synapse/devguides/cell_permissions.rst
  docs/synapse/glossary.rst
  docs/synapse/userguides/storm_ref_cmd.rstorm
Labels: documentation

#2635 Remove strip if onespace is specified (SYN-3421)
  synapse/models/base.py
  synapse/models/geospace.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/models/proj.py
  synapse/models/risk.py
  synapse/models/transport.py
  synapse/tests/test_lib_chop.py
Labels: enhancement

#2636 Adjust comma requirements in exprlist and exprdict (SYN-3439, SYN-3279)
  synapse/lib/storm.lark
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2634 Inet:url norm updates (SYN-3260 SYN-3360 SYN-3392)
  synapse/models/inet.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#2637 Add documentation annotations for ctors, gtors, and stors in stormtypes (SYN-3444)
  docs/conf.py
  synapse/lib/autodoc.py
  synapse/lib/stormlib/model.py
  synapse/lib/stormlib/project.py
  synapse/lib/stormlib/smtp.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_autodoc.py
  synapse/tests/test_model_proj.py
Labels: enhancement, documentation

#2638 log cell startup errors and handle lmdb.LockError in lmdbslab (SYN-3412)
  synapse/exc.py
  synapse/lib/cell.py
  synapse/lib/lmdbslab.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#2639 Cut over Project to use gtors instead of locls (SYN-3472)
  synapse/lib/stormlib/project.py
  synapse/tests/test_model_proj.py
Labels: enhancement

#2647 Log a storm query execution path which was missing (SYN-3018)
  synapse/lib/view.py
  synapse/tests/test_cortex.py
Labels: bug

#2646 Tuplify loadPkgProto output, ensuring doc generation doesn't produce brackets (SYN-3265)
  synapse/tests/files/stormpkg/testpkg.yaml
  synapse/tests/test_tools_autodoc.py
  synapse/tools/genpkg.py
Labels: bug

#2640 Remove _derefGet caching from stormtypes (SYN-3458)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2643 Int - Use str value for valus outside of valid msgpack ranges when raising BadTypeValu (SYN-3354)
  synapse/lib/types.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_types.py
Labels: bug

#2645 raise NotReady exception when a getAhaProxy is called without aha_clients set (SYN-3489)
  synapse/telepath.py
  synapse/tests/test_lib_aha.py
Labels: bug

#2644 Bug - scrape - allow endash when scraping CVE (SYN-3287)
  synapse/lib/chop.py
  synapse/lib/scrape.py
  synapse/models/infotech.py
  synapse/tests/test_lib_chop.py
  synapse/tests/test_lib_scrape.py
  synapse/tests/test_model_infotech.py
Labels: bug

#2650 Update schema validation for stormpkg cmdarg (SYN-3509)
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
Labels: enhancement

#2642 Add advisory locking to the Cell (SYN-3412)
  synapse/exc.py
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#2652 Use replace option in cve type (SYN-3287)
  synapse/lib/chop.py
  synapse/models/infotech.py
Labels: enhancement

#2651 Changelog for v2.91.0
  CHANGELOG.rst
Labels: documentation

#2653 URL Regression Fix (SYN-3514)
  CHANGELOG.rst
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: bug

#2655 Fix ival expansion in a fork (SYN-3442)
  synapse/lib/ast.py
  synapse/tests/test_lib_view.py
Labels: bug

#2658 Bump pytz range
  requirements.txt
  setup.py
Labels: enhancement

#2656 Make getDirSize test more resilient (SYN-3524)
  synapse/tests/test_common.py
Labels: bug

#2632 Support layer wipe by generating node edits (SYN-3438)
  synapse/lib/layer.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_view.py
Labels: enhancement
