Repository vertexproject/synapse, pull requests merged in 2022-02, with the labels that each got.

#2541 Deprecate splice related cmds/apis (SYN-2892)
  synapse/lib/layer.py
  synapse/lib/storm.py
Labels: enhancement

#2542 Allow some AHA bootstrap configs to generate certs
  synapse/lib/aha.py
  synapse/lib/certdir.py
  synapse/tests/test_lib_aha.py
Labels: enhancement

#2545 Update docstrings for some stormtypes (SYN-3158)
  synapse/lib/stormlib/cell.py
  synapse/lib/stormlib/oauth.py
  synapse/lib/stormlib/xml.py
Labels: documentation

#2548 Raise correct exception on parsing invalid time values like 0000-00-00
  synapse/lib/snap.py
  synapse/lib/time.py
  synapse/tests/test_lib_types.py
Labels: bug

#2549 Disable snap buid cache for storm dmons
  synapse/lib/snap.py
  synapse/lib/storm.py
Labels: bug

#2551 Changelog for v2.82.1
  CHANGELOG.rst
Labels: documentation

#2552 Add form/prop to BadTypeValu when raised during node edits
  synapse/lib/snap.py
Labels: enhancement

#2556 Remove antiquated docs on making CoreModule extensions
  docs/synapse/devguides/cortex_quickstart.ipynb
Labels: documentation

#2555 Add .storm extension option to genpkg
  synapse/tests/files/stormpkg/dotstorm/dotstorm.yaml
  synapse/tests/files/stormpkg/dotstorm/storm/commands/dotstorm.bar.storm
  synapse/tests/files/stormpkg/dotstorm/storm/modules/dotstorm.foo.storm
  synapse/tests/test_tools_genpkg.py
  synapse/tools/genpkg.py
Labels: enhancement

#2557 Feat storm lib log (VS-197)
  synapse/cortex.py
  synapse/lib/stormlib/log.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormlib_log.py
  synapse/tests/utils.py
Labels: enhancement

#2558 Changelog for v2.83.0
  CHANGELOG.rst
Labels: documentation

#2559 Cortex.py - replace schedcoro which ran a telepath proxy for the axon with a Telepath client. (SYN-3113)
  synapse/cortex.py
Labels: enhancement

#2560 Add verification for tagprop and array indexes in layers (SYN-3181)
  synapse/lib/layer.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_layer.py
Labels: enhancement

#2562 changelog for v2.84.0
  CHANGELOG.rst
Labels: documentation

#2564 Add a test helper to mock out the certdir singleton behavior (SYN-3214)
  synapse/common.py
  synapse/lib/certdir.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: enhancement

#2566 Do not allow addFormProp to be called twice with the same form+prop (SYN-3171)
  .circleci/config.yml
  synapse/cortex.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_stormlib_modelext.py
Labels: bug

#2569 Clamp macro names to the current maximum allowed value. (SYN-3271)
  synapse/lib/stormlib/macro.py
  synapse/tests/test_lib_stormlib_macro.py
Labels: bug
