Repository vertexproject/synapse, pull requests merged in 2023-05, with the labels that each got.

#3115 Remove deprecated HTTPAPI handler funcs
  CHANGELOG.rst
  synapse/axon.py
  synapse/lib/httpapi.py
Labels: enhancement

#3099 Add a default key to the permdef_schema
  CHANGELOG.rst
  synapse/lib/storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#3116 Changelog updates for 20230501
  CHANGELOG.rst
  synapse/lib/modelrev.py
Labels: documentation

#3117 Remove and archive prop vals which fail migration normalization (SYN-5345)
  CHANGELOG.rst
  synapse/lib/modelrev.py
  synapse/tests/test_lib_modelrev.py
Labels: enhancement

#3118 update fastjsonschema, pytz libraries
  CHANGELOG.rst
  requirements.txt
  setup.py
  synapse/tests/test_cortex.py
Labels: enhancement

#3122 Add support for STIX export configs to specify pivots to include additional nodes (SYN-5280)
  synapse/lib/stormlib/stix.py
  synapse/tests/test_lib_stormlib_stix.py
Labels: enhancement, reqChangelog

#3063 Add highlight context to AST/parser exceptions
  synapse/cmds/cron.py
  synapse/cmds/trigger.py
  synapse/cortex.py
  synapse/datamodel.py
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/lib/view.py
  synapse/tests/files/stormcov/lookup.storm
  synapse/tests/test_cmds_cron.py
  synapse/tests/test_cmds_trigger.py
  synapse/tests/test_cortex.py
  synapse/tests/test_datamodel.py
  synapse/tests/test_exc.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_utils_stormcov.py
  synapse/tools/storm.py
  synapse/utils/stormcov/plugin.py
Labels: enhancement, reqChangelog

#3126 Make sure tools use consistent return codes (SYN-5378)
  synapse/tests/test_tools_cellauth.py
  synapse/tests/test_tools_csvtool.py
  synapse/tests/test_tools_easycert.py
  synapse/tools/cellauth.py
  synapse/tools/csvtool.py
  synapse/tools/easycert.py
Labels: bug, reqChangelog

#3121 Ensure/allow callers to specify iden for adding triggers and dmons (SYN-5334)
  synapse/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3128 Additional layer validation in view schema (SYN-5335)
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3123 Add additional CVSS fields to risk:vuln and depr old ones
  synapse/models/risk.py
  synapse/tests/test_model_risk.py
Labels: enhancement, reqChangelog

#3124 Storm auth command updates (SYN-5240, SYN-5265)
  synapse/lib/stormlib/auth.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormlib_auth.py
Labels: enhancement, reqChangelog

#3025 Initial Python 3.11 Cutover (SYN-4788, SYN-5095, SYN-5308)
  .circleci/config.yml
  CHANGELOG.rst
  docker/bootstrap.sh
  docker/images/aha/Dockerfile
  docker/images/axon/Dockerfile
  docker/images/cortex/Dockerfile
  docker/images/cryotank/Dockerfile
  docker/images/jsonstor/Dockerfile
  docker/images/stemcell/Dockerfile
  docker/images/synapse/Dockerfile
  docker/rmlist.txt
  docs/synapse/devguides/docker.rst
  requirements.txt
  requirements_dev.txt
  setup.py
  synapse/tests/test_lib_link.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: enhancement, documentation

#3130 Correct storm texthash, add docs (SYN-5383, SYN-5388)
  CHANGELOG.rst
  docs/synapse/devguides/storm_api.rst
  synapse/lib/parser.py
  synapse/lib/view.py
  synapse/tests/test_lib_storm.py
Labels: bug, documentation

#3131 Fix view.set() for parents (SYN-5392)
  CHANGELOG.rst
  synapse/lib/view.py
  synapse/tests/test_lib_view.py
Labels: bug

#3133 Add stormcli to synapse.lib.jupyter (SYN-5229)
  docs/synapse/devguides/stormservices.ipynb
  synapse/lib/jupyter.py
  synapse/tests/test_lib_jupyter.py
  synapse/tools/storm.py
Labels: enhancement, documentation

#3127 Add --forms arg to scrape, adjust ftp fang regex (SYN-5266, SYN-5234, SYN-5302)
  synapse/lib/scrape.py
  synapse/lib/storm.py
  synapse/lib/view.py
  synapse/tests/test_lib_scrape.py
  synapse/tests/test_lib_storm.py
Labels: bug, enhancement, reqChangelog

#3138 Some spelling fixes
  synapse/lib/stormtypes.py
Labels: bug, documentation

#3136 Add azure backed axon
  docs/synapse/power_ups.rst
Labels: documentation

#3142 Handle readonly props in copyto (SYN-5313)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#3139 Fix getTypeDef for basic types (SYN-5327)
  synapse/lib/types.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tests/test_lib_types.py
Labels: bug

#3143 Ensure partial backups can be deleted (SYN-5292)
  synapse/tests/test_lib_cell.py
  synapse/tools/backup.py
Labels: bug, reqChangelog

#3144 Changelog for v2.134.0
  CHANGELOG.rst
Labels: documentation

#3145 Move the cell.guid copy into cell.py (SYN-5292)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
  synapse/tools/backup.py
Labels: bug, reqChangelog

#3141 Handle exceptions in Axon line feeder (SYN-5421)
  CHANGELOG.rst
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: bug

#3149 Additional type handling in view/layer set APIs (SYN-5336)
  synapse/lib/layer.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: reqChangelog

#3151 Python 3.11+ Announcement
  CHANGELOG.rst
Labels: documentation

#3153 Fix support for heavy list objects in $lib.min() and $lib.max()
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, reqChangelog

#3135 Add auth.perms.list command and add cortex perms list to admin guide
  docs/synapse/adminguide.rstorm
  synapse/cortex.py
  synapse/lib/stormlib/auth.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormlib_auth.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, documentation

#3154 Move core permdefs into their own init function, ensure the pdefs are validated
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_lib_stormlib_auth.py
Labels: enhancement

#3161 Add time merging for tagprop edits (SYN-5502)
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
Labels: bug

#3162 Update $lib.compression.gzip test
  synapse/tests/test_lib_stormlib_compression.py
Labels: bug

#3094 Prevent zero-length tag lifts, norm tag names more consistently (SYN-5190, SYN-5289)
  CHANGELOG.rst
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
Labels: bug

#3159 Remove trailing . when repr()ing a taxon and lower case bool repr
  synapse/lib/types.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_trigger.py
  synapse/tests/test_lib_types.py
Labels: enhancement

#3165 Fix a missing update to NoSuchForm call
  synapse/lib/stormtypes.py
Labels: bug
