Repository vertexproject/synapse, pull requests merged in 2023-04, with the labels that each got.

#3064 Set link high water mark to one byte
  CHANGELOG.rst
  synapse/lib/link.py
Labels: enhancement

#3062 Add cron start/stop events to beholder queue, resolves SYN-4311
  synapse/lib/agenda.py
  synapse/tests/test_lib_agenda.py
Labels: enhancement, reqChangelog

#3066 Return node:edits for addNode when in the same view (SYN-5171)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, reqChangelog

#3065 Allow deref syntax in formtag lifts, allow formatstring/dollarexpr in varderef (SYN-4495, SYN-4470)
  CHANGELOG.rst
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#3049 Add port to getAhaUrls default urls (SYN-5016)
  CHANGELOG.rst
  synapse/lib/aha.py
  synapse/lib/cell.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_tools_aha.py
  synapse/tools/aha/enroll.py
Labels: bug

#3067 Changelog for v2.127.0
  CHANGELOG.rst
Labels: documentation

#3068 Add view to storm structlog (SYN-5191)
  CHANGELOG.rst
  synapse/cortex.py
  synapse/lib/snap.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
Labels: enhancement

#3069 Fix auth.user.revoke (SYN-5198)
  CHANGELOG.rst
  synapse/lib/stormlib/auth.py
  synapse/tests/test_lib_stormlib_auth.py
Labels: bug

#3070 Preparation for Python 3.11 support (SYN-5095)
  .circleci/config.yml
  CHANGELOG.rst
  docs/synapse/devguides/docker.rst
  requirements.txt
  setup.py
  synapse/telepath.py
  synapse/tests/test_axon.py
  synapse/tests/test_telepath.py
Labels: enhancement

#3056 Model Updates 2023-03-24
  synapse/lib/modelrev.py
  synapse/models/belief.py
  synapse/models/files.py
  synapse/models/geopol.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/risk.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_model_belief.py
  synapse/tests/test_model_geopol.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_risk.py
Labels: enhancement, reqChangelog

#3061 Add copyto command to copy nodes from one view to another
  synapse/cortex.py
  synapse/datamodel.py
  synapse/lib/cell.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, enhancement, reqChangelog

#3081 Update it:semver to handle improperly formatted values (SYN-5104)
  CHANGELOG.rst
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#3079 Add private values to Storm modules (SYN-5149)
  CHANGELOG.rst
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#3078 Add leader status to aha.list output (SYN-4389)
  CHANGELOG.rst
  synapse/tests/test_lib_aha.py
  synapse/tests/test_tools_aha.py
  synapse/tools/aha/list.py
Labels: enhancement

#3073 Thesilence perms
  docs/synapse/adminguide.rst
  docs/synapse/adminguide.rstorm
  docs/synapse/deploymentguide.rst
  docs/synapse/userguides/storm_ref_cmd.rstorm
Labels: documentation, reqChangelog

#3083 fix broken links
  docs/synapse/adminguide.rstorm
Labels: documentation

#3086 Add missing toprim checks on storm rule apis (SYN-5267)
  CHANGELOG.rst
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#3088 Fix non-optimal confirm and prim conversions in storm user objects
  synapse/lib/stormtypes.py
Labels: enhancement

#3089 Docs changelog 202304171600
  CHANGELOG.rst
Labels: documentation

#3093 Fix regex used to validate extended STIX type names
  CHANGELOG.rst
  synapse/lib/stormlib/stix.py
  synapse/tests/test_lib_stormlib_stix.py
Labels: bug

#3095 Add it:host:ext:id prop (SYN-5201)
  CHANGELOG.rst
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#3096 Escape unescaped single quotes in backtick strings (SYN-5285)
  CHANGELOG.rst
  docs/synapse/userguides/storm_ref_intro.rst
  synapse/lib/parser.py
  synapse/tests/test_lib_storm.py
Labels: bug

#3098 Allow deleting props using Storm NodeProps prim (SYN-5206, SYN-5295)
  CHANGELOG.rst
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, enhancement

#3101 Changelog for v2.130.0
  CHANGELOG.rst
Labels: documentation

#3103 Fix docs build (SYN-5300)
  docs/conf.py
  docs/vertex.tpl
  docs/vertex/conf.json
  docs/vertex/index.rst.j2
  requirements.txt
  requirements_doc.txt
  scripts/doctests.py
  setup.py
Labels: bug, documentation

#3104 Address race condition in test_telepath_client_onlink_exc (SYN-5304)
  CHANGELOG.rst
  synapse/tests/test_telepath.py
Labels: bug

#3105 Account for links reconnecting fast (SYN-5304)
  synapse/tests/test_telepath.py
Labels: bug

#3109 Pass proxy argument to axon postfiles in _httpRequest (SYN-5192)
  CHANGELOG.rst
  synapse/lib/stormhttp.py
  synapse/tests/test_axon.py
Labels: bug

#3106 Initialize layer slabs before opening in readonly mode
  CHANGELOG.rst
  synapse/lib/layer.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, enhancement

#3111 Docs - fix search
  CHANGELOG.rst
  docs/conf.py
Labels: bug, documentation

#3108 Add dynamic DNS registration form
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: reqChangelog

#3110 Uniq nodes in multilayer prop lifts (SYN-5174, SYN-5160)
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/tests/test_lib_snap.py
Labels: reqChangelog
