Repository vertexproject/synapse, pull requests merged in 2023-06, with the labels that each got.

#3164 Feat bump requirements
  requirements.txt
  setup.py
  synapse/tests/test_lib_rstorm.py
Labels: enhancement

#3166 changelog for v2.136.0
  CHANGELOG.rst
Labels: documentation

#3160 Add a https:parse:proxy:remoteip option to the base Cell (SYN-4564)
  synapse/lib/cell.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement

#3168 SYN-5470 Implement modulo operator for storm
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3172 Handle SyntaxError which can be raised by cpython in 3.11.4+ (SYN-5563)
  synapse/lib/parser.py
Labels: bug

#3169 Easy model changes from 2023-05-09+ batch
  synapse/lib/layer.py
  synapse/lib/modelrev.py
  synapse/models/base.py
  synapse/models/geopol.py
  synapse/models/geospace.py
  synapse/models/inet.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/risk.py
  synapse/models/transport.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_risk.py
  synapse/tests/test_model_transport.py
Labels: enhancement

#3177 Add a option to disable synapse extension in STIX export (SYN-5429)
  synapse/lib/stormlib/stix.py
  synapse/tests/test_lib_stormlib_stix.py
Labels: enhancement

#3175 Remove whitespace stripping of storm queries (SYN-5441)
  synapse/lib/parser.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_utils_stormcov.py
  synapse/utils/stormcov/plugin.py
Labels: enhancement, reqChangelog

#3178 Changelog for v2.137.0 + misc cleanup
  CHANGELOG.rst
  synapse/lib/stormlib/infosec.py
  synapse/lib/stormtypes.py
  synapse/lib/urlhelp.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_urlhelp.py
Labels: bug, documentation

#3179 Only load files in getSslCtx (SYN-5582)
  synapse/common.py
  synapse/tests/test_common.py
  synapse/tests/utils.py
Labels: enhancement, reqChangelog

#3182 Add CWE to scrape (SYN-5427)
  synapse/lib/scrape.py
  synapse/tests/test_common.py
  synapse/tests/test_lib_scrape.py
Labels: bug, enhancement

#3183 Mark s_common.lockfile() as deprecated (SYN-5591)
  synapse/common.py
Labels: enhancement, reqChangelog

#3184 Fix !export command to use specified view (SYN-5596)
  synapse/tests/test_tools_storm.py
  synapse/tools/storm.py
Labels: bug, reqChangelog

#3181 vectToScore updates
  synapse/lib/stormlib/infosec.py
  synapse/tests/test_lib_stormlib_infosec.py
Labels: bug, enhancement, reqChangelog

#3174 SYN-5544: $lib.print($lib.cast(str, (5.3 / 2))) produces BadTypeValu: no norm for type: <class 'float'>.
  synapse/lib/types.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_types.py
Labels: enhancement, reqChangelog

#3187 Add permissions examples to admin docs
  docs/synapse/adminguide.rstorm
  docs/synapse/userguides/storm_ref_cmd.rstorm
Labels: documentation, reqChangelog

#3180 Make the :sha256 set check resist race conditions
  synapse/models/files.py
Labels: bug, reqChangelog

#3186 optimize graph mode output, use proper scope for lib.pipe, fix cpe auto-extension normalization
  synapse/lib/ast.py
  synapse/lib/snap.py
  synapse/lib/stormtypes.py
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: bug, reqChangelog

#3189 Changelog for v2.139.0
  CHANGELOG.rst
Labels: documentation

#3156 Python 3.11+ support
  .appveyor.yml
  .bumpversion.cfg
  .circleci/config.yml
  .readthedocs.yaml
  MANIFEST.in
  docker/bootstrap.sh
  docker/images/aha/Dockerfile
  docker/images/axon/Dockerfile
  docker/images/cortex/Dockerfile
  docker/images/cryotank/Dockerfile
  docker/images/jsonstor/Dockerfile
  docker/images/stemcell/Dockerfile
  docker/images/synapse/Dockerfile
  docs/synapse/contributing/doc_mastering.ipynb
  docs/synapse/devguides/cortex_quickstart.ipynb
  pyproject.toml
  scripts/replace_commit.py
  scripts/verify_version.py
  setup.py
  synapse/__init__.py
  synapse/tests/test_axon.py
Labels: enhancement, reqChangelog

#3193 Only replace the version commit once during package builds
  .circleci/config.yml
Labels: bug

#3191 Remove common.lockfile (SYN-5592)
  synapse/common.py
  synapse/tests/test_common.py
Labels: enhancement, reqChangelog

#3195 Fix certs path typo in pyproject.toml
  pyproject.toml
Labels: bug

#3199 Require field name in postfiles (SYN-5560)
  synapse/axon.py
  synapse/tests/test_lib_stormhttp.py
Labels: bug

#3163 Mark hashlib.md5() with useforsecurity=False (SYN-5503)
  synapse/common.py
  synapse/lib/ast.py
  synapse/lib/hashset.py
  synapse/lib/parser.py
  synapse/lib/stormlib/hashes.py
  synapse/lib/view.py
  synapse/models/files.py
  synapse/models/inet.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_crypto_tinfoil.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_tools_feed.py
  synapse/tests/utils.py
Labels: enhancement, reqChangelog

#3203 Catch divide by zero exceptions (SYN-5566)
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: bug, reqChangelog

#3198 getTotalMemory() - skip cgroupsv1 max memory.limit_in_bytes (SYN-4433)
  synapse/lib/platforms/linux.py
Labels: bug

#3201 Validate cron query on add (SYN-5364)
  synapse/lib/agenda.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
Labels: bug, reqChangelog

#3200 Add missing docstring, fix onboot:optimize docstring.
  synapse/lib/cell.py
  synapse/lib/stormlib/iters.py
Labels: bug

#3207 IPv6 cmprs, diff readonly, lib.cron.add/mod toprim, strip space and : from hex types, truncate times with unused precision
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/types.py
  synapse/models/inet.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_time.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_inet.py
Labels: bug, enhancement, reqChangelog

#3206 Handle invalid multipart fields which don't use the Axon (SYN-5724)
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: bug, reqChangelog

#3202 Add file:archive:entry to model archive file contents
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: enhancement, reqChangelog

#3205 Add new beholder message to track when a service gets connected, helps resolve OP-2570
  synapse/cortex.py
  synapse/lib/stormsvc.py
  synapse/tests/test_cortex.py
Labels: enhancement, reqChangelog

#3210 Add whitespace/colon removal to s_chop.hexstr
  synapse/lib/chop.py
  synapse/lib/types.py
Labels: bug

#3209 changelog for 2.140.0
  CHANGELOG.rst
Labels: documentation
