Repository vertexproject/synapse, pull requests merged in 2023-12, with the labels that each got.

#3451 SYN-6407: storm for loop docs talk about the example using a subquery but it doesn't
  docs/synapse/userguides/storm_adv_control.rstorm
Labels: bug, documentation, reqChangelog

#3449 Remove APIs marked for deprecation after 2023 10 01
  docs/synapse/userguides/storm_ref_cmd.rstorm
  docs/synapse/userguides/syn_tools_feed.rst
  synapse/cmds/cortex.py
  synapse/cmds/cron.py
  synapse/cmds/trigger.py
  synapse/common.py
  synapse/cortex.py
  synapse/lib/cmdr.py
  synapse/lib/httpapi.py
  synapse/lib/layer.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/view.py
  synapse/models/syn.py
  synapse/tests/test_cmds_cortex.py
  synapse/tests/test_cmds_cron.py
  synapse/tests/test_cmds_trigger.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_view.py
  synapse/tests/test_model_person.py
  synapse/tests/test_model_syn.py
  synapse/tests/test_tools_csvtool.py
  synapse/tests/test_tools_feed.py
  synapse/tools/csvtool.py
Labels: enhancement, reqChangelog

#3447 Add risk:vuln:ext:id property (SYN-5667)
  synapse/models/risk.py
  synapse/tests/test_model_risk.py
Labels: enhancement, reqChangelog

#3448 SYN-6495: lib.storm.eval to log its arg
  synapse/lib/stormlib/storm.py
  synapse/tests/test_lib_stormlib_storm.py
Labels: enhancement, reqChangelog

#3459 Handle invalid CIDR masks in IPv4 norm (SYN-6623)
  CHANGELOG.rst
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: bug, model

#3319 SYN-5887: Vaults
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/schemas.py
  synapse/lib/stormlib/easyperm.py
  synapse/lib/stormlib/graph.py
  synapse/lib/stormlib/vault.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormlib_easyperm.py
  synapse/tests/test_lib_stormlib_vault.py
Labels: enhancement, reqChangelog

#3461 SYN-6604: vault API to replace configs/secrets
  synapse/cortex.py
  synapse/lib/stormlib/vault.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormlib_vault.py
Labels: enhancement

#3464 Remove usage of snap.py in majority of unit tests (SYN-2288)
  synapse/lib/node.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_layer.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_node.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_types.py
  synapse/tests/test_model_base.py
  synapse/tests/test_model_crypto.py
  synapse/tests/test_model_dns.py
  synapse/tests/test_model_files.py
  synapse/tests/test_model_geospace.py
  synapse/tests/test_model_gov_cn.py
  synapse/tests/test_model_gov_intl.py
  synapse/tests/test_model_gov_us.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_language.py
  synapse/tests/test_model_material.py
  synapse/tests/test_model_media.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_person.py
  synapse/tests/test_model_syn.py
  synapse/tests/test_model_telco.py
  synapse/tests/utils.py
Labels: enhancement, reqChangelog

#3465 Move $lib.auth related classes to lib/stormlibs/auth.py (SYN-792)
  synapse/lib/stormlib/auth.py
  synapse/lib/stormlib/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormlib_auth.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#3460 SYN-6353: cron status changes through nexus
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/schemas.py
  synapse/tests/test_lib_agenda.py
Labels: enhancement, reqChangelog

#3443 Mark vars from parent runtimes runtsafe in subruntimes (SYN-6543, SYN-6554)
  synapse/lib/ast.py
  synapse/lib/storm.py
  synapse/lib/stormlib/cell.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormtypes.py
  synapse/tests/files/stix_export/basic.json
  synapse/tests/files/stix_export/custom0.json
  synapse/tests/test_lib_ast.py
Labels: bug, enhancement, reqChangelog

#3353 AHA service pools
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/aha.py
  synapse/lib/cell.py
  synapse/lib/hiveauth.py
  synapse/lib/schemas.py
  synapse/lib/storm.py
  synapse/lib/stormlib/aha.py
  synapse/lib/stormtypes.py
  synapse/telepath.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_hiveauth.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_telepath.py
Labels: enhancement, reqChangelog

#3470 HTTP API Key support (SYN-4201)
  docs/synapse/httpapi.rst
  docs/synapse/userguides/syn_tools_feed.rst
  synapse/lib/cell.py
  synapse/lib/crypto/passwd.py
  synapse/lib/hiveauth.py
  synapse/lib/httpapi.py
  synapse/lib/schemas.py
  synapse/lib/stormlib/auth.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_crypto_passwd.py
  synapse/tests/test_lib_stormlib_auth.py
Labels: enhancement, reqChangelog

#3477 Bug: Apply telepath client opts to the urlinfo before calling openinfo() (SYN-6671)
  synapse/telepath.py
Labels: bug, reqChangelog

#3476 Changelog for v2.157.0
  CHANGELOG.rst
Labels: documentation
