Repository vertexproject/synapse, pull requests merged in 2023-10, with the labels that each got.

#3354 SYN-6169: Manually setting parent does not include nested layers in reparented view
  synapse/lib/view.py
  synapse/tests/test_cortex.py
Labels: bug, reqChangelog

#3355 Updates for Python 3.12 compatibility (SYN-6184)
  synapse/cmds/cron.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormtypes.py
  synapse/tests/test_common.py
  synapse/tests/test_lib_link.py
  synapse/tests/test_lib_multislabseqn.py
  synapse/tests/test_lib_storm.py
Labels: enhancement, reqChangelog

#3350 Add Axon HTTP APIs to the Cortex (SYN-6139)
  docs/synapse/httpapi.rst
  synapse/cortex.py
  synapse/lib/stormtypes.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3363 Add status attributes to user/role CUD operations (SYN-6049)
  synapse/lib/cell.py
Labels: enhancement, reqChangelog

#3362 Add SYN_LOG_DATEFMT for logging (SYN-6217)
  docs/synapse/devopsguide.rst
  synapse/common.py
  synapse/tests/test_lib_structlog.py
Labels: enhancement, reqChangelog

#3369 note.add command set :updated prop. resolves SYN-6285
  synapse/lib/storm.py
  synapse/tests/test_model_base.py
Labels: enhancement, reqChangelog

#3368 Changelog for v2.151.0
  CHANGELOG.rst
Labels: documentation

#3356 Update getLogExtra behavior to prefer a user key (SYN-6047)
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
Labels: enhancement, reqChangelog

#3372 Update package-data to account for changes in #3361
  pyproject.toml
Labels: bug

#3367 Fix test_link_fromspawns race condition under load
  synapse/tests/test_lib_link.py
Labels: bug

#3374 Updates for 2.151.0
  CHANGELOG.rst
Labels: documentation

#3341 Model repo labels more concretely
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement, reqChangelog

#3378 SYN-6270: Scrape error in file path validation
  synapse/lib/scrape.py
  synapse/tests/test_lib_scrape.py
Labels: bug, reqChangelog

#3360 Add `edge:add` and `edge:del` as trigger conditions, resolves SYN-5974
  docs/synapse/userguides/storm_ref_automation.rstorm
  synapse/lib/cache.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/trigger.py
  synapse/lib/view.py
  synapse/models/syn.py
  synapse/tests/test_lib_trigger.py
Labels: enhancement, reqChangelog

#3371 synapse.tools.aha.list - check if service is an aha cell (SYN-6187)
  synapse/tests/test_tools_aha.py
  synapse/tools/aha/list.py
Labels: enhancement, reqChangelog

#3388 Revert "Add `edge:add` and `edge:del` as trigger conditions, resolves SYN-5974 (#3360)"
  docs/synapse/userguides/storm_ref_automation.rstorm
  synapse/lib/cache.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/lib/trigger.py
  synapse/lib/view.py
  synapse/models/syn.py
  synapse/tests/test_lib_trigger.py
Labels: enhancement

#3390 Changelog for v2.152.0
  CHANGELOG.rst
  synapse/datamodel.py
Labels: documentation

#3373 Raise an error when attempting to filter by wildcard tag/tagprop with value (SYN-6198)
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
Labels: bug, reqChangelog

#3399 Pin pyopenssl down to avoid v23.3.0 API changes
  pyproject.toml
  requirements.txt
Labels: bug

#3400 Doc changelog 20231026
  CHANGELOG.rst
  synapse/tests/test_axon.py
Labels: documentation

#3366 Storm Extended HTTP API (SYN-4803)
  docs/synapse/devopsguide.rst
  docs/synapse/httpapi.rst
  docs/synapse/userguides/storm_ref_cmd.rstorm
  scripts/testrunner.sh
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/cell.py
  synapse/lib/httpapi.py
  synapse/lib/schemas.py
  synapse/lib/storm.py
  synapse/lib/stormlib/cortex.py
  synapse/lib/stormlib/infosec.py
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormlib_cortex.py
Labels: enhancement, documentation, reqChangelog

#3397 SYN-6134: storm http proxy setting permission gated
  synapse/exc.py
  synapse/lib/stormhttp.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement, reqChangelog

#3401 Final changelog for v2.153.0
  CHANGELOG.rst
  synapse/lib/storm.py
Labels: documentation
