Repository vertexproject/synapse, pull requests merged in 2023-03, with the labels that each got.

#3031 thesilence glossary updates
  docs/synapse/glossary.rst
Labels: documentation

#2937 synapse.tools.storm: add support for specifying a view
  synapse/tests/test_tools_storm.py
  synapse/tools/storm.py
Labels: enhancement

#3021 synapse.lib.scope updates
  synapse/lib/base.py
  synapse/lib/scope.py
  synapse/tests/test_lib_base.py
  synapse/tests/test_lib_scope.py
Labels: bug, enhancement, reqChangelog

#3035 login and authdeny consistency (SYN-4870)
  CHANGELOG.rst
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/hive.py
  synapse/lib/hiveauth.py
  synapse/lib/storm.py
  synapse/lib/stormlib/cell.py
  synapse/lib/stormlib/notifications.py
  synapse/lib/stormlib/oauth.py
  synapse/lib/stormlib/project.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, enhancement

#3039 Changelog updates for v2.124.0
  CHANGELOG.rst
Labels: documentation

#3041 Add uplink status to cellinfo (SYN-4992)
  CHANGELOG.rst
  synapse/lib/cell.py
  synapse/lib/nexus.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#3042 Disable total timeout for restore via SYN_RESTORE_HTTPS_URL (SYN-5042)
  CHANGELOG.rst
  synapse/lib/cell.py
Labels: bug

#3044 HTTP Proxy tests
  CHANGELOG.rst
  requirements.txt
  setup.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#3045 Docs changelog 20230313
  CHANGELOG.rst
Labels: documentation

#3046 tostr() lib.time.parse value (SYN-4651)
  CHANGELOG.rst
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#3048 Add commercial offering text and streamline power-up docs to allow the list to be automatically generated
  docs/synapse/power_ups.rst
  docs/synapse/power_ups/advanced_power_ups.rst
  docs/synapse/power_ups/rapid_power_ups.rst
  docs/synapse/user_interface.rst
Labels: documentation

#2923 Additional Storm auth tools
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/storm.py
  synapse/lib/stormlib/auth.py
  synapse/lib/stormlib/iters.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_stormlib_auth.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/utils.py
Labels: enhancement

#3047 Add kubernetes examples (SYN-3357, SYN-4322)
  docs/_static/css/theme_overrides.css
  docs/conf.py
  docs/synapse/deploymentguide.rst
  docs/synapse/devopsguide.rst
  docs/synapse/kubernetes/aha.yaml
  docs/synapse/kubernetes/axon.yaml
  docs/synapse/kubernetes/cortex.yaml
  docs/synapse/kubernetes/jsonstor.yaml
  docs/synapse/kubernetes/optic.yaml
  docs/synapse/kubernetes/sysctl.yaml
  synapse/lib/aha.py
Labels: documentation

#3054 Additional Storm auth commands (SYN-5088)
  CHANGELOG.rst
  synapse/lib/stormlib/auth.py
  synapse/tests/test_lib_stormlib_auth.py
Labels: enhancement

#3051 Docs - Intro / Getting Started update
  docs/synapse/intro.rst
  docs/synapse/quickstart.rst
Labels: documentation

#3058 Add optional flag for Storm package dependencies (SYN-5012)
  CHANGELOG.rst
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#3060 Fix for view.addNode() Storm API perms and return value
  CHANGELOG.rst
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug
