Repository vertexproject/synapse, pull requests merged in 2023-07, with the labels that each got.

#3215 Fix TypeError when passing a Number to $lib.math.number (SYN-5571)
  synapse/lib/stormlib/math.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug, reqChangelog

#3216 Update backup space checks (SYN-5545)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: bug, reqChangelog

#3217 Increase test_storm_svcs timeouts
  synapse/tests/test_lib_stormsvc.py
Labels: bug

#3218 Prevent yield from operating on nodes which did not come from the current view. (SYN-5679)
  synapse/lib/ast.py
  synapse/tests/test_lib_storm.py
Labels: bug, reqChangelog

#3220 Remove mirror config from cell.mods.yaml during _bootProvConf (SYN-5755)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: bug

#3222 changelog for v2.141.0
  CHANGELOG.rst
Labels: documentation

#3033 Create general use proc pool (SYN-4901)
  synapse/lib/coro.py
  synapse/lib/parser.py
  synapse/lib/stormlib/json.py
  synapse/lib/stormlib/mime.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormlib/xml.py
  synapse/tests/test_lib_coro.py
  synapse/tests/test_lib_stormlib_stix.py
  synapse/tests/test_lib_stormlib_xml.py
  synapse/tests/utils.py
Labels: enhancement, reqChangelog

#3226 Clarify that $lib.math.number is not for converting a str to int (SYN-5571)
  synapse/lib/stormlib/math.py
Labels: enhancement, documentation

#3224 SYN-5701: CVSS norm doesn't handle unordered vectors
  synapse/lib/chop.py
  synapse/lib/modelrev.py
  synapse/models/risk.py
  synapse/tests/test_lib_chop.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_model_risk.py
Labels: bug, enhancement, reqChangelog

#3227 Model additions from discussion (20230710)
  synapse/lib/modelrev.py
  synapse/models/infotech.py
  synapse/models/orgs.py
  synapse/models/risk.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#3223 SYN-5600: Removing extended form does not properly remove all the props
  synapse/datamodel.py
  synapse/tests/test_datamodel.py
  synapse/tests/test_lib_stormlib_modelext.py
Labels: bug, reqChangelog

#3228 Add more beholder messages for notifying about extended model props, part of OP-2554
  synapse/cortex.py
  synapse/tests/test_lib_stormlib_modelext.py
Labels: enhancement, reqChangelog

#3196 Add byo pki cosign support to docker image builds
  .circleci/config.yml
  docker/build_all.sh
  docker/build_image.sh
  docker/scripts/copy_all.sh
  docker/scripts/push_all.sh
  docker/scripts/save_all.sh
  docs/synapse/devguides/docker.rst
  synapse/tests/test_tools_docker_validate.py
  synapse/tools/docker/__init__.py
  synapse/tools/docker/validate.py
Labels: enhancement, reqChangelog

#3237 SYN-5721: optionally specify 0pad bool to hex type to allow 0 ljust
  synapse/lib/types.py
  synapse/tests/test_lib_types.py
  synapse/tests/utils.py
Labels: enhancement

#3242 Add a .title() method to str (SYN-5795)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3246 Docker build: Install pyyaml with an available musl wheel to avoid issue with pyyaml + cython 3.0
  .circleci/config.yml
Labels: bug

#3240 Remove mirror config from cell.yaml during _bootProvConf (SYN-5777)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: bug, reqChangelog

#3238 AHA HTTP endpoint for services (SYN-5742)
  docs/synapse/httpapi.rst
  synapse/lib/aha.py
  synapse/tests/test_lib_aha.py
Labels: enhancement

#3239 Add option to use a semaphore when submitting jobs to the forkpool (SYN-5716)
  synapse/lib/coro.py
  synapse/lib/stormlib/json.py
  synapse/lib/stormlib/mime.py
  synapse/lib/stormlib/stix.py
  synapse/lib/stormlib/xml.py
  synapse/tests/test_lib_coro.py
Labels: enhancement, reqChangelog

#3241 changelog for v2.142.0
  CHANGELOG.rst
  docs/synapse/devguides/docker.rst
Labels: documentation

#3248 Fix for missing floating tags for container releases
  .circleci/config.yml
  CHANGELOG.rst
Labels: bug

#3249 Feat docker disable build cache
  docker/build_all.sh
  docker/build_image.sh
Labels: bug

#3204 Update vcrpy dep to include 4.4.0
  pyproject.toml
  requirements.txt
Labels: enhancement, reqChangelog

#3247 Add view iden into storm task info (SYN-5743)
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/httpapi.py
  synapse/lib/storm.py
  synapse/lib/view.py
  synapse/tests/test_cmds_boss.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_storm.py
Labels: enhancement, reqChangelog

#3100 Stormlib type introspection (SYN-2367)
  synapse/lib/stormtypes.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3253 SYN-5719: startup check for unpopulated depr props which are not locked
  synapse/cortex.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tests/utils.py
Labels: enhancement, reqChangelog

#3252 Add $lib.model.ext.getExtModel and $lib.model.ext.addExtModel APIS (SYN-5228)
  synapse/cortex.py
  synapse/lib/stormlib/modelext.py
  synapse/tests/test_lib_stormlib_modelext.py
Labels: enhancement, reqChangelog

#3260 Update synapse.tools.aha.enroll to work with a list of aha servers (SYN-5841)
  synapse/tests/test_tools_aha.py
  synapse/tools/aha/enroll.py
Labels: bug

#3250 Prevent emitter functions from leaving sub-runtimes behind (SYN-5819)
  synapse/lib/ast.py
  synapse/lib/coro.py
  synapse/tests/test_lib_ast.py
Labels: bug, reqChangelog

#3097 Raise StormRuntimeError for invalid Storm funccalls (SYN-5261)
  synapse/lib/ast.py
  synapse/tests/test_lib_ast.py
Labels: bug, reqChangelog

#3258 Update preboot.sh example (SYN-5834)
  docs/synapse/devguides/certbot.sh
Labels: documentation

#3236 Add performance sysctls to $lib.cell.getSystemInfo (SYN-5702)
  synapse/lib/cell.py
  synapse/lib/platforms/linux.py
  synapse/tests/test_lib_platforms_linux.py
Labels: enhancement, reqChangelog

#3254 Storm functions
  docs/synapse/glossary.rst
  docs/synapse/userguides/index_storm_adv.rst
  docs/synapse/userguides/storm_adv_control.rstorm
  docs/synapse/userguides/storm_adv_functions.rstorm
  docs/synapse/userguides/storm_adv_methods.rstorm
  docs/synapse/userguides/storm_adv_vars.rstorm
  docs/synapse/userguides/storm_ref_automation.rstorm
  docs/synapse/userguides/storm_ref_intro.rst
Labels: documentation, reqChangelog

#3261 Add $lib.pack.en() and $lib.pack.un() for packing/unpacking structured bytes (SYN-5865)
  synapse/cortex.py
  synapse/lib/stormlib/pack.py
  synapse/tests/test_lib_stormlib_pack.py
Labels: enhancement, reqChangelog

#3267 Add note about mirror=true for AHA URLs (SYN-5535)
  docs/synapse/devopsguide.rst
Labels: documentation, reqChangelog

#3268 $lib.gen functions use stable guid generation
  synapse/lib/stormlib/gen.py
  synapse/tests/test_lib_stormlib_gen.py
Labels: enhancement, reqChangelog

#3270 Changelog for v2.143.0
  CHANGELOG.rst
Labels: documentation

#3275 Changelog v2.143.0 fixes
  CHANGELOG.rst
Labels: documentation

#3273 Address flaky mirror test (SYN-5835)
  synapse/tests/test_lib_stormsvc.py
Labels: bug

#3277 Fix E721 violations from pycodestyle 2.11.0
  synapse/lib/types.py
  synapse/models/inet.py
Labels: enhancement

#3276 SYN-5827: inet:dns:answer:time
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: enhancement, reqChangelog

#3278 SYN-5823: Update cert filenames in docs
  docs/synapse/devopsguide.rst
Labels: bug, documentation

#3257 `it:dev:repo` model elements
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement, reqChangelog
