Repository vertexproject/synapse, pull requests merged in 2023-01, with the labels that each got.

#2963 Do not allow pkg.add to mutate packages (SYN-4546)
  synapse/lib/storm.py
Labels: bug

#2964 Make getStormMod return a copy of mdef (SYN-4549)
  synapse/cortex.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#2960 Remove existing Kubernetes examples pending their rewrite.
  docs/synapse/devguides/demo-aha-onepod.yaml
  docs/synapse/devguides/demo-aha-pods.yaml
  docs/synapse/devopsguide.rst
Labels: documentation

#2972 Update CRL to Revoke Code Signer 00
  synapse/data/certs/crls/The Vertex Project Intermediate CA 00.crl
Labels: enhancement

#2931 Biz model additions
  synapse/models/biz.py
  synapse/models/economic.py
  synapse/models/inet.py
  synapse/models/orgs.py
  synapse/models/risk.py
  synapse/tests/test_model_biz.py
  synapse/tests/test_model_economic.py
Labels: enhancement

#2920 Set cell to read-only on low disk space (SYN-4339)
  docs/synapse/devopsguide.rst
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/cell.py
  synapse/lib/nexus.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#2976 Docs changelog 20230109
  CHANGELOG.rst
Labels: documentation

#2977 CLI - handle being unable to access histfile (SYN-4577)
  synapse/lib/cli.py
Labels: bug

#2979 Fix beholder test under replay
  synapse/tests/test_cortex.py
Labels: enhancement

#2978 Small risk model additions 2023-01-11
  synapse/models/risk.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#2980 Changelog v2.120.0
  CHANGELOG.rst
Labels: documentation

#2981 Correct the provenance API deprecation notice and API call, bump it to v2.122.0
  CHANGELOG.rst
  synapse/cortex.py
Labels: bug

#2968 Update user vars docs
  docs/synapse/userguides/storm_adv_vars.rstorm
  docs/synapse/userguides/syn_tools_csvtool.rst
Labels: documentation

#2973 Implement extended permissions for macros (SYN-4544, SYN-942, SYN-4440, OP-1126)
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/hive.py
  synapse/lib/stormlib/macro.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_stormlib_macro.py
Labels: enhancement

#2982 inet model bugfixes (SYN-4552, SYN-4561)
  synapse/models/dns.py
  synapse/models/inet.py
  synapse/tests/test_lib_snap.py
  synapse/tests/test_model_dns.py
  synapse/tests/test_model_inet.py
  synapse/tests/utils.py
Labels: bug

#2983 Add mailgun config to release setup (SYN-4605)
  .circleci/config.yml
  setup.cfg
Labels: enhancement

#2988 Skip nodes which no longer exist when diffing a fork (SYN-4526)
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2990 Verify disk space before starting backups (SYN-4578)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#2991 Changelog for v2.121.0
  CHANGELOG.rst
Labels: documentation

#2993 Fix macro creator when creating macros (SYN-4668)
  synapse/cortex.py
  synapse/tests/test_lib_stormlib_macro.py
Labels: bug

#2994 Update changelog for v2.121.1
  CHANGELOG.rst
Labels: documentation

#2962 python 3.10 cutover (SYN-3525)
  .circleci/config.yml
  CHANGELOG.rst
  docker/images/aha/Dockerfile
  docker/images/axon/Dockerfile
  docker/images/cortex/Dockerfile
  docker/images/cryotank/Dockerfile
  docker/images/jsonstor/Dockerfile
  docker/images/stemcell/Dockerfile
  docker/images/synapse/Dockerfile
  setup.py
  synapse/__init__.py
Labels: enhancement, documentation

#2997 Remove x-xss-protection header from default headers in httpapi (SYN-4641)
  synapse/lib/httpapi.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement

#2992 Thesilence misc docs
  docs/synapse/glossary.rst
  docs/synapse/userguides/storm_ref_cmd.rstorm
  docs/synapse/userguides/storm_ref_data_mod.rstorm
  docs/synapse/userguides/storm_ref_filter.rstorm
  docs/synapse/userguides/storm_ref_type_specific.rstorm
Labels: documentation

#3000 Catch more file:bytes norm errors (SYN-4766)
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: bug

#2999 Changelog for v2.122.0
  CHANGELOG.rst
Labels: documentation
