Repository vertexproject/synapse, pull requests merged in 2023-08, with the labels that each got.

#3279 SYN-5812: storm dmons to start AFTER model migrations
  synapse/cortex.py
  synapse/tests/test_cortex.py
Labels: bug

#3281 update allowed cryptography package
  pyproject.toml
  requirements.txt
Labels: enhancement

#3280 Storm $lib.inet.http updates (SYN-5792, SYN-5730)
  synapse/axon.py
  synapse/common.py
  synapse/lib/stormhttp.py
  synapse/lib/stormtypes.py
  synapse/tests/test_axon.py
  synapse/tests/test_lib_stormhttp.py
Labels: bug, enhancement

#3235 Log agenda iden in storm structlog (SYN-5689)
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/snap.py
  synapse/lib/view.py
Labels: enhancement, reqChangelog

#3282 Tweaks to once command and docs
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug, documentation, reqChangelog

#3283 Changelog for v2.144.0
  CHANGELOG.rst
Labels: documentation

#3286 Fix error in perms doc
  docs/synapse/adminguide.rstorm
Labels: documentation

#3288 draft - adding type int
  docs/synapse/userguides/storm_ref_type_specific.rstorm
Labels: documentation

#3297 Bug: test SchemaCell should not override confbase
  synapse/lib/cell.py
  synapse/tests/test_lib_config.py
Labels: bug

#3295 SYN-5870: optional user count limits to account for locked/archived users
  synapse/lib/cell.py
  synapse/lib/hiveauth.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_config.py
Labels: enhancement, reqChangelog

#3296 Cleanup Stormlib autodoc syntax (SYN-5932)
  synapse/lib/autodoc.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_autodoc.py
  synapse/tests/utils.py
Labels: bug, enhancement, documentation, reqChangelog

#3293 Cell reload / SIGHUP handler (SYN-5886)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_tools_reload.py
  synapse/tests/utils.py
  synapse/tools/reload.py
Labels: enhancement, reqChangelog

#3302 Adds n1+n2 indexing for edges. Needed for graph projection to cut down edges.
  synapse/lib/layer.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/tests/test_lib_layer.py
Labels: enhancement, reqChangelog

#3306 Replace synaspe.common.aclosing with contextlib.aclosing
  synapse/common.py
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
Labels: enhancement, reqChangelog

#3308 Docs design cleanup
  CHANGELOG.rst
  docs/conf.py
  docs/synapse/changelog.rst
  docs/synapse/devopsguide.rst
  docs/synapse/stormtypes.rst
  docs/synapse/userguides/storm_adv_functions.rstorm
  docs/synapse/userguides/storm_ref_type_specific.rstorm
Labels: bug, documentation

#3307 Tweak s_common.wait_for implementation
  synapse/common.py
  synapse/tests/test_common.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_telepath.py
Labels: bug, reqChangelog

#3266 Add reverse lift syntax to Storm (SYN-5290, SYN-5833)
  synapse/cortex.py
  synapse/lib/ast.py
  synapse/lib/layer.py
  synapse/lib/parser.py
  synapse/lib/snap.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_grammar.py
Labels: enhancement

#3309 Add a meta:note prop for updated time, resolves SYN-5979
  synapse/models/base.py
  synapse/tests/test_model_base.py
Labels: enhancement, reqChangelog

#3303 Synapse User Guide revisions
  CHANGELOG.rst
  docs/conf.py
  docs/synapse/adminguide.rstorm
  docs/synapse/changelog.rst
  docs/synapse/devopsguide.rst
  docs/synapse/stormtypes.rst
  docs/synapse/userguide.rst
  docs/synapse/userguides/analytical_model.rstorm
  docs/synapse/userguides/analytical_model_tags.rstorm
  docs/synapse/userguides/analytical_model_tags_analysis.rst
  docs/synapse/userguides/background.rst
  docs/synapse/userguides/bkd_graphs_hypergraphs.rst
  docs/synapse/userguides/bkd_why_synapse.rst
  docs/synapse/userguides/data_model.rstorm
  docs/synapse/userguides/data_model_form_categories.rst
  docs/synapse/userguides/data_model_object_categories.rstorm
  docs/synapse/userguides/data_model_terms.rstorm
  docs/synapse/userguides/design_analytical_model.rst
  docs/synapse/userguides/design_data_model.rst
  docs/synapse/userguides/design_forms_vs_tags.rst
  docs/synapse/userguides/index_analytical.rst
  docs/synapse/userguides/index_bkd.rst
  docs/synapse/userguides/index_datamodel.rst
  docs/synapse/userguides/index_design.rst
  docs/synapse/userguides/storm_adv_functions.rstorm
  docs/synapse/userguides/storm_ref_pivot.rstorm
  docs/synapse/userguides/storm_ref_type_specific.rstorm
  docs/synapse/userguides/views_layers.rst
Labels: documentation, reqChangelog

#3292 Deprecation Deadline 2023-10-01
  CHANGELOG.rst
  synapse/cmds/cron.py
  synapse/cmds/trigger.py
  synapse/common.py
  synapse/cortex.py
  synapse/lib/httpapi.py
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/lib/view.py
  synapse/tests/test_lib_storm.py
Labels: enhancement, documentation, reqChangelog

#3311 Simplify IPv6 scrape regex and validate matches (SYN-6006)
  synapse/lib/scrape.py
  synapse/tests/test_lib_scrape.py
Labels: bug

#3310 Deprecate :registrant from inet:whois:iprec in favor of the :contacts array
  synapse/models/inet.py
Labels: enhancement

#3312 Changelog for v2.145.0
  CHANGELOG.rst
Labels: documentation

#3313 BUG: Tweak readonly layer handling for migrations
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/modelrev.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_layer.py
Labels: bug, reqChangelog

#3315 Update node.py helper functions (SYN-5998)
  synapse/lib/node.py
  synapse/tests/test_lib_node.py
Labels: bug, reqChangelog

#3317 Changelog for v2.146.0
  CHANGELOG.rst
Labels: documentation

#3318 Expose search charset in imap.search (SYN-6079)
  synapse/lib/stormlib/imap.py
  synapse/tests/test_lib_stormlib_imap.py
Labels: enhancement, reqChangelog

#3321 Pull in asyncio.timeout implementation from Python 3.11.3 (SYN-6087)
  synapse/common.py
Labels: enhancement

#3323 Changelog for v2.147.0
  CHANGELOG.rst
Labels: documentation

#3322 Add $lib.jsonstor.cachedel (SYN-6091)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3324 Fini cell.ahaclient if the Cell creates it (SYN-6101)
  synapse/lib/cell.py
  synapse/tests/test_lib_aha.py
Labels: bug
