Repository vertexproject/synapse, pull requests merged in 2023-02, with the labels that each got.

#3003 Docs tweaks 20230201
  docs/synapse/deploymentguide.rst
  docs/synapse/devopsguide.rst
  synapse/models/transport.py
Labels: bug, documentation

#2998 Cleanup most of the direct cell.auth refs in httpapi (SYN-4671)
  synapse/lib/cell.py
  synapse/lib/httpapi.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement

#3006 Clarify desync error message (SYN-4638)
  synapse/lib/nexus.py
  synapse/tests/test_cortex.py
Labels: enhancement

#3005 Clean up read-only props in datamodel (SYN-4663)
  synapse/models/dns.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#3012 Bug: Storm tree command did not use tostr() (SYN-4898)
  CHANGELOG.rst
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#2961 Coverage plugin for storm files (SYN-4840)
  CHANGELOG.rst
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/tests/files/stormcov/argvquery.storm
  synapse/tests/files/stormcov/dupesubs.storm
  synapse/tests/files/stormcov/lookup.storm
  synapse/tests/files/stormcov/pivot.storm
  synapse/tests/files/stormcov/spin.storm
  synapse/tests/files/stormcov/stormctrl.storm
  synapse/tests/test_tools_storm.py
  synapse/tests/test_utils_stormcov.py
  synapse/utils/__init__.py
  synapse/utils/stormcov/__init__.py
  synapse/utils/stormcov/plugin.py
Labels: enhancement

#3010 Set copyright year to current year (SYN-4878)
  CHANGELOG.rst
  docs/conf.py
Labels: bug, documentation

#3009 Ensure BadTypeValu errors during time normalization include the input text (SYN-4785)
  CHANGELOG.rst
  synapse/lib/time.py
  synapse/lib/types.py
Labels: bug

#3013 Fix risk:vuln:cvss:av enum (SYN-4897)
  CHANGELOG.rst
  synapse/lib/modelrev.py
  synapse/models/risk.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_lib_stormlib_infosec.py
Labels: bug

#3011 Axon and Storm wget improvements (SYN-4675)
  CHANGELOG.rst
  docs/synapse/httpapi.rst
  synapse/axon.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_storm.py
  synapse/tests/utils.py
Labels: bug, enhancement

#3017 Add :updated to media:news, fix ismax=True (SYN-4771, SYN-4924)
  CHANGELOG.rst
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/lib/types.py
  synapse/models/media.py
  synapse/models/proj.py
  synapse/tests/test_model_media.py
Labels: bug, enhancement

#3018 Allow specifying a value to uniq based on (SYN-4850)
  CHANGELOG.rst
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#3014 Update changelog for existing items merged into master.
  CHANGELOG.rst
Labels: documentation

#3019 Support choices in Storm command arguments (SYN-4673)
  CHANGELOG.rst
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#3020 Adjust Storm grammar to allow funccalls when specifying tagprops (SYN-4940)
  CHANGELOG.rst
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
Labels: bug

#3016 Add free space checks on slab expansion (SYN-4615)
  CHANGELOG.rst
  synapse/cortex.py
  synapse/lib/aha.py
  synapse/lib/ast.py
  synapse/lib/cell.py
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/lib/multislabseqn.py
  synapse/lib/nexus.py
  synapse/lib/snap.py
  synapse/lib/spooled.py
  synapse/lib/storm.py
  synapse/lib/stormlib/scrape.py
  synapse/lib/view.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#3007 Update HTTP Handler to primarily be useriden driven, add user logging to requests (SYN-4602)
  CHANGELOG.rst
  docs/synapse/devguides/storm_api.rst
  synapse/axon.py
  synapse/lib/cell.py
  synapse/lib/httpapi.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement

#3023 Add HTTP status code lookup to Storm (SYN-2750)
  CHANGELOG.rst
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#3022 Update pyopenssl and cryptography requirements (SYN-4913)
  CHANGELOG.rst
  requirements.txt
  setup.py
  synapse/lib/certdir.py
Labels: enhancement

#3024 telepath.loadTeleCell() issue (SYN-4975)
  synapse/telepath.py
Labels: bug

#3001 Add onboot:optimize to allow LMDB optimization during boot
  CHANGELOG.rst
  synapse/lib/base.py
  synapse/lib/cell.py
  synapse/lib/lmdbslab.py
  synapse/tests/test_lib_cell.py
  synapse/tools/backup.py
Labels: enhancement
