Repository vertexproject/synapse, pull requests merged in 2024-04, with the labels that each got.

#3661 Add storm fixed cache (SYN-6946)
  synapse/cortex.py
  synapse/lib/stormlib/cache.py
  synapse/tests/test_lib_stormlib_cache.py
Labels: enhancement, reqChangelog

#3658 Bug: Agenda task teardown during promote can block the leadership promotion (SYN-7133)
  synapse/cortex.py
  synapse/lib/agenda.py
Labels: bug, reqChangelog

#3665 aha pool updates (SYN-7109, SYN-7110, SYN-7169)
  synapse/lib/stormlib/aha.py
  synapse/lib/stormlib/cortex.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_aha.py
Labels: bug, reqChangelog

#3656 `show:storage` opt to also add the storage info for the embeds, resolves SYN-7067
  synapse/lib/snap.py
  synapse/tests/test_lib_storm.py
Labels: enhancement, reqChangelog

#3663 Extended HTTP API Updates (SYN-7021, SYN-7141, SYN-7152, SYN-7153)
  synapse/cortex.py
  synapse/lib/httpapi.py
  synapse/lib/schemas.py
  synapse/lib/stormlib/cortex.py
  synapse/tests/test_lib_stormlib_cortex.py
Labels: bug, enhancement, reqChangelog

#3667 Add pool to the http:api.pack() method output if it is not present (SYN-7153)
  synapse/lib/stormlib/cortex.py
  synapse/tests/test_lib_stormlib_cortex.py
Labels: enhancement, reqChangelog

#3666 Add getMergeCount API, resolves SYN-7117
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3662 Refactor to unify telepath pool/client (SYN-7131, SYN-7134)
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/nexus.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_telepath.py
Labels: bug, enhancement, reqChangelog

#3669 Revert "Update the minimum required version of the stix2-validator library."
  pyproject.toml
  requirements.txt
  synapse/lib/stormlib/stix.py
Labels: bug, reqChangelog

#3678 Deprecate hiveboot.yaml usage (SYN-7146)
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: enhancement, reqChangelog

#3674 Deprecated edge type and related forms (SYN-7100)
  synapse/lib/types.py
  synapse/models/base.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_rstorm.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormlib_compression.py
  synapse/tests/test_lib_stormlib_spooled.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3682 SYN-7204: aiohttp 3.9.4 breaks axon wput test
  synapse/axon.py
  synapse/tools/autodoc.py
Labels: bug, reqChangelog

#3677 Let each cell create its own Client object.
  synapse/lib/cell.py
Labels: enhancement, reqChangelog

#3672 Stix2-validator update (SYN-7177)
  pyproject.toml
  requirements.txt
  synapse/lib/stormlib/stix.py
Labels: enhancement, reqChangelog

#3684 Increase allowed range of IDNA library
  pyproject.toml
  requirements.txt
Labels: enhancement

#3673 Fix: Weird tag pruning behavior, resolves SYN-7050
  synapse/lib/node.py
  synapse/tests/test_cortex.py
Labels: bug, reqChangelog

#3686 Ensure Base / Cell signal handler tasks are tracked to avoid GC (SYN-4952)
  synapse/lib/base.py
  synapse/lib/cell.py
Labels: bug, reqChangelog

#3687 Add a hook for StormPkgTest to interact with a Cortex before packages are loaded.
  synapse/tests/files/stormpkg/dotstorm/dotstorm.yaml
  synapse/tests/test_tools_genpkg.py
  synapse/tests/utils.py
Labels: enhancement, reqChangelog

#3679 Macro beholder events and more careful handling of macro names, resolves SYN-7115 SYN-7184 SYN-7196
  synapse/cortex.py
  synapse/lib/stormlib/macro.py
  synapse/tests/test_lib_stormlib_macro.py
Labels: enhancement, reqChangelog

#3688 Fix file:path normalization issue
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: bug, reqChangelog

#3681 SYN-7093: option to prevent deletion of a view
  synapse/cortex.py
  synapse/exc.py
  synapse/lib/schemas.py
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_view.py
Labels: enhancement, reqChangelog

#3685 Storm AHA API updates (SYN-6682, SYN-7010, SYN-7168, SYN-7209)
  synapse/lib/stormlib/aha.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_stormlib_aha.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/utils.py
Labels: bug, enhancement, reqChangelog

#3690 Changelog for v2.167.0
  CHANGELOG.rst
  synapse/tests/test_tools_genpkg.py
  synapse/tests/utils.py
Labels: documentation

#3692 Account for aha networks / names that are wide
  CHANGELOG.rst
  synapse/lib/stormlib/aha.py
  synapse/tests/test_lib_stormlib_aha.py
Labels: enhancement

#3693 Log when a service has been deleted from AHA
  CHANGELOG.rst
  synapse/lib/aha.py
Labels: enhancement

#3695 SYN-7154: modelrev.runstorm to disable pool
  synapse/lib/modelrev.py
Labels: enhancement, reqChangelog

#3700 Add sleep statements for some callers of syncNodeEdits2 which were missing (SYN-7287)
  synapse/cortex.py
  synapse/lib/layer.py
  synapse/lib/view.py
Labels: bug, reqChangelog

#3701 SYN-7185: archive rapid7 repos
  docs/synapse/power_ups.rst
Labels: documentation

#3697 Model additions for planning systems/procedures/steps/phases
  synapse/lib/modules.py
  synapse/models/planning.py
  synapse/tests/test_model_planning.py
Labels: enhancement, reqChangelog
