Repository vertexproject/synapse, pull requests merged in 2024-12, with the labels that each got.

#4018 SYN-7590: syn:cmd runt node lift raised 'dictionary keys changed during iteration' RuntimeError
  changes/0244354eeb3357a00daa09ff5432542c.yaml
  synapse/models/syn.py
  synapse/tests/test_model_syn.py
Labels: bug

#4011 Update Python package requirements
  changes/869d76131459cc98c17ba41d0e870ef0.yaml
  pyproject.toml
  requirements.txt
Labels: enhancement, dependencies

#4017 Cell.adminapi - add wrapped func to struct log and fix AuthDeny
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_lmdbslab.py
  synapse/tests/test_lib_stormlib_cortex.py
  synapse/tests/test_lib_stormlib_log.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_lib_trigger.py
  synapse/tests/test_utils.py
  synapse/tests/utils.py
Labels: enhancement

#4027 Changelog for v2.191.0
  CHANGELOG.rst
  changes/0244354eeb3357a00daa09ff5432542c.yaml
  changes/682ec41b52580113397a486bf8b6375c.yaml
  changes/869d76131459cc98c17ba41d0e870ef0.yaml
  changes/9a938445e5032cd85d989fd364099600.yaml
  changes/a20a071e0a601e3b9c32ab279ffa663a.yaml
  changes/f3f11729f396cca949121d9d2ccb4bf8.yaml
  docs/synapse/userguides/model_updates/update_v2_191_0.rst
  synapse/lib/msgpack.py
  synapse/models/telco.py
  synapse/tests/test_model_base.py
Labels: documentation

#4028 Fix runMirrorLoop version checking for ready handling. (SYN-8408)
  changes/97840d098f93ba22d670165cdd0ce7ca.yaml
  synapse/lib/nexus.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_servers_univ.py
Labels: bug

#4026 Add user-agent to web logs
  changes/fc37c51f8dcd9d232c0063fdcd907f90.yaml
  synapse/lib/cell.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement

#4029 Add changelog entry for Layer getNodeData() Storm API
  CHANGELOG.rst
Labels: documentation

#4032 SYN-8284: synapse.tools.apikey to support adding/deleting API keys
  changes/af6c75e04ed1f03290a7c0926bb91110.yaml
  synapse/lib/cell.py
  synapse/tests/test_tools_apikey.py
  synapse/tools/apikey.py
Labels: enhancement

#4035 Add line number information to exceptions raised during var derefs (SYN-8307)
  changes/e25248c44d5ba33a43ae937a0bb25fd4.yaml
  synapse/lib/ast.py
  synapse/tests/test_lib_ast.py
Labels: enhancement

#4037 Changelog for v2.192.0
  CHANGELOG.rst
  changes/173b1177e82ed6ab9c76ed9a822a8657.yaml
  changes/50f21639946d72088a36adf6653828b4.yaml
  changes/88fa45340a89ce6994ec255b95baf450.yaml
  changes/97840d098f93ba22d670165cdd0ce7ca.yaml
  changes/a402c23ee6ae45fef72fded0bc992edd.yaml
  changes/af6c75e04ed1f03290a7c0926bb91110.yaml
  changes/bab32ddfc47f9963c4d69b0af747a39b.yaml
  changes/e25248c44d5ba33a43ae937a0bb25fd4.yaml
  changes/fc37c51f8dcd9d232c0063fdcd907f90.yaml
Labels: documentation

#4034 Remove async from Cortex.loadStormPkg and Cortex._dropStormPkg (SYN-8426)
  synapse/cortex.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormlib_scrape.py
Labels: enhancement

#4049 No requests in mainline code.
  synapse/tests/test_utils_getrefs.py
  synapse/utils/getrefs.py
Labels: bug

#4042 refactor streaming backup (SYN-8340)
  changes/34ba15e2aef8b5c6be4d0274db884f84.yaml
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#4048 catch ctrl-c for long running queries in tools.storm (SYN-7932)
  changes/5433695fd5f2187f2cd9f7a4ba0ae4d9.yaml
  pyproject.toml
  requirements.txt
  synapse/lib/cli.py
  synapse/tests/test_tools_storm.py
Labels: bug

#4038 Add line number information to exceptions raised during function calls
  changes/e25248c44d5ba33a43ae937a0bb25fd5.yaml
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_ast.py
Labels: bug

#4050 Update SynErr.errinfo manipulation to use set / update APIs.
  synapse/exc.py
  synapse/lib/ast.py
  synapse/lib/parser.py
  synapse/lib/snap.py
  synapse/tests/test_exc.py
Labels: enhancement

#4045 Add http.coookies monkeypatch (SYN-8465)
  changes/bd45773cff22d0cf547370e90918ba58.yaml
  synapse/common.py
  synapse/vendor/cpython/lib/http/__init__.py
  synapse/vendor/cpython/lib/http/cookies.py
  synapse/vendor/cpython/lib/test/test_http_cookies.py
Labels: bug
