Repository vertexproject/synapse, pull requests merged in 2024-03, with the labels that each got.

#3598 Changelog for v2.164.0
  CHANGELOG.rst
  synapse/lib/stormlib/gen.py
Labels: documentation

#3595 Add file:mime:image:text for recording text parsed from an image (SYN-6939)
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: enhancement, reqChangelog

#3599 Update Storm pivot docs
  docs/synapse/userguides/storm_ref_data_mod.rstorm
  docs/synapse/userguides/storm_ref_pivot.rstorm
Labels: documentation

#3605 SYN-6209: $lib.regex.escape
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3602 Finalize storm pool configuration management and implementation
  docs/synapse/deploymentguide.rst
  synapse/cortex.py
  synapse/lib/cell.py
  synapse/lib/schemas.py
  synapse/lib/stormlib/cortex.py
  synapse/tests/test_cortex.py
Labels: enhancement, reqChangelog

#3608 Use normal write mode with compresslevel=1 for streaming backups
  synapse/lib/cell.py
Labels: enhancement, reqChangelog

#3611 More spelling/docs fixes
  synapse/axon.py
  synapse/common.py
  synapse/datamodel.py
  synapse/lib/stormlib/cortex.py
  synapse/lib/stormlib/math.py
Labels: documentation

#3607 Add AHA APIs for clearing unused provisioning information (SYN-6986)
  synapse/lib/aha.py
  synapse/tests/test_lib_aha.py
Labels: enhancement, reqChangelog

#3613 Update aha api names for deleting unused entries (SYN-6986)
  synapse/lib/aha.py
  synapse/tests/test_lib_aha.py
Labels: enhancement

#3609 Clamp certdir cname and aha provisioning name values (SYN-6634)
  synapse/lib/aha.py
  synapse/lib/certdir.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_certdir.py
Labels: bug, reqChangelog

#3618 Fix isconst check when pivoting to a variable form (SYN-7048)
  synapse/lib/ast.py
  synapse/tests/test_lib_ast.py
Labels: bug, reqChangelog

#3615 Add verbose logging to the Cell.promote and Cell.handoff methods (SYN-7029)
  synapse/lib/cell.py
Labels: enhancement, reqChangelog

#3616 Fix velocity string norming when no unit is provided (SYN-7032)
  synapse/lib/modelrev.py
  synapse/lib/types.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_lib_types.py
Labels: bug

#3606 Additional has/owns verbs and risk:vulnerable
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/models/risk.py
  synapse/tests/test_model_risk.py
Labels: enhancement, reqChangelog

#3625 Bug: Add missing fini handler for activebase
  synapse/lib/cell.py
Labels: bug, reqChangelog

#3635 Doc updates (SYN-7088, SYN-7089, SYN-7090, SYN-7092)
  synapse/lib/stormlib/aha.py
  synapse/models/economic.py
  synapse/models/science.py
Labels: bug

#3631 Use cell.version as the version check when doing mirror version checking (SYN-7091)
  synapse/lib/nexus.py
  synapse/tests/test_lib_nexus.py
Labels: bug, reqChangelog

#3638 Bug node perm check dataclasses
  synapse/lib/hiveauth.py
  synapse/lib/storm.py
  synapse/lib/stormlib/auth.py
Labels: enhancement

#3627 Bug: Node property set / deletion permissions precedence order issue (SYN-7038, SYN-7077)
  synapse/datamodel.py
  synapse/lib/hiveauth.py
  synapse/lib/storm.py
  synapse/lib/stormlib/auth.py
  synapse/tests/test_lib_ast.py
Labels: bug, reqChangelog

#3593 SYN-6917: Remove `synapse_minversion` references from everywhere
  docs/docdata/foopkg/foopkg.yml
  docs/synapse/devguides/power-ups.rst
  docs/synapse/devguides/stormservices.ipynb
  docs/synapse/userguides/syn_tools_genpkg.ipynb
  examples/power-ups/rapid/acme-hello/acme-hello.yaml
  synapse/cortex.py
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_httpapi.py
  synapse/tests/test_lib_jupyter.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormsvc.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_syn.py
Labels: enhancement, reqChangelog

#3641 bug: copyto needs to use the layriden when checking confirmPropSet for the destination layer (SYN-7102)
  synapse/lib/storm.py
Labels: bug, reqChangelog

#3643 Hand in AHA URL for service pool entries
  synapse/telepath.py
Labels: bug, reqChangelog

#3645 Ensure fini pool proxies are removed from dequeue (SYN-7111)
  synapse/telepath.py
Labels: bug, reqChangelog

#3634 Changelog for v2.165.0
  CHANGELOG.rst
Labels: documentation

#3640 Deprecate telepath task V1, add message to t2:genr LinkShutDown (SYN-7035, SYN-7033)
  synapse/telepath.py
Labels: enhancement, reqChangelog

#3651 Add --list and --gate options to moduser/modrole tools (SYN-4923)
  synapse/common.py
  synapse/lib/stormlib/auth.py
  synapse/tests/test_tools_modrole.py
  synapse/tests/test_tools_moduser.py
  synapse/tools/modrole.py
  synapse/tools/moduser.py
Labels: enhancement, reqChangelog

#3648 Add check for use of cortex authgate, warn when it is set via storm (SYN-7007)
  synapse/cortex.py
  synapse/lib/stormlib/auth.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_storm.py
Labels: enhancement, reqChangelog

#3632 Add spooled set stormtype, resolves SYN-7020, SYN-3401
  synapse/cortex.py
  synapse/lib/stormlib/cortex.py
  synapse/lib/stormlib/spooled.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormlib_spooled.py
Labels: enhancement, reqChangelog

#3649 Add default column defs to a few forms
  synapse/datamodel.py
  synapse/models/orgs.py
  synapse/models/person.py
  synapse/models/risk.py
  synapse/tests/test_datamodel.py
Labels: enhancement, reqChangelog

#3647 Add Storm service permissions to the declared permissions (SYN-7014)
  synapse/lib/stormtypes.py
Labels: enhancement, reqChangelog

#3650 Redirect tags based on parent tags having :isnow properties set
  synapse/lib/snap.py
  synapse/lib/types.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_storm.py
Labels: enhancement, reqChangelog

#3652 Add pool option to cron jobs
  synapse/cortex.py
  synapse/lib/agenda.py
  synapse/lib/schemas.py
  synapse/lib/storm.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog
