Repository vertexproject/synapse, pull requests merged in 2024-10, with the labels that each got.

#3938 Macro docs update (VTX-1795)
  docs/synapse/glossary.rst
  docs/synapse/userguides/storm_ref_automation.rstorm
Labels: documentation

#3929 Add some deprecation info to the stormlib/function info
  changes/1f6a274b8f349b5456339018fabc6414.yaml
  synapse/lib/autodoc.py
  synapse/lib/storm.py
  synapse/lib/stormlib/cortex.py
  synapse/lib/stormlib/infosec.py
  synapse/lib/stormlib/model.py
  synapse/lib/stormtypes.py
  synapse/tests/files/stormpkg/testpkg.yaml
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_autodoc.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_tools_autodoc.py
  synapse/tests/utils.py
  synapse/tools/autodoc.py
Labels: enhancement

#3939 Update / clarify info on guid types (VTX-2933)
  docs/synapse/userguides/storm_ref_type_specific.rstorm
Labels: documentation

#3941 Catch BadTag in tag add try syntax (SYN-8067)
  changes/15335178955a306aa781fad26e861ed4.yaml
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
Labels: bug

#3942 SYN-7989: Can't mod it:fs:file::path:base value after creation
  changes/567b27ca0c86763ea74b5335e249f3bb.yaml
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: bug

#3944 Add task.get and task.del perm declarations (SYN-8075)
  changes/3b29a319448855b62c467473db0809c6.yaml
  synapse/cortex.py
Labels: bug

#3945 Add $lib.random.generator() (SYN-8077)
  changes/cbc55b0dc67ba567eab1337905889565.yaml
  synapse/lib/stormlib/random.py
  synapse/tests/test_lib_stormlib_random.py
Labels: enhancement

#3946 Changelog for v2.183.0
  CHANGELOG.rst
  changes/15335178955a306aa781fad26e861ed4.yaml
  changes/1f6a274b8f349b5456339018fabc6414.yaml
  changes/3b29a319448855b62c467473db0809c6.yaml
  changes/567b27ca0c86763ea74b5335e249f3bb.yaml
  changes/cbc55b0dc67ba567eab1337905889565.yaml
  docs/synapse/userguides/model_updates/update_v2_183_0.rst
  synapse/tools/changelog.py
Labels: documentation

#3949 Fix varlistset runtsafety issue (SYN-8114)
  changes/b033cdc61731e49b48db67094121b4d6.yaml
  synapse/lib/ast.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_ast.py
Labels: bug

#3951 Deprecate `$lib.inet.whois.guid` (SYN-8070)
  changes/d4c6fdc96cc6347ebcef68d8fa6b0131.yaml
  synapse/lib/stormwhois.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_stormwhois.py
Labels: enhancement

#3952 Mark all functions in a deprecated library (like LibBytes) as deprecated (SYN-8060)
  changes/8f5c83c0f2f977bfcd07b6131aa7ad1b.yaml
  synapse/lib/autodoc.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_autodoc.py
  synapse/tests/test_lib_storm.py
  synapse/tests/utils.py
Labels: enhancement

#3957 Model for assets and mitigation types
  changes/1bb2c10dcd45ca552c2614fdc31903b7.yaml
  changes/d0b850904544a61640cd0432a052d800.yaml
  synapse/models/orgs.py
  synapse/models/risk.py
  synapse/tests/test_model_orgs.py
  synapse/tests/test_model_risk.py
Labels: enhancement

#3958 Fix interface handling when deleting extended model forms (SYN-8043)
  changes/8b13b1e0805b28027205dcc2a9d507ba.yaml
  synapse/datamodel.py
  synapse/tests/test_lib_stormlib_modelext.py
Labels: bug

#3961 Changelog for v2.184.0
  CHANGELOG.rst
  changes/1bb2c10dcd45ca552c2614fdc31903b7.yaml
  changes/2ce741ee21dd3f5f55838ec14d75e807.yaml
  changes/33127175adaff42214b2e19af4688fab.yaml
  changes/44763e312940ac2d6b448d82442020c4.yaml
  changes/8b13b1e0805b28027205dcc2a9d507ba.yaml
  changes/8f5c83c0f2f977bfcd07b6131aa7ad1b.yaml
  changes/b033cdc61731e49b48db67094121b4d6.yaml
  changes/c0742a66de15a690dbd560cf8f17a670.yaml
  changes/d0b850904544a61640cd0432a052d800.yaml
  changes/d4c6fdc96cc6347ebcef68d8fa6b0131.yaml
  changes/f57bc5bea7752161edf0667f2e08204c.yaml
  docs/synapse/userguides/model_updates/update_v2_184_0.rst
Labels: documentation

#3966 Prevent Cell.handoff() from executing on non-leader services (SYN-8157)
  changes/3d96986df672d56d7143a2a6f91d4ff7.yaml
  changes/8da40a8252615ed2243a907c06ab165a.yaml
  synapse/lib/cell.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_tools_promote.py
  synapse/tools/promote.py
Labels: bug

#3977 Implement freeze() / resume() API and synapse.tools.snapshot
  changes/24c8600a22c769c150ef9ac09529b1c7.yaml
  changes/d8fac054aca3b0349a60b5baef35a22f.yaml
  synapse/lib/cell.py
  synapse/tests/test_tools_snapshot.py
  synapse/tools/aha/clone.py
  synapse/tools/aha/easycert.py
  synapse/tools/aha/enroll.py
  synapse/tools/aha/provision/service.py
  synapse/tools/aha/provision/user.py
  synapse/tools/livebackup.py
  synapse/tools/promote.py
  synapse/tools/snapshot.py
Labels: enhancement

#3978 Changelog for v2.186.0
  CHANGELOG.rst
  changes/24c8600a22c769c150ef9ac09529b1c7.yaml
  changes/60d8953a7fa67ef77e490823d34c5582.yaml
  changes/c59d22e4667bab19936fa9c146c5d707.yaml
  changes/d8fac054aca3b0349a60b5baef35a22f.yaml
  docs/synapse/userguides/model_updates/update_v2_186_0.rst
Labels: documentation

#3918 SYN-8002: CPE migration helper functions
  changes/43f371ecea46eb149a43a4fedc8052ed.yaml
  changes/ba8fc0dc6da223ce7484149c106d3447.yaml
  changes/cc1e9aa094fc02194a37c6fc7eb686e7.yaml
  pyproject.toml
  synapse/assets/__init__.py
  synapse/assets/storm/migrations/model-0.2.28.storm
  synapse/cortex.py
  synapse/lib/hive.py
  synapse/lib/modelrev.py
  synapse/lib/spooled.py
  synapse/lib/stormlib/model.py
  synapse/lib/stormtypes.py
  synapse/models/infotech.py
  synapse/tests/test_assets.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_modelrev.py
  synapse/tests/test_lib_spooled.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tests/test_lib_stormtypes.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#3982 Clarify heavy object handling behavior in runas/view.exec (SYN-8041)
  docs/synapse/userguides/storm_ref_cmd.rstorm
  synapse/lib/storm.py
Labels: documentation

#3983 Changelog for v2.187.0
  CHANGELOG.rst
  changes/43f371ecea46eb149a43a4fedc8052ed.yaml
  changes/ba8fc0dc6da223ce7484149c106d3447.yaml
  changes/cc1e9aa094fc02194a37c6fc7eb686e7.yaml
  docs/synapse/userguides/model_updates/update_v2_187_0.rst
  scripts/doctests.py
  synapse/tools/changelog.py
Labels: documentation
