Repository vertexproject/synapse, pull requests merged in 2024-07, with the labels that each got.

#3768 SYN-7474: nexus mirror loop can die if dns is removed from under it?
  synapse/lib/nexus.py
  synapse/tests/test_lib_nexus.py
Labels: bug

#3791 Skeleton of synapse.tools.changelog + change files for v2.174.0
  changes/.gitkeep
  changes/0bf440170993e8eb22226bba18dfabad.yaml
  changes/10e0be88505921617b1107fcf6c8bc70.yaml
  changes/284e57c9e4e874be69e982ec3e3d26fb.yaml
  changes/35b13bde0c424d8df575d77c0588a9ee.yaml
  changes/4e316b8dc3f963083591218b74d5bc16.yaml
  changes/54b59b674df6be36fa8946579d238674.yaml
  changes/7cd478c2b229954060670cc6cd50fe22.yaml
  changes/8088c654bd3f9877adec9f9ec2c3b975.yaml
  changes/8d08208d076fb84207aec7608219e5b4.yaml
  changes/9978d0926e51b558e78aa0a0f168dce4.yaml
  changes/ac281161b19aa53704d0a99c9762153e.yaml
  synapse/common.py
  synapse/cortex.py
  synapse/lib/schemas.py
  synapse/lib/stormtypes.py
  synapse/tools/changelog.py
Labels: enhancement, documentation

#3792 Changelog for v2.174.0
  CHANGELOG.rst
  changes/0bf440170993e8eb22226bba18dfabad.yaml
  changes/10e0be88505921617b1107fcf6c8bc70.yaml
  changes/284e57c9e4e874be69e982ec3e3d26fb.yaml
  changes/35b13bde0c424d8df575d77c0588a9ee.yaml
  changes/4e316b8dc3f963083591218b74d5bc16.yaml
  changes/54b59b674df6be36fa8946579d238674.yaml
  changes/7cd478c2b229954060670cc6cd50fe22.yaml
  changes/8088c654bd3f9877adec9f9ec2c3b975.yaml
  changes/8d08208d076fb84207aec7608219e5b4.yaml
  changes/9978d0926e51b558e78aa0a0f168dce4.yaml
  changes/ac281161b19aa53704d0a99c9762153e.yaml
  synapse/models/economic.py
  synapse/models/geopol.py
  synapse/tests/test_model_geopol.py
Labels: enhancement, documentation

#3793 Add logs for cron job enabling / disabling (SYN-7490)
  CHANGELOG.rst
  synapse/cortex.py
  synapse/tools/changelog.py
Labels: enhancement

#3796 Avoid deadlock in $lib.cron.kill()
  CHANGELOG.rst
  synapse/cortex.py
  synapse/tests/test_lib_agenda.py
Labels: bug

#3770 SYN-7598: User overridable http options
  changes/40b390075a459e6e92de24b077660bb1.yaml
  synapse/lib/cell.py
Labels: enhancement

#3799 Fix for large array props causing system lag
  changes/57063623557b594a615bdf2d825589fe.yaml
  synapse/lib/layer.py
Labels: bug

#3804 Merge cmd perm optimizations (SYN-7656, SYN-7127)
  changes/162508092fc91905bb0669f10d4d9d46.yaml
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#3806 Support multiple tags in diff command (SYN-7656)
  changes/933fa110524f48414d2abbf5c8dda1ab.yaml
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#3802 Store HTTPS listener information, add it to getCellInfo() (SYN-7632)
  changes/191b3876553873b7a8ad0e2e61a43dd7.yaml
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: enhancement

#3803 Remove remaining jupyter docs (SYN-7597)
  changes/3dc5e844303dec8f10a6dffddafec873.yaml
  changes/4c9a2cdca40851b2460f3e682c847849.yaml
  docs/conf.py
  docs/synapse/contributing/doc_mastering.ipynb
  docs/synapse/contributing/doc_mastering.rst
  docs/synapse/devguide.rst
  docs/synapse/devguides/adv_power_ups.rst
  docs/synapse/devguides/cortex_quickstart.ipynb
  docs/synapse/devguides/power-ups.rst
  docs/synapse/devguides/stormservices.ipynb
  docs/synapse/userguides/syn_tools_genpkg.ipynb
  docs/synapse/userguides/syn_tools_genpkg.rst
  scripts/doctests.py
  synapse/lib/jupyter.py
Labels: enhancement, documentation

#3808 Add link address info to some dmon / link related error messages
  changes/5d9920aef5c359d9839c744a251011ff.yaml
  synapse/daemon.py
  synapse/lib/link.py
  synapse/tests/test_daemon.py
Labels: enhancement

#3810 Changelog for v2.175.0
  CHANGELOG.rst
  changes/03c7f7fe2e7a73d7fc44584369a0a1d7.yaml
  changes/162508092fc91905bb0669f10d4d9d46.yaml
  changes/191b3876553873b7a8ad0e2e61a43dd7.yaml
  changes/3dc5e844303dec8f10a6dffddafec873.yaml
  changes/40b390075a459e6e92de24b077660bb1.yaml
  changes/4c9a2cdca40851b2460f3e682c847849.yaml
  changes/57063623557b594a615bdf2d825589fe.yaml
  changes/5d9920aef5c359d9839c744a251011ff.yaml
  changes/7180c158e6ee1fb0a8100898c505d2fb.yaml
  changes/8cedc37e450f0c7833b68e1145762089.yaml
  changes/933fa110524f48414d2abbf5c8dda1ab.yaml
  changes/fa0f0afe26db13ddd9d35b3d1c784801.yaml
Labels: documentation

#3812 Add the view iden to synapse.storm logger.
  changes/9b2ee0e0bba2b8a00114aebf067a4c40.yaml
  changes/e1e7d83f37341583bcf6876abb2c411a.yaml
  synapse/lib/stormlib/storm.py
Labels: enhancement

#3813 Add $lib.storm.run() function
  changes/9b0c3998325687c0ac92251ed3b9ddbf.yaml
  synapse/lib/stormlib/storm.py
  synapse/tests/test_lib_stormlib_storm.py
Labels: enhancement

#3819 Do not log the per-node pivot errors to the snap logger.
  changes/c75a0630de2796b281dee39673da456d.yaml
  synapse/lib/ast.py
Labels: enhancement

#3817 Enh: Prop additions for LNK form, resolves SYN-7680
  changes/11f2d115dca7d817e457fa13d0e6a2f7.yaml
  synapse/models/files.py
  synapse/tests/test_model_files.py
Labels: enhancement

#3818 Add tabular stormlib (SYN-7652)
  changes/9dd54637fd2fce6ee1cefe708336892d.yaml
  docs/synapse/devopsguide.rst
  synapse/cortex.py
  synapse/lib/schemas.py
  synapse/lib/stormlib/cortex.py
  synapse/lib/stormlib/tabular.py
  synapse/tests/test_lib_stormlib_cortex.py
  synapse/tests/test_lib_stormlib_tabular.py
Labels: enhancement

#3801 SYN-7488: inet:ssl:cert -> inet:tls:* migration helper
  .circleci/config.yml
  changes/1987d42974cbe92cadcfa537debc9dc2.yaml
  changes/85f8d04d446272ee1f394dbfea44b992.yaml
  changes/b098583bbfa9f16f74d198b4e6e0fb21.yaml
  changes/f15c93e3948905070949eaf2553de647.yaml
  synapse/lib/stormlib/gen.py
  synapse/lib/stormlib/model.py
  synapse/tests/test_lib_stormlib_gen.py
  synapse/tests/test_lib_stormlib_model.py
  synapse/tools/changelog.py
Labels: enhancement

#3826 Agenda log issue: mesg is a str not a tuple
  synapse/lib/agenda.py
Labels: bug

#3829 Cap aiohttp maximum version
  changes/51475aeec1ed01c9c2247b27c8cae659.yaml
  pyproject.toml
  requirements.txt
Labels: enhancement

#3831 Bug: addresses OSError related to "Bad file descriptor" messages that could occur after a socket has closed (SYN-7773)
  changes/766777551f0c9e7c78e8728849e3ffc3.yaml
  synapse/lib/link.py
  synapse/tests/test_lib_link.py
Labels: bug
