Repository vertexproject/synapse, pull requests merged in 2024-02, with the labels that each got.

#3534 Set aha logs to info level (SYN-6519)
  synapse/lib/aha.py
Labels: enhancement, reqChangelog

#3523 Update Synapse User Guide - data model docs
  docs/synapse/userguides/data_model.rstorm
Labels: documentation

#3519 Add aha information to getCellInfo (SYN-6764)
  synapse/lib/cell.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_cell.py
Labels: enhancement, reqChangelog

#3538 Back out trigger setting created time
  synapse/lib/trigger.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#3539 Fix AHA pool replay test inconsistency
  synapse/cortex.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_aha.py
Labels: bug

#3516 Add gen command for it:av:scan:result (SYN-6661)
  synapse/lib/stormlib/gen.py
  synapse/tests/test_lib_stormlib_gen.py
Labels: enhancement, reqChangelog

#3541 Add getMergeRequest() and getMergeRequestSummary() to storm view object
  synapse/lib/stormtypes.py
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3544 Add a method to the http session to do a bulk value set
  synapse/lib/cell.py
  synapse/lib/httpapi.py
  synapse/tests/test_lib_httpapi.py
Labels: enhancement, reqChangelog

#3536 Doc changelog 20240131
  CHANGELOG.rst
Labels: documentation

#3547 Update Synapse User Guide "Automation" docs
  docs/synapse/glossary.rst
  docs/synapse/userguides/storm_ref_automation.rstorm
  docs/synapse/userguides/storm_ref_model_introspect.rstorm
  docs/synapse/userguides/views_layers.rst
Labels: documentation, reqChangelog

#3550 benchmark_cortex.py, change eval -> storm
  scripts/benchmark_cortex.py
Labels: bug

#3555 SYN-6763: $str.json()
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3556 Fix use of updateHttpSessInfo by cells that haven't loaded a sess into memory
  synapse/lib/cell.py
Labels: bug, reqChangelog

#3549 SYN-6848: :url added to ou:id:type
  synapse/models/orgs.py
  synapse/tests/test_model_orgs.py
Labels: enhancement, reqChangelog

#3560 Storm update (Part 1)
  docs/synapse/userguides/storm_ref_filter.rstorm
  docs/synapse/userguides/storm_ref_lift.rstorm
  docs/synapse/userguides/storm_ref_subquery.rstorm
Labels: documentation

#3564 Add received:from:ipv4/ipv6/fqdn to inet:email:message
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement, reqChangelog

#3567 Add rstorm onload waiters (SYN-6871)
  synapse/lib/rstorm.py
  synapse/tests/files/rstorm/testsvc.py
  synapse/tests/files/stormpkg/testpkg.yaml
  synapse/tests/test_lib_rstorm.py
Labels: enhancement, reqChangelog

#3545 Adjust tag permissions check during merges (SYN-6830)
  synapse/lib/layer.py
  synapse/lib/storm.py
  synapse/tests/test_lib_view.py
Labels: bug, reqChangelog

#3572 Changelog for v2.162.0
  CHANGELOG.rst
Labels: documentation

#3575 Enable constructing a guid from a single value in Storm (SYN-6933)
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3574 SYN-5975: replace "/" with "_" on tags in branch builds
  .circleci/config.yml
Labels: enhancement

#3576 Revert $lib.bytes deprecation
  synapse/lib/stormtypes.py
Labels: enhancement, reqChangelog

#3577 Changelog for v2.163.0
  CHANGELOG.rst
Labels: documentation

#3580 Add merge request and votes to quorum merge beholder events.
  synapse/lib/view.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement, reqChangelog

#3583 Add tempdir information to getSystemInfo() APIS (SYN-6866)
  synapse/lib/cell.py
  synapse/lib/platforms/common.py
  synapse/tests/test_lib_cell.py
Labels: enhancement, reqChangelog

#3586 SYN-4369: Add ``--del`` option to ``synapse.tools.modrole`` command
  synapse/tests/test_tools_modrole.py
  synapse/tools/modrole.py
Labels: enhancement, reqChangelog

#3587 SYN-4370: Deprecate ``synapse.tools.cellauth``
  synapse/common.py
  synapse/tests/test_tools_cellauth.py
  synapse/tools/cellauth.py
Labels: enhancement, reqChangelog

#3568 Update cryptography to 42.0.4 and update certdir (SYN-3552, SYN-6860)
  pyproject.toml
  requirements.txt
  synapse/cortex.py
  synapse/lib/aha.py
  synapse/lib/certdir.py
  synapse/lib/crypto/rsa.py
  synapse/lib/link.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_certdir.py
  synapse/tests/test_telepath.py
  synapse/tests/test_tools_docker_validate.py
  synapse/tests/test_tools_easycert.py
  synapse/tools/aha/easycert.py
  synapse/tools/docker/validate.py
Labels: enhancement, reqChangelog

#3584 Use tostr on prop/form names to avoid attribute errors (SYN-6657)
  synapse/lib/ast.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_ast.py
Labels: bug, reqChangelog

#3589 Deprecate cmdr (SYN-6873)
  synapse/lib/cmdr.py
  synapse/tests/test_cmds_cortex.py
Labels: enhancement
