Repository vertexproject/synapse, pull requests merged in 2024-08, with the labels that each got.

#3830 Update aiohttp + aiohttp-socks together
  changes/51475aeec1ed01c9c2247b27c8cae659.yaml
  changes/a09c5a98ed03e6f6d5a486b6f71358ff.yaml
  pyproject.toml
  requirements.txt
  synapse/tests/test_axon.py
Labels: enhancement

#3836 Changelog for v2.177.0, changelog tool updates
  .coveragerc
  CHANGELOG.rst
  changes/0fd928464e1279bb2ad427d34dff41be.yaml
  changes/11f2d115dca7d817e457fa13d0e6a2f7.yaml
  changes/1987d42974cbe92cadcfa537debc9dc2.yaml
  changes/40149ec18dae127e0be8b3246cdb2426.yaml
  changes/69e610471c72c496b629a2dab72de988.yaml
  changes/6af3e9b19b477fc9b5a0a9b99cffb85e.yaml
  changes/6ca4b85ad6834e502b0f156483c81d5d.yaml
  changes/71c62dcf5972525552891a051dc0affc.yaml
  changes/766777551f0c9e7c78e8728849e3ffc3.yaml
  changes/772657cf16edfbbc84207e030a5abc15.yaml
  changes/7758bace71e568accc6e66f761dd0f54.yaml
  changes/85f8d04d446272ee1f394dbfea44b992.yaml
  changes/9dd54637fd2fce6ee1cefe708336892d.yaml
  changes/a09c5a98ed03e6f6d5a486b6f71358ff.yaml
  changes/b098583bbfa9f16f74d198b4e6e0fb21.yaml
  changes/be9adb6265fe179686312f871bc04905.yaml
  changes/d26ecea7c1bec4a8b2c354f6bf374cb8.yaml
  changes/d67820964f7e9f22c9315309b3de14ad.yaml
  changes/dc728d3fb932016d445ef3f2c7dba228.yaml
  changes/df8566411d59425c876fd3a940050ded.yaml
  changes/e9bb88deb90fa149c657cdce3ee8acc3.yaml
  changes/f15c93e3948905070949eaf2553de647.yaml
  changes/modelrefs/model_2.176.0_16ee721a6b7221344eaf946c3ab4602dda546b1a.yaml.gz
  docs/synapse/userguide.rst
  docs/synapse/userguides/index_model_updates.rst
  docs/synapse/userguides/model_update_v2_176_0.rst
  docs/synapse/userguides/model_update_v2_177_0.rst
  synapse/tests/files/changelog/model_2.176.0_16ee721a6b7221344eaf946c3ab4602dda546b1a.yaml.gz
  synapse/tests/files/changelog/model_2.176.0_2a25c58bbd344716cd7cbc3f4304d8925b0f4ef2.yaml.gz
  synapse/tests/test_tools_changelog.py
  synapse/tools/changelog.py
Labels: documentation

#3839 Model Doc updates
  CHANGELOG.rst
  changes/0d70678d970e2a045f8b1e225df8afa4.yaml
  changes/82ba890689de6c96e87ee71470fe680f.yaml
  changes/modelrefs/model_2.177.0_b7da795aeb690020e38e99dc5aa1f505cdc2d659.yaml.gz
  docs/synapse/devopsguide.rst
  docs/synapse/userguides/index_model_updates.rst
  docs/synapse/userguides/model_updates/update_v2_133_0.rst
  docs/synapse/userguides/model_updates/update_v2_134_0.rst
  docs/synapse/userguides/model_updates/update_v2_137_0.rst
  docs/synapse/userguides/model_updates/update_v2_140_0.rst
  docs/synapse/userguides/model_updates/update_v2_141_0.rst
  docs/synapse/userguides/model_updates/update_v2_142_0.rst
  docs/synapse/userguides/model_updates/update_v2_143_0.rst
  docs/synapse/userguides/model_updates/update_v2_144_0.rst
  docs/synapse/userguides/model_updates/update_v2_145_0.rst
  docs/synapse/userguides/model_updates/update_v2_149_0.rst
  docs/synapse/userguides/model_updates/update_v2_150_0.rst
  docs/synapse/userguides/model_updates/update_v2_151_0.rst
  docs/synapse/userguides/model_updates/update_v2_152_0.rst
  docs/synapse/userguides/model_updates/update_v2_153_0.rst
  docs/synapse/userguides/model_updates/update_v2_154_0.rst
  docs/synapse/userguides/model_updates/update_v2_155_0.rst
  docs/synapse/userguides/model_updates/update_v2_156_0.rst
  docs/synapse/userguides/model_updates/update_v2_160_0.rst
  docs/synapse/userguides/model_updates/update_v2_162_0.rst
  docs/synapse/userguides/model_updates/update_v2_165_0.rst
  docs/synapse/userguides/model_updates/update_v2_166_0.rst
  docs/synapse/userguides/model_updates/update_v2_167_0.rst
  docs/synapse/userguides/model_updates/update_v2_168_0.rst
  docs/synapse/userguides/model_updates/update_v2_170_0.rst
  docs/synapse/userguides/model_updates/update_v2_172_0.rst
  docs/synapse/userguides/model_updates/update_v2_173_0.rst
  docs/synapse/userguides/model_updates/update_v2_173_1.rst
  docs/synapse/userguides/model_updates/update_v2_174_0.rst
  docs/synapse/userguides/model_updates/update_v2_176_0.rst
  docs/synapse/userguides/model_updates/update_v2_177_0.rst
  docs/synapse/userguides/syn_tools_csvtool.rst
  docs/synapse/userguides/syn_tools_pullfile.rst
  docs/synapse/userguides/syn_tools_pushfile.rst
  synapse/tools/changelog.py
Labels: documentation

#3783 AHA Clones / Dynamic Servers
  changes/06bd1eabe999e90b2b3301ee041f7017.yaml
  changes/46d7d7c3fd22e158bd500f03532e7b3a.yaml
  changes/6ebc22454e67c26ce57ea4533441c9fc.yaml
  changes/b652abf9758a82bb616f0037740c35e7.yaml
  changes/c2d4e325f4c46cb9ae7985097e2b364e.yaml
  changes/e3b7e45e107d35ac377e867f1a8ac725.yaml
  docker/rmlist.txt
  docker/scripts/test_all.sh
  docs/synapse/deploymentguide.rst
  synapse/cortex.py
  synapse/lib/aha.py
  synapse/lib/base.py
  synapse/lib/cell.py
  synapse/lib/config.py
  synapse/lib/layer.py
  synapse/lib/lmdbslab.py
  synapse/lib/nexus.py
  synapse/telepath.py
  synapse/tests/files/aha/certs/cas/synapse.crt
  synapse/tests/files/aha/certs/cas/synapse.key
  synapse/tests/files/aha/certs/hosts/00.aha.loop.vertex.link.crt
  synapse/tests/files/aha/certs/hosts/00.aha.loop.vertex.link.key
  synapse/tests/files/aha/certs/users/root@synapse.crt
  synapse/tests/files/aha/certs/users/root@synapse.key
  synapse/tests/files/rstorm/testsvc.py
  synapse/tests/test_axon.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_agenda.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_base.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_config.py
  synapse/tests/test_lib_nexus.py
  synapse/tests/test_lib_stormlib_aha.py
  synapse/tests/test_lib_stormlib_cell.py
  synapse/tests/test_tools_aha.py
  synapse/tests/utils.py
  synapse/tools/aha/clone.py
  synapse/tools/aha/enroll.py
Labels: enhancement

#3837 Fix backup test stability
  synapse/tests/test_lib_cell.py
Labels: bug

#3842 Update TLS support for $lib.inet.imap, $lib.inet.smtp, update aioimpaplib (SYN-7592, SYN-7800, SYN-7801)
  changes/66247462dea46da6522b61eaaddec744.yaml
  changes/bb2fcc477ab4c2984f6ef0f395435784.yaml
  pyproject.toml
  requirements.txt
  synapse/lib/stormlib/imap.py
  synapse/lib/stormlib/smtp.py
  synapse/tests/test_lib_stormlib_imap.py
  synapse/tests/test_lib_stormlib_smtp.py
Labels: enhancement

#3843 Log the path of the lmdb slab that was backed up in synapse.tools.backup.backup_lmdb (SYN-7663)
  changes/aa4866ed92e13fa3c40710010710c7fc.yaml
  synapse/tools/backup.py
Labels: enhancement

#3844 Handle possible TypeError in the Cell._initCellBoot / _bootCellMirror APIs (SYN-7511)
  changes/47e453bbec1bc6b759f3e4f5f3b5df39.yaml
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
  synapse/tests/utils.py
Labels: bug

#3846 changelog for v2.178.0
  CHANGELOG.rst
  changes/06bd1eabe999e90b2b3301ee041f7017.yaml
  changes/0d70678d970e2a045f8b1e225df8afa4.yaml
  changes/46d7d7c3fd22e158bd500f03532e7b3a.yaml
  changes/47e453bbec1bc6b759f3e4f5f3b5df39.yaml
  changes/66247462dea46da6522b61eaaddec744.yaml
  changes/6ebc22454e67c26ce57ea4533441c9fc.yaml
  changes/82ba890689de6c96e87ee71470fe680f.yaml
  changes/aa4866ed92e13fa3c40710010710c7fc.yaml
  changes/b652abf9758a82bb616f0037740c35e7.yaml
  changes/bb2fcc477ab4c2984f6ef0f395435784.yaml
  changes/c2d4e325f4c46cb9ae7985097e2b364e.yaml
  changes/dce3c3b7ac5ead37b4cfc6a1fbcad525.yaml
  changes/e3b7e45e107d35ac377e867f1a8ac725.yaml
Labels: documentation

#3852 plumbing for publication of synapse 3.0.0 alpha wheels to vtx pypi services.
  .bumpversion.cfg
  .circleci/config.yml
Labels: enhancement

#3854 Deprecate $tag trigger var (SYN-7750)
  changes/b3d387efb18aa1467d53997fdbafaa44.yaml
  docs/synapse/userguides/storm_adv_vars.rstorm
  synapse/lib/storm.py
Labels: enhancement

#3851 So many more language codes, resolves SYN-7786
  changes/0acdec9b83959f0edc4b6304585701b5.yaml
  synapse/lookup/pe.py
Labels: enhancement

#3858 Add additional fields to it:sec:stix:indicator
  changes/d1f9b7f8cd044d460780dc6719eeeadd.yaml
  synapse/models/infotech.py
  synapse/tests/test_model_infotech.py
Labels: enhancement

#3850 SYN-7804: fix slab fini order
  synapse/lib/base.py
  synapse/lib/cell.py
  synapse/tests/test_lib_cell.py
Labels: bug

#3860 Avoid logging CancelledError in taskDone
  synapse/lib/base.py
Labels: bug

#3864 Enh: `:node` property for `geo:telem`, resolves SYN-7844
  changes/76a0f7e5662b34db3d9367b28c42484b.yaml
  docs/synapse/datamodel_deprecation.rst
  synapse/models/geospace.py
  synapse/tests/test_model_geospace.py
Labels: model

#3868 Add DNS reply code enum to inet:dns:request:reply:code (SYN-7841)
  changes/697898a8c38ccf59b4284a8e1d1bbb20.yaml
  synapse/models/dns.py
  synapse/tests/test_model_dns.py
Labels: enhancement

#3865 Fix vault perm removal (SYN-7870, SYN-7872)
  changes/9c24d33e360b8204f0a488e4ebd6f8e9.yaml
  changes/b6b060e7790cd404694bb96f781c4a68.yaml
  synapse/cortex.py
  synapse/lib/stormlib/vault.py
  synapse/tests/test_lib_stormlib_vault.py
Labels: bug

#3866 Fix issue with automatic aha provisioning URL & bind precedence (SYN-7869)
  changes/3c27b826b9de26edad031a2593704ef7.yaml
  synapse/lib/aha.py
Labels: bug

#3871 Catch TypeError in stormtypes.Number (SYN-7877)
  changes/92cea56aa93a09661de3e2d129599c2b.yaml
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#3869 Fix for delDriveData replay issue
  synapse/lib/cell.py
  synapse/lib/drive.py
  synapse/tests/test_lib_cell.py
Labels: bug

#3870 Add test for provision:listen with only dns:name
  synapse/lib/aha.py
  synapse/tests/test_lib_aha.py
Labels: bug

#3863 Add force options to ext model del property APIs
  changes/2cf609e2228d21cf401d55013e3d3363.yaml
  synapse/cortex.py
  synapse/datamodel.py
  synapse/lib/coro.py
  synapse/lib/snap.py
  synapse/lib/stormlib/modelext.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_coro.py
  synapse/tests/test_lib_stormlib_modelext.py
Labels: enhancement

#3867 Improve error handling in $lib.stix.import.ingest (SYN-7837)
  changes/f2e24dc074f481337b9efedc07d20ddd.yaml
  synapse/lib/stormlib/stix.py
  synapse/tests/test_lib_stormlib_stix.py
Labels: bug

#3849 SYN-7000: ssl_opts.ca_cert
  changes/97ec15678010c07b9e9a2fd0a58c4408.yaml
  synapse/lib/cell.py
  synapse/lib/schemas.py
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: enhancement

#3872 Changelog for v2.179.0
  CHANGELOG.rst
  changes/0acdec9b83959f0edc4b6304585701b5.yaml
  changes/1ddf4c80ca6c07897e48bcad31c67d57.yaml
  changes/2cf609e2228d21cf401d55013e3d3363.yaml
  changes/3c27b826b9de26edad031a2593704ef7.yaml
  changes/3c5efeff7b96ea89e61c0a00440271bc.yaml
  changes/697898a8c38ccf59b4284a8e1d1bbb20.yaml
  changes/76a0f7e5662b34db3d9367b28c42484b.yaml
  changes/92cea56aa93a09661de3e2d129599c2b.yaml
  changes/97ec15678010c07b9e9a2fd0a58c4408.yaml
  changes/9c24d33e360b8204f0a488e4ebd6f8e9.yaml
  changes/b3d387efb18aa1467d53997fdbafaa44.yaml
  changes/b6b060e7790cd404694bb96f781c4a68.yaml
  changes/d1f9b7f8cd044d460780dc6719eeeadd.yaml
  changes/f2e24dc074f481337b9efedc07d20ddd.yaml
  docs/synapse/userguides/model_updates/update_v2_179_0.rst
  synapse/models/geospace.py
  synapse/tools/changelog.py
Labels: documentation

#3875 Update Storm nexsoffs timeout messages (SYN-7796)
  synapse/cortex.py
Labels: enhancement

#3862 Enh: Include pivot/walk info in path, resolves SYN-7716
  changes/f36fdbee7ec3a6c76cfcb7c2c03769f4.yaml
  synapse/lib/ast.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/tests/test_lib_ast.py
  synapse/tests/test_lib_node.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#3874 Add JSON schemas for STIX ingest objects (SYN-7876)
  synapse/lib/schemas.py
  synapse/lib/stormlib/stix.py
  synapse/tests/test_lib_stormlib_stix.py
Labels: enhancement

#3883 Tidy taxonomies docs
  changes/eb6aa5d9b19bb5dc5156074bd2e5a575.yaml
  docs/synapse/glossary.rst
  docs/synapse/userguides/data_model.rstorm
  docs/synapse/userguides/storm_ref_type_specific.rstorm
Labels: documentation

#3880 Add inet:service:account props to forms with inet:web:accounts
  changes/c8b96fd9ab0d825a1b619e5048be5eca.yaml
  synapse/models/auth.py
  synapse/models/inet.py
  synapse/models/person.py
  synapse/models/telco.py
  synapse/tests/test_model_inet.py
  synapse/tests/test_model_person.py
  synapse/tests/test_model_telco.py
Labels: enhancement, model

#3879 Add inet:service:object interface to most it:dev:repo forms
  changes/e855b63e60cf0727fe9c692bae3ef1c8.yaml
  synapse/models/infotech.py
Labels: enhancement, model

#3881 Update inet:email:message:link and inet:email:message:attachment to be guid forms
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: model
