Repository vertexproject/synapse, pull requests merged in 2025-05, with the labels that each got.

#4261 improve view.del documentation (SYN-8972)
  changes/10857d23b0b062631ae47cec2be19495.yaml
  docs/synapse/userguides/views_layers.rst
  synapse/lib/storm.py
Labels: bug, documentation

#4273 Add inet:service:message:mentions (SYN-9060)
  changes/2da6b534988c8487583e74d8a4340f17.yaml
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement, model

#4246 Update promotion / handoff to preserve mirror dynamism (SYN-7659)
  changes/2d1bd63239909c98ecb9ca3cb40c8002.yaml
  synapse/lib/cell.py
  synapse/lib/nexus.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
Labels: bug

#4282 Fix ambiguous value error message
  synapse/lib/storm.py
Labels: bug

#4277 Bug: Ensure that Telepath Proxy links in CLI tools are torn down (SYN-8856)
  synapse/lib/coro.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_coro.py
  synapse/tests/test_model_gov_intl.py
  synapse/tests/test_telepath.py
  synapse/tests/test_tools_aha.py
  synapse/tools/aha/clone.py
  synapse/tools/aha/easycert.py
  synapse/tools/aha/enroll.py
  synapse/tools/aha/list.py
  synapse/tools/aha/mirror.py
  synapse/tools/aha/provision/service.py
  synapse/tools/aha/provision/user.py
  synapse/tools/apikey.py
  synapse/tools/axon2axon.py
  synapse/tools/cellauth.py
  synapse/tools/cmdr.py
  synapse/tools/csvtool.py
  synapse/tools/feed.py
  synapse/tools/genpkg.py
  synapse/tools/healthcheck.py
  synapse/tools/livebackup.py
  synapse/tools/modrole.py
  synapse/tools/moduser.py
  synapse/tools/promote.py
  synapse/tools/pullfile.py
  synapse/tools/pushfile.py
  synapse/tools/reload.py
  synapse/tools/snapshot.py
  synapse/tools/storm.py
Labels: bug, enhancement

#4269 Add contact props for inet:web transition (SYN-9058)
  changes/054fa27408ae5e0cede0a6e7f25c27e0.yaml
  synapse/models/person.py
  synapse/tests/test_model_person.py
Labels: enhancement, model

#4271 Add inet:service:channel:topic (SYN-9061)
  changes/b42324c0455fd9a20dd57c1c99ec199b.yaml
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement

#4287 Fix coro import in aha provisioning tool
  synapse/tools/aha/provision/service.py
Labels: bug

#4289 Changelog for v2.210.0
  CHANGELOG.rst
  changes/054fa27408ae5e0cede0a6e7f25c27e0.yaml
  changes/10857d23b0b062631ae47cec2be19495.yaml
  changes/2d1bd63239909c98ecb9ca3cb40c8002.yaml
  changes/2da6b534988c8487583e74d8a4340f17.yaml
  changes/493590a3f353210b32fad676d882820e.yaml
  changes/75539f2b340578c24c1fd8ffb02254ce.yaml
  changes/7dc337c45d911f27deb911e1bc53d081.yaml
  changes/b42324c0455fd9a20dd57c1c99ec199b.yaml
  docs/synapse/userguides/model_updates/update_v2_210_0.rst
  synapse/tools/cellauth.py
Labels: documentation

#4292 Dev: In Base.__init__ check the parent frame code name directly.
  synapse/lib/base.py
  synapse/tests/test_lib_base.py
Labels: enhancement

#4245 Deprecated $lib.str functions (SYN-9024)
  changes/302e6db2488f498de9471bf36bf1c716.yaml
  synapse/lib/stormtypes.py
Labels: deprecation

#4290 SYN-9147: add version info to pkgdef build key
  changes/e0bb0e2291cc18ac02c8f5bb385848d3.yaml
  synapse/lib/schemas.py
  synapse/tests/test_tools_genpkg.py
  synapse/tools/genpkg.py
Labels: enhancement

#4297 Fix $node.data.list() docstring (SYN-9132)
  changes/46e53f28c3426e335855b7447b86a3ed.yaml
  synapse/lib/stormtypes.py
Labels: bug, documentation

#4303 Fix tag adds duplicating tag values (SYN-9150)
  changes/3e002ff9fcb645e008d6df6a084a8484.yaml
  synapse/lib/snap.py
  synapse/tests/test_lib_view.py
Labels: bug

#4308 Dev - remove test:str from test_storm_lib_str
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#4309 A few small inet:service additions
  synapse/models/inet.py
  synapse/tests/test_model_inet.py
Labels: enhancement, model

#4312 Add changelog for v2.211.0
  CHANGELOG.rst
  changes/3e002ff9fcb645e008d6df6a084a8484.yaml
  changes/46e53f28c3426e335855b7447b86a3ed.yaml
  changes/50df9ace36ecb1163135fe054e054b0d.yaml
  changes/e0bb0e2291cc18ac02c8f5bb385848d3.yaml
  changes/fb55c73f02536c721906d1dcdc233a40.yaml
  docs/synapse/userguides/model_updates/update_v2_211_0.rst
Labels: documentation

#4313 Cleanup inet:web deprecation comments.
  synapse/models/inet.py
Labels: deprecation

#4306 Make embeds include the embedded node form in the key "$form" . resolves SYN-8661
  changes/940149c2d5473b9a21d47939ce7e2cb9.yaml
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#4321 Changelog for v2.212.0
  CHANGELOG.rst
  changes/3a210b40204fbc79127aa4af87c81545.yaml
  changes/6d94db2443f313ce6bdc4b0eb4cae251.yaml
  changes/940149c2d5473b9a21d47939ce7e2cb9.yaml
  docs/synapse/userguides/model_updates/update_v2_212_0.rst
  synapse/tests/test_model_inet.py
Labels: enhancement, deprecation
