Repository vertexproject/synapse, pull requests merged in 2025-03, with the labels that each got.

#4167 SYN-8832: test_utils_getrefs breaks subsequent tests w/ os.unlink
  synapse/tests/test_utils_getrefs.py
  synapse/utils/getrefs.py
Labels: bug

#4162 Resolve syntax error in guid constructor when using constant in literals (SYN-8790)
  changes/8ebc9217f868e2355072a4726de39496.yaml
  synapse/lib/parser.py
  synapse/lib/storm.lark
  synapse/lib/storm_format.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_storm.py
Labels: bug

#4166 Telepath / pool optimization (SYN-8797, SYN-8823)
  changes/48c7dc3c1587b483c40dcbbcac5113a1.yaml
  changes/70190930e44c58fc96b517653b9101c6.yaml
  changes/a0ac6cea024bc6b478c5378557cdc22c.yaml
  changes/ac3f41f2d48e265898ca62412da5a6c6.yaml
  synapse/cortex.py
  synapse/lib/base.py
  synapse/lib/cell.py
  synapse/telepath.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_telepath.py
Labels: bug

#4168 Changelog for v2.202.0
  CHANGELOG.rst
  changes/48c7dc3c1587b483c40dcbbcac5113a1.yaml
  changes/70190930e44c58fc96b517653b9101c6.yaml
  changes/8ebc9217f868e2355072a4726de39496.yaml
  changes/a0ac6cea024bc6b478c5378557cdc22c.yaml
  changes/ac3f41f2d48e265898ca62412da5a6c6.yaml
Labels: documentation

#4170 Deprecate meta:seen form (SYN-8836)
  changes/3c9a8dc0efbaa6ae33030095de1b66a6.yaml
  synapse/lib/storm.py
  synapse/lib/stormlib/graph.py
  synapse/models/base.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/utils.py
Labels: enhancement, model

#4174 Do not leak references to different IO loops in the Telepath Proxy class locals
  synapse/telepath.py
Labels: bug

#4173 Update stormlib and stormtype docs to use null, true, false
  changes/743c6037967ff586e75d45288bbe9f9c.yaml
  synapse/lib/autodoc.py
  synapse/lib/stormhttp.py
  synapse/lib/stormlib/aha.py
  synapse/lib/stormlib/auth.py
  synapse/lib/stormlib/cache.py
  synapse/lib/stormlib/cortex.py
  synapse/lib/stormlib/imap.py
  synapse/lib/stormlib/model.py
  synapse/lib/stormlib/notifications.py
  synapse/lib/stormlib/oauth.py
  synapse/lib/stormlib/vault.py
  synapse/lib/stormlib/xml.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_autodoc.py
  synapse/tests/test_lib_storm.py
Labels: documentation

#4125 Update Oauth2 providers to include client_assertion based auth (SYN-8437, SYN-8458)
  changes/a91b110f56bd02fb9b95bffba5727c2c.yaml
  synapse/lib/oauth.py
  synapse/lib/schemas.py
  synapse/lib/stormlib/oauth.py
  synapse/tests/test_lib_stormlib_oauth.py
Labels: enhancement

#4181 Add missing tostr / tobool calls on stats:tally (SYN-8893)
  changes/2f8a5e14b4011b81d944dadd28e43db6.yaml
  synapse/lib/stormlib/stats.py
  synapse/tests/test_lib_stormlib_stats.py
Labels: bug

#4185 Changelog for v2.203.0
  CHANGELOG.rst
  changes/2604eaff8961455bf01c59754af1e0f9.yaml
  changes/2f8a5e14b4011b81d944dadd28e43db6.yaml
  changes/3be2f29a5e433cb1cf122d69571a3d23.yaml
  changes/3c9a8dc0efbaa6ae33030095de1b66a6.yaml
  changes/6bbd120c09e55dd15c66bda3395bfeaf.yaml
  changes/743c6037967ff586e75d45288bbe9f9c.yaml
  changes/956640827a4eef239eab0b469a67eab9.yaml
  changes/a91b110f56bd02fb9b95bffba5727c2c.yaml
  changes/e203739308c7b9753b2e91b9b3af5fe4.yaml
  changes/f180249e613528adec8366a1a8bcfa40.yaml
  docs/synapse/userguides/model_updates/update_v2_203_0.rst
Labels: documentation

#4193 Add ps:contact:id
  synapse/models/person.py
  synapse/tests/test_model_person.py
Labels: enhancement, model

#4180 Invalidate session access when account is locked (SYN-8848)
  changes/b6dc1d9ba329f0a7052a665a433bca20.yaml
  synapse/lib/auth.py
  synapse/lib/cell.py
  synapse/tests/test_lib_httpapi.py
Labels: bug

#4194 Prevent variables set within parallel from crossing into other pipelines (SYN-8809)
  changes/27445d862a834195c1e61991b1bf4e65.yaml
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#4187 Fix "not" requiring whitespace and disallow "(" and "$" in unquoted strings (SYN-8894)
  changes/3cebc8e3a3ef47d0f539cfe0e9108af0.yaml
  changes/8a673baea12460d04f275c96b8edffef.yaml
  docs/synapse/userguides/storm_ref_type_specific.rstorm
  synapse/lib/storm.lark
  synapse/tests/test_lib_grammar.py
Labels: bug

#4196 Changelog for v2.204.0
  CHANGELOG.rst
  changes/27445d862a834195c1e61991b1bf4e65.yaml
  changes/3cebc8e3a3ef47d0f539cfe0e9108af0.yaml
  changes/8a673baea12460d04f275c96b8edffef.yaml
  changes/b6dc1d9ba329f0a7052a665a433bca20.yaml
  changes/eebcae67c5d2f5d5430a7b9624fe392e.yaml
  docs/synapse/userguides/model_updates/update_v2_204_0.rst
Labels: documentation

#4199 Changelog for v2.204.1
  CHANGELOG.rst
  changes/29d02d22c2f4fcf23237a4a33e30ae7d.yaml
Labels: documentation

#4203 Add tel:phone:type and econ:acct:balance:instrument
  synapse/models/economic.py
  synapse/models/telco.py
  synapse/tests/test_model_economic.py
  synapse/tests/test_model_telco.py
Labels: enhancement, model

#4204 Move from a license trove classifer to a SPDX compatible license field per PEP-639
  pyproject.toml
Labels: documentation

#4189 fix common file helper test with appr size (SYN-8867)
  synapse/common.py
  synapse/tests/test_common.py
Labels: bug

#4206 Tests: Add an array of items with a regex opt prop to the test:arrayprop form
  synapse/tests/utils.py
Labels: enhancement

#4192 ignore or raise warns for autodocs (SYN-8791)
  .circleci/config.yml
  docs/conf.py
  docs/synapse/userguides/storm_adv_vars.rstorm
  docs/synapse/userguides/storm_ref_data_mod.rstorm
  docs/synapse/userguides/storm_ref_filter.rstorm
  docs/synapse/userguides/storm_ref_lift.rstorm
  docs/synapse/userguides/storm_ref_pivot.rstorm
  docs/synapse/userguides/storm_ref_type_specific.rstorm
  scripts/doctests.py
Labels: enhancement

#4212 Changelog for v2.205.0
  CHANGELOG.rst
  changes/8077de946625725db35cb9af9e73bebf.yaml
  changes/cb518ea29bf8bff1acbe52bb15faff73.yaml
  docs/synapse/userguides/model_updates/update_v2_205_0.rst
  synapse/models/economic.py
Labels: documentation

#4214 Add permission declarations for queues and light edges (SYN-8959, SYN-8973)
  changes/116c175a74bfbfefae62a705b3d7fe32.yaml
  synapse/cortex.py
  synapse/lib/stormtypes.py
Labels: bug
