Repository vertexproject/synapse, pull requests merged in 2025-10, with the labels that each got.

#4517 SYN-9654: :ext:creator added to proj:comment
  synapse/models/proj.py
  synapse/tests/test_model_proj.py
Labels: model

#4513 SYN-9680: `$lib.time.formats.iso8601` (and friends?)
  changes/de89bf6f84322f7c674edd518f27b006.yaml
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#4512 SYN-9735: imap tests leak stream resources
  changes/60b3b0d9fa12b20e6dea0ecb4222779b.yaml
  synapse/lib/stormlib/imap.py
  synapse/tests/test_lib_stormlib_imap.py
Labels: bug

#4521 SYN-9732: layerapi - perms checking missing await
  changes/869101b4a0182bab6d89f5a16f912c9c.yaml
  synapse/lib/layer.py
Labels: bug

#4523 Changelog for v2.224.0
  CHANGELOG.rst
  changes/2919c952353d783ca27813b3b924b092.yaml
  changes/40f5df08afa90051b98a71400b8bb73b.yaml
  changes/51e2f055eebc7d778803a76f84757227.yaml
  changes/57a190c6f5857c9e4fa2def6d128a93c.yaml
  changes/60b3b0d9fa12b20e6dea0ecb4222779b.yaml
  changes/656304d3c1efc722396f9319964aaba8.yaml
  changes/6b836bf097ed7cac4bf1b70518e554be.yaml
  changes/869101b4a0182bab6d89f5a16f912c9c.yaml
  changes/a82f566ac11365c0a52910f1a002ead8.yaml
  changes/de89bf6f84322f7c674edd518f27b006.yaml
  changes/f9f384464c155422b9b41f98ad6a13a6.yaml
  docs/synapse/userguides/model_updates/update_v2_224_0.rst
Labels: documentation
