Repository vertexproject/synapse, pull requests merged in 2025-07, with the labels that each got.

#4379 Changelog for v2.214.0.
  CHANGELOG.rst
  changes/0c93b251645651ed7ef2985fc4510a37.yaml
  changes/152e5aecbd335e4217b9d331d7ce332d.yaml
  changes/1896ab6b6fdda99d87955f9fbb9b5a3c.yaml
  changes/274a887f9373235eadc62dca543b9a03.yaml
  changes/3130807e3050ca436a0d8bc54f80c6b1.yaml
  changes/38f93d877f0d7b2c1dcb267d609778e8.yaml
  changes/4dafcc98ae69ecd9759604b51c4446f0.yaml
  changes/55985d333bcc0c1f3383b812dbad45ae.yaml
  changes/60df099ffc66cbff525ec975ea57df9c.yaml
  changes/7baf3e8e3fcddea8234cb3e1ce835738.yaml
  changes/9f92991a0588f9631ecd85cc63c61ad0.yaml
  changes/a39998f5dd79391523b9b2e61af2db10.yaml
  changes/aa5a45ec9e1b01c79321d5da687f3312.yaml
  changes/ba56868fd6953c1b4488517a55393fc3.yaml
  changes/d80ba60a223a989db29027dddabc0b71.yaml
  changes/e02872d64eacab064a16b32300f5d2b5.yaml
  changes/e33b1e265edcdb238ee1d51ebdc0f472.yaml
  changes/e4e32f9e37b7395bb7e0a501d10d8517.yaml
  changes/e7b9fce9ed5812c947b15c23ce8edc9e.yaml
  changes/ef8688d44c3162b8cb5dc4734bb39ca3.yaml
  changes/ff3ba5249ce3c2f4fc87e6cff7ebee0b.yaml
  docs/synapse/userguides/model_updates/update_v2_214_0.rst
Labels: documentation

#4386 Changelog for v2.215.0
  CHANGELOG.rst
  changes/2b7c048b0004aec821fb27525829c64f.yaml
  changes/728ba1093a0bf15eb9d5b5d88f1cf970.yaml
  changes/8279e619a59bb781ce79bbd066bea9ef.yaml
  changes/ea3b857e8d70c8700ba91b56010f2b8b.yaml
  docs/synapse/userguides/model_updates/update_v2_215_0.rst
Labels: documentation

#4372 Allow setting props with gutors
  changes/97a5befc860632c50281cb9fc64cbc9e.yaml
  synapse/lib/snap.py
  synapse/tests/test_lib_storm.py
  synapse/tests/utils.py
Labels: enhancement

#4392 SYN-9322: guid norm with a empty list/tuple is bad
  changes/0f0fccebc46aaf0d8ae619493565c5de.yaml
  synapse/lib/types.py
  synapse/tests/test_lib_storm.py
  synapse/tests/test_lib_types.py
Labels: bug

#4394 SYN-5270: reqValidRules allows zero length rules
  changes/18235243c3f15cb43927b98f36cf7501.yaml
  synapse/lib/schemas.py
  synapse/tests/test_lib_auth.py
Labels: bug

#4402 Add changelog for v2.216.0
  CHANGELOG.rst
  changes/0f0fccebc46aaf0d8ae619493565c5de.yaml
  changes/18235243c3f15cb43927b98f36cf7501.yaml
  changes/97a5befc860632c50281cb9fc64cbc9e.yaml
  changes/cc23bb136458ebab4a44a2d081796546.yaml
  docs/synapse/userguides/model_updates/update_v2_216_0.rst
Labels: enhancement

#4416 Deprecated ou:requirement ( for doc:requirement and ou:enacted )
  changes/bf7e6796f462d5bd49e0127944e34632.yaml
  synapse/models/orgs.py
Labels: model, deprecation

#4421 Changelog for v2.217.0
  CHANGELOG.rst
  docs/synapse/userguides/model_updates/update_v2_217_0.rst
Labels: documentation

#4425 SYN-8787: runas updated to plumb print/warn/err messages
  changes/0bbeb63c77c6135e476401c47b9c3a11.yaml
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug, enhancement

#4427 Dev - split the cpedata.json portion of it:sec:cpe tests into its own test
  synapse/tests/test_model_infotech.py
  synapse/tests/test_telepath.py
Labels: enhancement

#4429 Update LMDB library (SYN-9479)
  changes/79447b3152963a706243050441da8128.yaml
  pyproject.toml
  requirements.txt
Labels: enhancement

#4432 decrement def off val in fill
  changes/65da0e86a90dab5e184931bfe04ac44b.yaml
  synapse/cortex.py
Labels: bug

#4434 Changelog for v2.218.1
  CHANGELOG.rst
  changes/65da0e86a90dab5e184931bfe04ac44b.yaml
Labels: documentation
