Repository vertexproject/synapse, pull requests merged in 2025-02, with the labels that each got.

#4110 BUG SYN-8673 : fixed new task APIs return user iden and name
  synapse/lib/cell.py
  synapse/lib/task.py
  synapse/tests/test_lib_aha.py
  synapse/tests/test_lib_boss.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_task.py
Labels: bug

#4113 adds index.count.prop command
  changes/bdb33bcaca6df45be9e41132b2137ffc.yaml
  synapse/cortex.py
  synapse/lib/stormlib/index.py
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormlib_index.py
Labels: enhancement

#4114 Fix a handful of synerr exceptions without a mesg argument.
  synapse/lib/config.py
  synapse/lib/multislabseqn.py
  synapse/lib/urlhelp.py
Labels: bug

#4100 SYN-8056: archived users can have their locked status set to false
  changes/18953408aedaa83bdcbf6c96fa40409c.yaml
  changes/3860db87e644997ee1592699aa0c8008.yaml
  changes/6b7bce21bbecb3f6ea9731274665b4d4.yaml
  synapse/lib/auth.py
  synapse/lib/cell.py
  synapse/lib/hiveauth.py
  synapse/tests/test_lib_auth.py
Labels: bug

#4118 Catch regex exceptions in $lib.regex and raise BadArg (SYN-8660)
  changes/e30787a30f361212355c2cfc894c3ad0.yaml
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#4119 SYN-8647: syn:user norm assumes user name is guid when user doesn't exist
  changes/5e64ea70d917c50cab3d8148c2e7ed64.yaml
  synapse/models/syn.py
  synapse/tests/test_model_syn.py
Labels: bug, model

#4121 Fix position info on embed queries to include leading/trailing whitespace and comments (SYN-6540)
  changes/4cd9939355b22dcd8ad5bdcae6e0e0fb.yaml
  synapse/lib/parser.py
  synapse/tests/test_lib_grammar.py
  synapse/tests/test_lib_stormlib_macro.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#4126 Model additions 20250211
  synapse/models/infotech.py
  synapse/models/risk.py
  synapse/tests/test_model_infotech.py
  synapse/tests/test_model_risk.py
Labels: enhancement, model

#4122 SYN-8647: Don't accept `*` as a value for `syn:user`/`syn:role`
  changes/a014806e2981b195a520ad7ff8681b77.yaml
  synapse/models/syn.py
  synapse/tests/test_model_syn.py
Labels: bug

#4127 add new 'endpoints' conf to the pkgdef schema (SYN-8617)
  changes/15215d541cf5681e62e043e76392ab77.yaml
  synapse/lib/schemas.py
  synapse/tests/files/stormpkg/badendpoints.yaml
  synapse/tests/files/stormpkg/testpkg.yaml
  synapse/tests/test_tools_genpkg.py
Labels: enhancement

#4132 Allow lifting guid forms using a prop dictionary (SYN-8641)
  changes/14398d58633c219150a7dfa3c88660cf.yaml
  synapse/lib/snap.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#4131 Fixed an issue where the Axon failed to yield to the IO loop in certain read operations (SYN-8716)
  changes/fd8a7d62dcb7778a73c0d39ce32149c2.yaml
  synapse/axon.py
Labels: bug

#3937 improve hot slab ops (SYN-7901)
  changes/b807af812f0af5ebe692d82e05522a7f.yaml
  synapse/lib/aha.py
  synapse/lib/jsonstor.py
  synapse/lib/layer.py
  synapse/tests/test_lib_lmdbslab.py
Labels: enhancement

#4117 Allow editing node edges using variables (SYN-8670)
  changes/89fd4588c6dcfa6d74326b2809e0754c.yaml
  docs/synapse/userguides/storm_ref_data_mod.rstorm
  synapse/lib/ast.py
  synapse/lib/node.py
  synapse/lib/snap.py
  synapse/lib/storm.lark
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_grammar.py
Labels: enhancement

#4139 Changelog for v2.198.0
  CHANGELOG.rst
  changes/14398d58633c219150a7dfa3c88660cf.yaml
  changes/15215d541cf5681e62e043e76392ab77.yaml
  changes/18953408aedaa83bdcbf6c96fa40409c.yaml
  changes/2f054f3eb861d5d28d49af46561d64b4.yaml
  changes/3860db87e644997ee1592699aa0c8008.yaml
  changes/4cd9939355b22dcd8ad5bdcae6e0e0fb.yaml
  changes/5e64ea70d917c50cab3d8148c2e7ed64.yaml
  changes/6b7bce21bbecb3f6ea9731274665b4d4.yaml
  changes/89fd4588c6dcfa6d74326b2809e0754c.yaml
  changes/a014806e2981b195a520ad7ff8681b77.yaml
  changes/b807af812f0af5ebe692d82e05522a7f.yaml
  changes/c9ba311917b38203499ad4df919d8aac.yaml
  changes/e30787a30f361212355c2cfc894c3ad0.yaml
  changes/fd8a7d62dcb7778a73c0d39ce32149c2.yaml
  docs/synapse/userguides/model_updates/update_v2_198_0.rst
Labels: documentation

#4141 Add additional deprecation notices for hiveauth related APIs.
  CHANGELOG.rst
  synapse/cortex.py
  synapse/lib/hive.py
  synapse/tools/hive/load.py
Labels: enhancement

#4144 Fix Snap usage in merges
  changes/2fd8f0063e1961894ab3b80612c1eec0.yaml
  changes/e46fd4c86e4e95f75de93345ce7352e5.yaml
  synapse/lib/snap.py
  synapse/lib/storm.py
  synapse/lib/view.py
  synapse/tests/test_lib_storm.py
Labels: bug, enhancement

#4143 Avoid warning when deprecated props are set via subs (SYN-8711)
  changes/f9cc5bd59e5dd6becbbb57c3b82ce826.yaml
  synapse/lib/snap.py
  synapse/tests/test_datamodel.py
  synapse/tests/utils.py
Labels: enhancement

#4146 Changelog for v2.199.0
  CHANGELOG.rst
  changes/2fd8f0063e1961894ab3b80612c1eec0.yaml
  changes/e46fd4c86e4e95f75de93345ce7352e5.yaml
  changes/f9cc5bd59e5dd6becbbb57c3b82ce826.yaml
Labels: documentation

#4140 Remove hiveauth.py and all related functionality.
  changes/7354b1b174a3b577778dd44d4b9b82e2.yaml
  synapse/cortex.py
  synapse/lib/hive.py
  synapse/lib/hiveauth.py
  synapse/tests/test_cortex.py
  synapse/tests/test_lib_cell.py
  synapse/tests/test_lib_hive.py
  synapse/tests/test_tools_hiveload.py
  synapse/tests/test_tools_hivesave.py
  synapse/tests/utils.py
  synapse/tools/hive/load.py
Labels: enhancement

#4145 Dev relax lmdb requirement
  changes/3e33fa492b7dcb6d97b2b836a8cbadee.yaml
  pyproject.toml
  requirements.txt
Labels: enhancement

#4147 Add missing None check when filtering by alts (SYN-8731)
  changes/fe8c5da530bbb3bb684bed3d88f8f36f.yaml
  synapse/lib/snap.py
  synapse/tests/test_lib_storm.py
Labels: bug

#4150 SYN-8619: deprecated form/prop hooks
  synapse/datamodel.py
  synapse/lib/snap.py
Labels: enhancement

#4153 Changelog for v2.200.0
  CHANGELOG.rst
  changes/3e33fa492b7dcb6d97b2b836a8cbadee.yaml
  changes/7354b1b174a3b577778dd44d4b9b82e2.yaml
  changes/d5031614fcaaceae21b2eccb1b96feb3.yaml
  changes/edb3957c613c125e5414b16f33eecf9d.yaml
  changes/fe8c5da530bbb3bb684bed3d88f8f36f.yaml
Labels: documentation

#4156 Fix interface on risk:mitigation:type:taxonomy form
  changes/f0eed2916be135ccd7baba52073f8227.yaml
  synapse/models/risk.py
  synapse/tests/test_model_risk.py
Labels: bug

#4154 Remove Runtime.tick()
  synapse/lib/ast.py
  synapse/lib/storm.py
  synapse/tests/test_cortex.py
Labels: enhancement

#4160 Fix docstring typo for inet:dns:txt
  synapse/models/dns.py
Labels: bug, documentation

#4164 Allow Storm batch command to accept storm:query objects (SYN-8810)
  changes/088116698be7d5987a99e07ee4ac71e9.yaml
  synapse/lib/storm.py
  synapse/tests/test_lib_storm.py
Labels: bug

#4163 Resolve lasterrs bug in cron jobs (SYN-8744)
  changes/c2d53b410011a129e59d6ba5242a548f.yaml
  synapse/lib/agenda.py
  synapse/tests/test_lib_agenda.py
Labels: bug

#4165 Changelog for v2.201.0
  CHANGELOG.rst
  changes/088116698be7d5987a99e07ee4ac71e9.yaml
  changes/0a1c24aa21904d854db1f11f28de71d2.yaml
  changes/b8a16368b23bde3e0f517215fe55def9.yaml
  changes/c2d53b410011a129e59d6ba5242a548f.yaml
  changes/eed57a396eb932f7d7fb96ff570268c7.yaml
  changes/f0eed2916be135ccd7baba52073f8227.yaml
  docs/synapse/userguides/model_updates/update_v2_201_0.rst
Labels: documentation
