Repository vertexproject/synapse, pull requests merged in 2025-04, with the labels that each got.

#4215 Update aha.svc.mirror to print the service version alongside the synapse version (SYN-8900)
  changes/1508bffbdfc8ed831a10290dde2672cc.yaml
  synapse/lib/stormlib/aha.py
  synapse/tools/aha/mirror.py
Labels: enhancement

#4220 Fix queue.del
  synapse/lib/stormtypes.py
Labels: bug, documentation

#4218 Add ruleset edge definitions for YARA, Snort, and Service rules
  changes/2bbc359887796fb06054da368066e085.yaml
  synapse/models/base.py
Labels: enhancement, model

#4223 Changelog for v2.206.0
  CHANGELOG.rst
  changes/097fe55fd65056987f782f9f779e3250.yaml
  changes/116c175a74bfbfefae62a705b3d7fe32.yaml
  changes/1508bffbdfc8ed831a10290dde2672cc.yaml
  changes/2818bb8ad6820cf69d477f8984d1cf8c.yaml
  changes/2bbc359887796fb06054da368066e085.yaml
  changes/5bc9697951b7c5b83a6bced86e256a10.yaml
  changes/805e1b53761ec5c94f585b65dbd0f5b4.yaml
  changes/af0603a5aef92f347e1d1c6a5292cddd.yaml
  changes/c68703107768a6df0c087c3a0e3e1238.yaml
  docs/synapse/userguides/model_updates/update_v2_206_0.rst
Labels: documentation

#4224 Ensure inet:http:resp header keys are strings (SYN-9015)
  changes/d8d16db63f04b6c5dd8ef58309260dd7.yaml
  synapse/lib/stormhttp.py
  synapse/tests/test_lib_stormhttp.py
Labels: bug

#4227 Add $str.join() method (SYN-2093)
  changes/312ea74ce7eff1090d36b160c6d198a8.yaml
  synapse/lib/stormtypes.py
  synapse/tests/test_lib_stormtypes.py
Labels: enhancement

#4232 Changelog for v2.207.0
  CHANGELOG.rst
  changes/312ea74ce7eff1090d36b160c6d198a8.yaml
  changes/d8d16db63f04b6c5dd8ef58309260dd7.yaml
Labels: documentation

#4235 Fix json serialization for axon wget/wput apis for local axons (SYN-9015)
  CHANGELOG.rst
  synapse/axon.py
  synapse/tests/test_axon.py
Labels: bug

#4186 SYN-8845: demote runstorm tasks
  .circleci/config.yml
  changes/1a225d84d0c27aa6258256145b6d5af4.yaml
  synapse/lib/boss.py
  synapse/lib/task.py
  synapse/lib/view.py
  synapse/tests/test_lib_boss.py
  synapse/tests/test_lib_nexus.py
  synapse/tests/test_lib_stormlib_storm.py
Labels: enhancement

#4241 Changelog for v2.187.1
  CHANGELOG.rst
  changes/805e1b53761ec5c94f585b65dbd0f5b4.yaml
Labels: documentation

#4236 cherry-pick cpe migration changes from 2.187.1 dev branch
  synapse/lib/modelrev.py
Labels: bug

#4240 Update fjs, idna, cryptodome, and pygments
  pyproject.toml
  requirements.txt
  synapse/tests/test_lib_stormsvc.py
Labels: enhancement

#4237 SYN-8869: pkg onloads surviving a cortex restart
  changes/c29a4eff442f81b14e7ffe92ec977af7.yaml
  synapse/cortex.py
  synapse/tests/test_lib_storm.py
Labels: enhancement

#4234 Fix escape character issue in backtick strings (SYN-9037)
  changes/aa2b97230dd409875c8122afaf947d76.yaml
  synapse/lib/storm.lark
  synapse/tests/test_lib_storm.py
Labels: bug

#4230 anchor to UTC for timezone offset calculations (SYN-9036)
  changes/0e9736eaa0eef92f2d033cc8e5059bac.yaml
  pyproject.toml
  requirements.txt
  synapse/lib/time.py
  synapse/tests/test_lib_stormtypes.py
Labels: bug

#4264 Changelog for v2.209.0
  CHANGELOG.rst
  changes/47b6d1884e16c8fcdd86ba8450a9ddd0.yaml
  changes/caeeac902c4e05c7872ee2925ee14bcf.yaml
Labels: documentation

#4272 Update vtx-yyjson minver
  pyproject.toml
  requirements.txt
Labels: enhancement

#4267 Deprecate user notification subsystem (SYN-9031)
  changes/7dc337c45d911f27deb911e1bc53d081.yaml
  synapse/lib/stormlib/auth.py
  synapse/lib/stormlib/notifications.py
Labels: deprecation
